--
-- PostgreSQL database dump
--

\restrict LkHDGXsAwmB0d1rIOK1EKZElGml9AdijkFHIQf7Z3flXt5mfd3T23QIU0cheTXo

-- Dumped from database version 17.11 (Ubuntu 17.11-1.pgdg24.04+2)
-- Dumped by pg_dump version 17.11 (Ubuntu 17.11-1.pgdg24.04+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: order_status; Type: TYPE; Schema: public; Owner: jjf
--

CREATE TYPE public.order_status AS ENUM (
    'pending',
    'paid',
    'shipped',
    'cancelled'
);


ALTER TYPE public.order_status OWNER TO jjf;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: customers; Type: TABLE; Schema: public; Owner: jjf
--

CREATE TABLE public.customers (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    display_name character varying,
    note text,
    referrer_id bigint,
    nicknames character varying(30)[],
    tags text[],
    profile jsonb DEFAULT '{}'::jsonb NOT NULL,
    external_id uuid DEFAULT gen_random_uuid() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    born_on date,
    balance numeric(10,2) DEFAULT 0 NOT NULL,
    registered_at timestamp(3) without time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.customers OWNER TO jjf;

--
-- Name: TABLE customers; Type: COMMENT; Schema: public; Owner: jjf
--

COMMENT ON TABLE public.customers IS '顧客
オンラインショップの利用者。退会しても行は残す。';


--
-- Name: COLUMN customers.email; Type: COMMENT; Schema: public; Owner: jjf
--

COMMENT ON COLUMN public.customers.email IS 'メールアドレス';


--
-- Name: COLUMN customers.balance; Type: COMMENT; Schema: public; Owner: jjf
--

COMMENT ON COLUMN public.customers.balance IS '残高';


--
-- Name: customers_id_seq; Type: SEQUENCE; Schema: public; Owner: jjf
--

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_lines; Type: TABLE; Schema: public; Owner: jjf
--

CREATE TABLE public.order_lines (
    order_id bigint NOT NULL,
    line_no integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer DEFAULT 1 NOT NULL,
    unit_price numeric(10,2) NOT NULL
);


ALTER TABLE public.order_lines OWNER TO jjf;

--
-- Name: TABLE order_lines; Type: COMMENT; Schema: public; Owner: jjf
--

COMMENT ON TABLE public.order_lines IS '注文明細';


--
-- Name: orders; Type: TABLE; Schema: public; Owner: jjf
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    customer_id bigint NOT NULL,
    status public.order_status DEFAULT 'pending'::public.order_status NOT NULL,
    placed_at timestamp with time zone DEFAULT now() NOT NULL,
    shipped_at timestamp with time zone,
    total numeric(10,2) NOT NULL
);


ALTER TABLE public.orders OWNER TO jjf;

--
-- Name: TABLE orders; Type: COMMENT; Schema: public; Owner: jjf
--

COMMENT ON TABLE public.orders IS '注文';


--
-- Name: COLUMN orders.status; Type: COMMENT; Schema: public; Owner: jjf
--

COMMENT ON COLUMN public.orders.status IS '注文状態';


--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: jjf
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: jjf
--

CREATE TABLE public.products (
    id integer NOT NULL,
    sku character varying(32) NOT NULL,
    name text NOT NULL,
    price numeric(10,2) NOT NULL,
    weight double precision,
    released_on date
);


ALTER TABLE public.products OWNER TO jjf;

--
-- Name: TABLE products; Type: COMMENT; Schema: public; Owner: jjf
--

COMMENT ON TABLE public.products IS '商品';


--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: jjf
--

CREATE SEQUENCE public.products_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.products_id_seq OWNER TO jjf;

--
-- Name: products_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: jjf
--

ALTER SEQUENCE public.products_id_seq OWNED BY public.products.id;


--
-- Name: shipments; Type: TABLE; Schema: public; Owner: jjf
--

CREATE TABLE public.shipments (
    order_id bigint NOT NULL,
    line_no integer NOT NULL,
    carrier character varying(64) NOT NULL,
    tracking_no character varying(64),
    shipped_on date NOT NULL
);


ALTER TABLE public.shipments OWNER TO jjf;

--
-- Name: TABLE shipments; Type: COMMENT; Schema: public; Owner: jjf
--

COMMENT ON TABLE public.shipments IS '配送';


--
-- Name: products id; Type: DEFAULT; Schema: public; Owner: jjf
--

ALTER TABLE ONLY public.products ALTER COLUMN id SET DEFAULT nextval('public.products_id_seq'::regclass);


--
-- Name: customers customers_email_key; Type: CONSTRAINT; Schema: public; Owner: jjf
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_email_key UNIQUE (email);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: jjf
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- Name: order_lines order_lines_pkey; Type: CONSTRAINT; Schema: public; Owner: jjf
--

ALTER TABLE ONLY public.order_lines
    ADD CONSTRAINT order_lines_pkey PRIMARY KEY (order_id, line_no);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: jjf
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: jjf
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: shipments shipments_carrier_tracking_key; Type: CONSTRAINT; Schema: public; Owner: jjf
--

ALTER TABLE ONLY public.shipments
    ADD CONSTRAINT shipments_carrier_tracking_key UNIQUE (carrier, tracking_no);


--
-- Name: shipments shipments_pkey; Type: CONSTRAINT; Schema: public; Owner: jjf
--

ALTER TABLE ONLY public.shipments
    ADD CONSTRAINT shipments_pkey PRIMARY KEY (order_id, line_no);


--
-- Name: orders_customer_id_idx; Type: INDEX; Schema: public; Owner: jjf
--

CREATE INDEX orders_customer_id_idx ON public.orders USING btree (customer_id);


--
-- Name: orders_status_placed_at_idx; Type: INDEX; Schema: public; Owner: jjf
--

CREATE INDEX orders_status_placed_at_idx ON public.orders USING btree (status, placed_at);


--
-- Name: products_sku_key; Type: INDEX; Schema: public; Owner: jjf
--

CREATE UNIQUE INDEX products_sku_key ON public.products USING btree (sku);


--
-- Name: customers customers_referrer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jjf
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_referrer_id_fkey FOREIGN KEY (referrer_id) REFERENCES public.customers(id) ON DELETE SET NULL;


--
-- Name: order_lines order_lines_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jjf
--

ALTER TABLE ONLY public.order_lines
    ADD CONSTRAINT order_lines_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;


--
-- Name: order_lines order_lines_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jjf
--

ALTER TABLE ONLY public.order_lines
    ADD CONSTRAINT order_lines_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: orders orders_customer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jjf
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: shipments shipments_line_fkey; Type: FK CONSTRAINT; Schema: public; Owner: jjf
--

ALTER TABLE ONLY public.shipments
    ADD CONSTRAINT shipments_line_fkey FOREIGN KEY (order_id, line_no) REFERENCES public.order_lines(order_id, line_no) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict LkHDGXsAwmB0d1rIOK1EKZElGml9AdijkFHIQf7Z3flXt5mfd3T23QIU0cheTXo

