package svg

import (
	"bufio"
	"encoding/xml"
	"fmt"
	"io"
	"strconv"
)

// ---------------------------------------------------------------------------
// The document skeleton
// ---------------------------------------------------------------------------

// writeScene serialises a Scene as an SVG document.
//
// Everything below this line is serialization and nothing else: it turns the
// numbers and strings a Scene already holds into elements and attributes, and
// has no drawing decision left to make. There is no rank here, no cardinality,
// no row height and no font role, and TestWriteSceneBuiltByHand is what keeps
// it that way - it assembles a Scene out of Go literals with no Document and
// no layout anywhere in it, so the day the writer needs one of those things
// that test stops compiling.
//
// # One element per line
//
// Every element is written on a line of its own, and the golden files are the
// bytes that produces. It costs a newline per element and buys two things: a
// golden diff a person can read, and the ability for a structural test to scan
// lines - the same shape internal/export/dot/golden_test.go's htmlLabels
// depends on for DOT. Document text cannot break it either, because
// xml.EscapeText turns a newline inside a logical name into &#xA; rather than
// passing the byte through.
//
// # Nothing in the file identifies this build
//
// No timestamp, no jjf version, no input path - the reasoning writeGraph
// already carries for the DOT header: a version would make two builds of jjf
// disagree about the same document, and a path would make the output depend on
// where the input happened to sit.
func writeScene(w *bufio.Writer, s Scene) {
	// The declaration is here for the same reason the DOT output sets
	// charset="UTF-8": a Japanese logical name has to be read as UTF-8 whatever
	// the reader's locale says, and a renderer handed a file with no
	// declaration guesses.
	io.WriteString(w, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n")
	io.WriteString(w, "<!-- Generated by jjf from a database design document. -->\n")
	io.WriteString(w, "<!-- The JSON is the source of truth: edit it and export again, never this file. -->\n")

	// width and height as well as viewBox: an <img> referencing an SVG with
	// neither scales the drawing to its container, and some rsvg-convert
	// versions fall back to a default size. The viewBox starts at 0 0 because
	// moveToMargin put every coordinate in the drawing at or past the margin.
	fmt.Fprintf(w, "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"%s\" height=\"%s\" viewBox=\"0 0 %s %s\">\n",
		formatCoord(s.Width), formatCoord(s.Height), formatCoord(s.Width), formatCoord(s.Height))

	// The four arms are the whole of Item, which is closed by an unexported
	// method - so a fifth primitive cannot arrive from outside the package, and
	// adding one here is a visible edit to this switch rather than an item
	// silently dropped on the floor. There is deliberately no default: the
	// compiler cannot check a type switch for exhaustiveness, and a default
	// that drew something plausible would hide the omission instead of leaving
	// it where TestSceneItemOrder's paint-order lists can see it.
	for _, item := range s.Items {
		switch it := item.(type) {
		case Box:
			writeRect(w, it)
		case Polyline:
			writePolyline(w, it)
		case Circle:
			writeCircle(w, it)
		case TextRun:
			writeText(w, it)
		}
	}

	io.WriteString(w, "</svg>\n")
}

// ---------------------------------------------------------------------------
// The four primitives
// ---------------------------------------------------------------------------

// Presentation attributes, and never a class, a style attribute or a <style>
// block (D27).
//
// GitHub's SVG sanitiser strips class and style, so a diagram styled that way
// is right in a browser and wrong in the README it was made for. A <style>
// block does survive when the file is referenced with <img src> rather than
// inlined, but relying on the difference between the two embedding paths is a
// trap: the same file would render two ways depending on how somebody chose to
// embed it. Attributes work in both, at the cost of repeating the paint on
// every element - which is bytes, and bytes are the cheapest thing here.
//
// No <marker> either (D25), which is why every crow's foot arrives here as a
// Polyline that scene construction has already placed. A marker at the START of
// a path orients along the outgoing direction, so a crow's foot at the tail
// faces backwards unless orient="auto-start-reverse" is used - which is SVG 2,
// and which librsvg does not implement (librsvg#484). It would look right in a
// browser and be silently reversed in rsvg-convert. Orthogonal routing means
// the attachment point and the outgoing direction are both known exactly at
// emission time, so a marker's only real value is redundant here.

// writeRect emits one <rect>.
//
// The stroke attributes are omitted when there is no stroke, which is not the
// writer deciding anything: the page background is the one Box with an empty
// Stroke, and an empty colour is not a colour SVG can be given. Everything
// else about the element is written unconditionally, including a stroke width
// that happens to equal the default, because the Scene resolved it and the
// writer's job is to say what the Scene says.
func writeRect(w *bufio.Writer, b Box) {
	fmt.Fprintf(w, "\t<rect x=\"%s\" y=\"%s\" width=\"%s\" height=\"%s\" fill=\"%s\"",
		formatCoord(b.Rect.X), formatCoord(b.Rect.Y), formatCoord(b.Rect.W), formatCoord(b.Rect.H), b.Fill)
	if b.Stroke != "" {
		fmt.Fprintf(w, " stroke=\"%s\" stroke-width=\"%s\"", b.Stroke, formatCoord(b.StrokeWidth))
	}
	// The pattern is spelled here because Box carries a FLAG and not a dash
	// pattern: there is exactly one dashed thing in this drawing, the stub box,
	// so a pattern in the Scene would be a presentation knob no document can
	// reach. Both lengths come from one constant, so the dashes and the gaps
	// cannot drift apart.
	if b.Dash {
		fmt.Fprintf(w, " stroke-dasharray=\"%s %s\"", formatCoord(dashLen), formatCoord(dashLen))
	}
	io.WriteString(w, "/>\n")
}

// writePolyline emits one <polyline>: a route, a row separator, a crow's foot
// or a cardinality bar.
//
// fill comes from the Scene rather than being written as "none" here, even
// though it is always "none", because SVG fills a <polyline> BLACK when nothing
// says otherwise - so the value is load-bearing, and a writer that supplied it
// would be making the one kind of decision this layer may not make.
func writePolyline(w *bufio.Writer, p Polyline) {
	io.WriteString(w, "\t<polyline points=\"")
	for i, pt := range p.Points {
		if i > 0 {
			io.WriteString(w, " ")
		}
		io.WriteString(w, formatCoord(pt.X)+","+formatCoord(pt.Y))
	}
	fmt.Fprintf(w, "\" fill=\"%s\" stroke=\"%s\" stroke-width=\"%s\"/>\n",
		p.Fill, p.Stroke, formatCoord(p.StrokeWidth))
}

// writeCircle emits one <circle>: the optionality mark, and the only curve in
// the drawing.
func writeCircle(w *bufio.Writer, c Circle) {
	fmt.Fprintf(w, "\t<circle cx=\"%s\" cy=\"%s\" r=\"%s\" fill=\"%s\" stroke=\"%s\" stroke-width=\"%s\"/>\n",
		formatCoord(c.Centre.X), formatCoord(c.Centre.Y), formatCoord(c.R),
		c.Fill, c.Stroke, formatCoord(c.StrokeWidth))
}

// writeText emits one <text> on its BASELINE.
//
// There is no dominant-baseline anywhere in this package (D26): GitHub's SVG
// sanitiser strips it from <text> nodes (github/markup#1160), so text centred
// that way is correct in a browser and misaligned in the README the diagram was
// made for. The baseline is therefore computed during layout and text-anchor,
// which survives sanitisation, does the horizontal half.
func writeText(w *bufio.Writer, t TextRun) {
	fmt.Fprintf(w, "\t<text x=\"%s\" y=\"%s\" font-family=\"%s\" font-size=\"%s\" font-weight=\"%s\" text-anchor=\"%s\" fill=\"%s\">",
		formatCoord(t.At.X), formatCoord(t.At.Y), t.Family, formatCoord(t.Size), t.Weight, t.Anchor, t.Fill)
	escape(w, t.Text)
	io.WriteString(w, "</text>\n")
}

// ---------------------------------------------------------------------------
// Text, and the numbers
// ---------------------------------------------------------------------------

// escape writes s as XML character data, through encoding/xml's EscapeText.
//
// # What it is for
//
// EscapeText does BOTH halves of the job, in the right order: it replaces every
// rune outside XML 1.0's Char production with U+FFFD, and then escapes the
// markup characters. The first half is the one that is easy to forget and
// impossible to recover from. $defs/logicalName in the schema has a maxLength
// and no pattern, and jjf validate only counts runes - so a document may quite
// legally carry U+0001 or U+FFFE in a logical name, and such a rune does not
// render badly, it makes the file NOT WELL-FORMED. A renderer's answer to that
// is an error, not a diagram.
//
// # Why this is not a predicate written here
//
// The obvious alternative was to write the XML 1.0 character predicate out and
// filter with it. It was not taken because that predicate is, byte for byte,
// isInCharacterRange in encoding/xml itself: copying standard library code into
// a project whose rules say to prefer the standard library is the wrong
// direction, and the copy would then have to be kept in step with a spec it
// cannot see.
//
// Verified behaviour with go 1.26.5, run rather than assumed: U+0001, U+000B,
// U+FFFE and U+FFFF each become the literal U+FFFD; U+FDD0 and the other
// noncharacters that Char does permit survive unchanged, so it is not
// over-filtering; & < > become the named entities and " and ' become &#34; and
// &#39;; tab, LF and CR become &#x9; &#xA; &#xD;. Invalid UTF-8 becomes U+FFFD
// too, though nothing here can reach that case: encoding/json has already
// substituted by the time a document exists.
//
// The one thing to know about relying on it: the U+FFFD substitution is what go
// 1.26.5 does and has done for many releases, but the doc comment does not
// promise it. TestEscapeTextSubstitutesInvalidRunes pins the answer for the
// runes that matter, so a future Go changing it is reported here; and
// TestFixturesAreWellFormedXML parses the whole output of a fixture that
// carries U+0001, so even with the pin deleted the malformed file would fail a
// test rather than ship.
//
// # What goes through it
//
// Every string in a Scene that can hold document text - and today that is
// exactly one field, TextRun.Text, which carries a table's names, a column's
// name, logical name and rendered type, a relationship's label and the stub
// sentence. It is applied to all of them uniformly, including the ones the
// schema's identifier pattern says cannot need it, so that no reviewer has to
// work out which ones can.
//
// The other strings a Scene holds - the colours, the anchors, the weights and
// the font family - are constants this package chose, not document text, and
// they are written straight into their attributes. fontFamily's own comment
// says why that is safe rather than lucky: the family names are single-quoted
// precisely so that the value needs no escaping inside a double-quoted XML
// attribute. If a Scene field ever starts carrying document text, it comes
// through here too.
//
// The error is dropped for the reason Export's comment gives: the bufio.Writer
// latches its first write error and turns every later write into a no-op, so
// Flush is the single place a failure can surface.
func escape(w *bufio.Writer, s string) {
	xml.EscapeText(w, []byte(s))
}

// formatCoord writes c as an SVG user-space length: a whole number of pixels,
// with one decimal digit when the tenth is not zero, and no trailing ".0".
//
// This is the ONLY function in the package that can produce a decimal point,
// which is what makes "there is no floating point in internal/export/svg" a
// rule a reader can check by grep rather than one they have to take on trust.
// A Coord is a tenth of a pixel (see unit), so the conversion is one integer
// division and one remainder, and 1200 comes out as "120" while 1205 comes out
// as "120.5".
//
// The sign is handled explicitly even though a finished Geometry has no
// negative coordinate in it - every one is at least the margin, which
// TestBoundsStartAtOrigin asserts. A Scene is a plain struct that anything can
// build, TestWriteSceneBuiltByHand builds one, and the arithmetic without the
// sign split would spell -5 as "0.-5": a wrong answer in a file, rather than a
// failure, is the worse outcome of the two.
func formatCoord(c Coord) string {
	sign := ""
	if c < 0 {
		sign, c = "-", -c
	}
	whole := strconv.FormatInt(int64(c/unit), 10)
	if tenth := c % unit; tenth != 0 {
		return sign + whole + "." + strconv.FormatInt(int64(tenth), 10)
	}
	return sign + whole
}
