package svg

import (
	"bufio"
	"bytes"
	"errors"
	"strings"
	"testing"

	"github.com/shutx-net/jumping-json-flush/internal/exitcode"
	"github.com/shutx-net/jumping-json-flush/internal/model"
)

// render exports doc and returns the SVG source. The documents in this file are
// Go literals rather than fixtures: what is under test is the shape of the
// output for one document shape at a time, and a literal keeps the shape and
// the assertion next to each other. The JSON fixtures under testdata/ render
// whole documents and are frozen as goldens instead.
func render(t *testing.T, doc *model.Document) string {
	t.Helper()
	var buf bytes.Buffer
	if err := Export(&buf, doc); err != nil {
		t.Fatalf("Export: %v", err)
	}
	return buf.String()
}

// writeOnly serialises a Scene with no Document and no layout involved, which
// is the only way the seam test is allowed to reach the writer.
func writeOnly(t *testing.T, s Scene) string {
	t.Helper()
	var buf bytes.Buffer
	bw := bufio.NewWriter(&buf)
	writeScene(bw, s)
	if err := bw.Flush(); err != nil {
		t.Fatalf("flush: %v", err)
	}
	return buf.String()
}

// ---------------------------------------------------------------------------
// The seam
// ---------------------------------------------------------------------------

// TestWriteSceneBuiltByHand is the compiler-checked form of the claim the two
// representations exist for (D05): the writer's input is a Scene, and a Scene is
// buildable out of nothing but numbers and strings.
//
// It mentions no Document, no Geometry and no layout call, and it never will -
// the day the writer needs a row height, a rank, a cardinality or a font role
// to produce its bytes, this test cannot be written and therefore cannot
// compile. That is what a second package would have bought, without exporting
// the whole geometry model to get it.
//
// The bytes are asserted in full rather than probed, because this is also where
// the element grammar is pinned: attribute order, the dashed stroke, the omitted
// stroke on a fill-only rect, one element per line, and the trailing newline
// after </svg>.
func TestWriteSceneBuiltByHand(t *testing.T) {
	scene := Scene{
		Width:  4000,
		Height: 2000,
		Items: []Item{
			Box{Rect: Rect{W: 4000, H: 2000}, Fill: "#ffffff"},
			Box{
				Rect: Rect{X: 100, Y: 205, W: 1200, H: 400},
				Fill: "#f4f4f4", Stroke: "#9a9a9a", StrokeWidth: 10, Dash: true,
			},
			Polyline{
				Points:      []Point{{X: 1300, Y: 405}, {X: 2000, Y: 405}, {X: 2000, Y: 1005}},
				Stroke:      "#333333",
				StrokeWidth: 10,
				Fill:        "none",
			},
			Circle{Centre: Point{X: 2000, Y: 1005}, R: 30, Fill: "#ffffff", Stroke: "#333333", StrokeWidth: 10},
			TextRun{
				At: Point{X: 700, Y: 305}, Text: "顧客", Family: "'Menlo', monospace",
				Size: 120, Weight: "bold", Anchor: "middle", Fill: "#1a1a1a",
			},
			TextRun{
				At: Point{X: 160, Y: 505}, Text: "a & b < c", Family: "'Menlo', monospace",
				Size: 120, Weight: "normal", Anchor: "start", Fill: "#1a1a1a",
			},
			TextRun{
				At: Point{X: 2000, Y: 1500}, Text: "fk_orders_customer", Family: "'Menlo', monospace",
				Size: 120, Weight: "normal", Anchor: "middle", Fill: "#1a1a1a",
			},
		},
	}

	want := strings.Join([]string{
		`<?xml version="1.0" encoding="UTF-8"?>`,
		`<!-- Generated by jjf from a database design document. -->`,
		`<!-- The JSON is the source of truth: edit it and export again, never this file. -->`,
		`<svg xmlns="http://www.w3.org/2000/svg" width="400" height="200" viewBox="0 0 400 200">`,
		"\t" + `<rect x="0" y="0" width="400" height="200" fill="#ffffff"/>`,
		"\t" + `<rect x="10" y="20.5" width="120" height="40" fill="#f4f4f4" stroke="#9a9a9a" stroke-width="1" stroke-dasharray="4 4"/>`,
		"\t" + `<polyline points="130,40.5 200,40.5 200,100.5" fill="none" stroke="#333333" stroke-width="1"/>`,
		"\t" + `<circle cx="200" cy="100.5" r="3" fill="#ffffff" stroke="#333333" stroke-width="1"/>`,
		"\t" + `<text x="70" y="30.5" font-family="'Menlo', monospace" font-size="12" font-weight="bold" text-anchor="middle" fill="#1a1a1a">顧客</text>`,
		"\t" + `<text x="16" y="50.5" font-family="'Menlo', monospace" font-size="12" font-weight="normal" text-anchor="start" fill="#1a1a1a">a &amp; b &lt; c</text>`,
		"\t" + `<text x="200" y="150" font-family="'Menlo', monospace" font-size="12" font-weight="normal" text-anchor="middle" fill="#1a1a1a">fk_orders_customer</text>`,
		`</svg>`,
		"",
	}, "\n")

	if got := writeOnly(t, scene); got != want {
		t.Errorf("the writer produced\n%s\nwant\n%s", got, want)
	}
}

// ---------------------------------------------------------------------------
// Numbers
// ---------------------------------------------------------------------------

func TestFormatCoord(t *testing.T) {
	tests := []struct {
		in   Coord
		want string
	}{
		{0, "0"},
		{10, "1"},
		{1200, "120"},
		{1205, "120.5"},
		{5, "0.5"},
		{15, "1.5"},
		{-5, "-0.5"},
		{-1200, "-120"},
	}

	for _, tt := range tests {
		if got := formatCoord(tt.in); got != tt.want {
			t.Errorf("formatCoord(%d) = %q, want %q", tt.in, got, tt.want)
		}
	}
}

// TestFormatCoordIsTheOnlyDecimalPoint checks the claim formatCoord's comment
// makes, against the actual bytes of a whole rendered document: every "." in the
// file comes from a coordinate this function wrote, or from a piece of document
// text. Nothing else in the package can produce one, because there is no
// floating point in it.
func TestFormatCoordIsTheOnlyDecimalPoint(t *testing.T) {
	out := render(t, document(linked("customers"), linked("orders", "customers")))

	for _, line := range strings.Split(out, "\n") {
		// Only the item lines, which are the indented ones. The prologue's own
		// dots are in prose and a URL, and the root element's numbers are
		// pinned byte for byte by TestWriteSceneBuiltByHand.
		if !strings.HasPrefix(line, "\t") {
			continue
		}
		// Splitting on the quote puts every attribute VALUE at an odd index and
		// everything outside the quotes at an even one, so a dot in a logical
		// name - which is document text, not a number - is not examined here.
		fields := strings.Split(line, "\"")
		for i := 1; i < len(fields); i += 2 {
			// A coordinate list, or one number: every dot in it must have a
			// digit on both sides, which is what formatCoord produces and what
			// a stray %f or a truncated ".0" would not.
			for _, number := range strings.FieldsFunc(fields[i], func(r rune) bool { return r == ' ' || r == ',' }) {
				at := strings.Index(number, ".")
				if at < 0 {
					continue
				}
				if at == 0 || at == len(number)-1 || strings.Count(number, ".") != 1 {
					t.Errorf("the output holds %q, which is not a number formatCoord can produce:\n%s", number, line)
				}
			}
		}
	}
}

// ---------------------------------------------------------------------------
// Escaping
// ---------------------------------------------------------------------------

// escaped renders one string through the writer the way document text reaches
// it, and returns the text content of the element it landed in.
func escaped(t *testing.T, s string) string {
	t.Helper()
	out := writeOnly(t, Scene{Items: []Item{TextRun{Text: s}}})
	const opener, closer = ">", "</text>"
	i := strings.Index(out, "<text")
	if i < 0 {
		t.Fatalf("no <text> element in\n%s", out)
	}
	rest := out[i:]
	return rest[strings.Index(rest, opener)+len(opener) : strings.Index(rest, closer)]
}

func TestEscapeMarkupCharacters(t *testing.T) {
	tests := []struct {
		in   string
		want string
	}{
		{"a & b", "a &amp; b"},
		{"<図>", "&lt;図&gt;"},
		{`"面"`, "&#34;面&#34;"},
		{"it's", "it&#39;s"},
		{"グラフ & <図> \"面\"", "グラフ &amp; &lt;図&gt; &#34;面&#34;"},
	}

	for _, tt := range tests {
		if got := escaped(t, tt.in); got != tt.want {
			t.Errorf("%q came out as %q, want %q", tt.in, got, tt.want)
		}
	}
}

// TestEscapeTextSubstitutesInvalidRunes is the pin escape's comment describes.
//
// It asserts the half of xml.EscapeText that the doc comment does not promise:
// a rune outside XML 1.0's Char production is REPLACED by U+FFFD rather than
// passed through. That is what stops a logical name carrying U+0001 - which the
// schema permits and jjf validate accepts - from producing a file no renderer
// will parse. If a future Go release changes the substitution, this test is
// where it is reported, rather than a malformed .svg in somebody's README.
//
// U+FDD0 is in the list for the opposite reason: XML 1.0's Char production
// PERMITS the noncharacters, so a rune surviving unchanged is the check that
// EscapeText is not over-filtering and quietly damaging legal text.
func TestEscapeTextSubstitutesInvalidRunes(t *testing.T) {
	const replacement = "\uFFFD"

	tests := []struct {
		name string
		in   string
		want string
	}{
		{"U+0001, a C0 control XML 1.0 forbids", "a\u0001b", "a" + replacement + "b"},
		{"U+000B, the other forbidden control that looks like whitespace", "a\u000Bb", "a" + replacement + "b"},
		{"U+FFFE, a noncharacter Char excludes", "a\uFFFEb", "a" + replacement + "b"},
		{"U+FFFF, likewise", "a\uFFFFb", "a" + replacement + "b"},
		{"U+FDD0, a noncharacter Char permits, survives", "a\uFDD0b", "a\uFDD0b"},
		{"tab is numeric-escaped, not passed through", "a\tb", "a&#x9;b"},
		{"a newline cannot break the one-element-per-line rule", "a\nb", "a&#xA;b"},
		{"carriage return likewise", "a\rb", "a&#xD;b"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := escaped(t, tt.in); got != tt.want {
				t.Errorf("%q came out as %q, want %q", tt.in, got, tt.want)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// The file around the drawing
// ---------------------------------------------------------------------------

func TestExportHeader(t *testing.T) {
	out := render(t, document(linked("customers")))
	lines := strings.Split(out, "\n")

	want := []string{
		`<?xml version="1.0" encoding="UTF-8"?>`,
		"<!-- Generated by jjf from a database design document. -->",
		"<!-- The JSON is the source of truth: edit it and export again, never this file. -->",
	}
	for i, line := range want {
		if i >= len(lines) {
			t.Fatalf("the output has only %d lines, want at least %d", len(lines), len(want))
		}
		if lines[i] != line {
			t.Errorf("line %d = %q, want %q", i+1, lines[i], line)
		}
	}

	// The root element carries all four attributes, in a fixed order, and the
	// viewBox starts at the origin.
	svg := lines[len(want)]
	if !strings.HasPrefix(svg, `<svg xmlns="http://www.w3.org/2000/svg" width="`) {
		t.Errorf("the root element is %q", svg)
	}
	for _, attribute := range []string{" width=\"", " height=\"", ` viewBox="0 0 `} {
		if !strings.Contains(svg, attribute) {
			t.Errorf("the root element has no %s attribute: %q", strings.TrimSpace(attribute), svg)
		}
	}

	if !strings.HasSuffix(out, "</svg>\n") || strings.HasSuffix(out, "\n\n</svg>\n") {
		t.Errorf("the output does not end with a single closing tag line:\n%q", out[max(0, len(out)-40):])
	}
}

// TestExportHeaderHasNothingNondeterministic probes for the three ways a build
// could leak into the file: a version would make two builds of jjf disagree
// about one document, a path would make the output depend on where the input
// sat, and a year is how a timestamp shows up.
func TestExportHeaderHasNothingNondeterministic(t *testing.T) {
	out := render(t, document(linked("customers")))
	prologue := strings.SplitN(out, "<svg", 2)[0]

	for _, unwanted := range []string{"jjf version", ".json", "20"} {
		if strings.Contains(prologue, unwanted) {
			t.Errorf("the prologue mentions %q, which would break determinism:\n%s", unwanted, prologue)
		}
	}
}

// TestExportNoSanitiserBait checks the output against what GitHub's SVG
// sanitiser strips (D25, D26, D27). Every one of these would look right in a
// browser and wrong in the README the diagram was made for, which is why the
// check is on the bytes rather than on the source.
func TestExportNoSanitiserBait(t *testing.T) {
	out := render(t, document(linked("customers"), linked("orders", "customers", "coupons")))

	for _, unwanted := range []string{"class=", "style=", "<style", "dominant-baseline", "<marker", "url(#"} {
		if strings.Contains(out, unwanted) {
			t.Errorf("the output contains %q, which the sanitiser strips or which needs a marker:\n%s", unwanted, out)
		}
	}
}

// TestExportBackgroundIsFirstAndOpaque pins the answer to a transparent diagram
// on a dark-mode README (D24): the first element inside <svg> is an opaque rect
// covering the whole viewBox. A theme-aware file would need a <style> block,
// which is exactly what the sanitiser removes.
func TestExportBackgroundIsFirstAndOpaque(t *testing.T) {
	out := render(t, document(linked("customers")))
	lines := strings.Split(out, "\n")

	svg := ""
	background := ""
	for i, line := range lines {
		if strings.HasPrefix(line, "<svg ") {
			svg, background = line, lines[i+1]
			break
		}
	}
	if svg == "" {
		t.Fatalf("no root element in\n%s", out)
	}

	size := svg[strings.Index(svg, `viewBox="0 0 `)+len(`viewBox="0 0 `):]
	size = size[:strings.Index(size, `"`)]
	width, height, _ := strings.Cut(size, " ")

	want := "\t<rect x=\"0\" y=\"0\" width=\"" + width + "\" height=\"" + height + "\" fill=\"" + colourPage + "\"/>"
	if background != want {
		t.Errorf("the first element is\n%s\nwant the opaque background\n%s", background, want)
	}
}

func TestExportEveryElementOnItsOwnLine(t *testing.T) {
	out := render(t, document(linked("customers"), linked("orders", "customers")))

	lines := strings.Split(strings.TrimSuffix(out, "\n"), "\n")
	if last := lines[len(lines)-1]; last != "</svg>" {
		t.Errorf("the last line is %q, want the root element's closing tag", last)
	}

	for i, line := range lines[:len(lines)-1] {
		// One OPENING tag per line. A <text> element carries its content and
		// its closing tag on the same line, which is the point: the content is
		// document text, and putting it on a line of its own would make the
		// file's whitespace part of the drawing.
		if opened := strings.Count(line, "<") - strings.Count(line, "</"); opened != 1 {
			t.Errorf("line %d opens %d element(s), want exactly one:\n%s", i+1, opened, line)
		}
	}
}

// errWriter fails every write, standing in for a full disk or a closed pipe.
type errWriter struct{ err error }

func (w errWriter) Write([]byte) (int, error) { return 0, w.err }

func TestExportWriteError(t *testing.T) {
	boom := errors.New("boom")
	err := Export(errWriter{err: boom}, document(linked("customers"), linked("orders", "customers")))

	if err == nil {
		t.Fatal("Export to a failing writer returned no error")
	}
	if !errors.Is(err, boom) {
		t.Errorf("Export error = %v, want it to wrap %v", err, boom)
	}
	if got, want := exitcode.Of(err), exitcode.OutputFailed; got != want {
		t.Errorf("exitcode.Of(err) = %d, want %d", got, want)
	}
}
