-- Source DDL for the broad importer fixture.
--
-- It is loaded into a throwaway PostgreSQL cluster by generate.sh; the dump of
-- the result is what the tests read. Everything here must import with ZERO
-- warnings, so that edge.sql is the only source of expected warning output.

CREATE TYPE order_status AS ENUM ('pending', 'paid', 'shipped', 'cancelled');

CREATE TABLE customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email character varying(255) NOT NULL UNIQUE,
    display_name character varying,
    note text,
    referrer_id bigint REFERENCES customers (id) ON DELETE SET NULL,
    nicknames character varying(30)[],
    tags text[],
    profile jsonb DEFAULT '{}'::jsonb NOT NULL,
    external_id uuid DEFAULT gen_random_uuid() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    born_on date,
    balance numeric(10,2) DEFAULT 0 NOT NULL,
    registered_at timestamp(3) without time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE customers IS '顧客
オンラインショップの利用者。退会しても行は残す。';
COMMENT ON COLUMN customers.email IS 'メールアドレス';
COMMENT ON COLUMN customers.balance IS '残高';

CREATE TABLE products (
    id serial PRIMARY KEY,
    sku character varying(32) NOT NULL,
    name text NOT NULL,
    price numeric(10,2) NOT NULL,
    weight double precision,
    released_on date
);

CREATE UNIQUE INDEX products_sku_key ON products (sku);
COMMENT ON TABLE products IS '商品';

CREATE TABLE orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL REFERENCES customers (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    status order_status DEFAULT 'pending'::order_status NOT NULL,
    placed_at timestamp with time zone DEFAULT now() NOT NULL,
    shipped_at timestamp with time zone,
    total numeric(10,2) NOT NULL
);

CREATE INDEX orders_customer_id_idx ON orders (customer_id);
CREATE INDEX orders_status_placed_at_idx ON orders (status, placed_at);
COMMENT ON TABLE orders IS '注文';
COMMENT ON COLUMN orders.status IS '注文状態';

CREATE TABLE order_lines (
    order_id bigint NOT NULL,
    line_no integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer DEFAULT 1 NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    PRIMARY KEY (order_id, line_no),
    FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products (id)
);

COMMENT ON TABLE order_lines IS '注文明細';

CREATE TABLE shipments (
    order_id bigint NOT NULL,
    line_no integer NOT NULL,
    carrier character varying(64) NOT NULL,
    tracking_no character varying(64),
    shipped_on date NOT NULL,
    CONSTRAINT shipments_pkey PRIMARY KEY (order_id, line_no),
    CONSTRAINT shipments_line_fkey FOREIGN KEY (order_id, line_no)
        REFERENCES order_lines (order_id, line_no) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT shipments_carrier_tracking_key UNIQUE (carrier, tracking_no)
);

COMMENT ON TABLE shipments IS '配送';
