package ddl

import (
	"errors"
	"io"
	"strings"
	"testing"
	"unicode/utf8"

	"github.com/shutx-net/jumping-json-flush/internal/exitcode"
	"github.com/shutx-net/jumping-json-flush/internal/model"
)

func TestOutputShape(t *testing.T) {
	const header = "-- Generated by jjf from a database design document.\n" +
		"-- The JSON is the source of truth: edit it and export again, never this file.\n"

	for _, name := range pgFixtures {
		t.Run(name, func(t *testing.T) {
			src := render(t, loadDoc(t, name))

			if !utf8.ValidString(src) {
				t.Fatal("the output is not valid UTF-8")
			}
			if !strings.HasPrefix(src, header) {
				t.Errorf("the output does not open with the two comment lines:\n%.160s", src)
			}
			if !strings.HasSuffix(src, ";\n") {
				t.Errorf("the output does not end with a statement terminator and one newline: %q", src[max(0, len(src)-20):])
			}
		})
	}
}

// TestStatementPhasesAreInOrder is the one property the four fixed phases are
// entirely about, so it is asserted here rather than left to a golden diff: no
// index and no foreign key may be written before the last table exists, which
// is what removes every ordering dependency between tables.
func TestStatementPhasesAreInOrder(t *testing.T) {
	for _, name := range pgFixtures {
		t.Run(name, func(t *testing.T) {
			src := render(t, loadDoc(t, name))

			at := -1
			for _, section := range []string{"\n-- Tables\n", "\n-- Indexes\n", "\n-- Foreign keys\n", "\n-- Comments\n"} {
				i := strings.Index(src, section)
				if i < 0 {
					continue // an absent section is the point of the guards
				}
				if i <= at {
					t.Errorf("%q appears at %d, not after the section before it at %d", section, i, at)
				}
				at = i
			}

			lastTable := strings.LastIndex(src, "CREATE TABLE ")
			for _, later := range []string{"CREATE INDEX ", "CREATE UNIQUE INDEX ", "ALTER TABLE ", "COMMENT ON "} {
				if i := strings.Index(src, later); i >= 0 && i < lastTable {
					t.Errorf("%q appears at %d, before the last CREATE TABLE at %d", later, i, lastTable)
				}
			}
		})
	}
}

// TestEmptySectionsDisappear holds the guards to their reason for existing: a
// document with no index, no foreign key and no comment worth writing produces
// a complete script with no dangling section comment and no dangling blank line.
func TestEmptySectionsDisappear(t *testing.T) {
	src := render(t, loadDoc(t, "minimal.json"))

	for _, absent := range []string{"-- Indexes", "-- Foreign keys", "-- Comments"} {
		if strings.Contains(src, absent) {
			t.Errorf("the minimal output carries the section %q:\n%s", absent, src)
		}
	}
	if strings.Contains(src, "\n\n\n") {
		t.Errorf("the minimal output has two consecutive blank lines:\n%q", src)
	}
}

// TestEdgeFixtureCoversItsCases names, one by one, the awkward cases the edge
// golden is supposed to show, so that a regression reports which case broke
// rather than dumping a diff of the whole file.
func TestEdgeFixtureCoversItsCases(t *testing.T) {
	src := render(t, loadDoc(t, "edge.json"))

	tests := []struct {
		name string
		want string
	}{
		{"a table named after a reserved word, quoted", `CREATE TABLE "order" (`},
		{"a column named after a reserved word, quoted", `    "user" BIGINT NOT NULL,`},
		{"an identity column", `"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL`},
		{"a user-defined type, never quoted", `"status" ORDER_STATUS DEFAULT 'pending'::order_status NOT NULL`},
		{"a precision and a scale", `"total" NUMERIC(10,2)`},
		{"a precision alone", `"rate" NUMERIC(8),`},
		{"the infix time precision PostgreSQL insists on", `"placed_at" TIMESTAMP(3) WITH TIME ZONE`},
		{"the short spelling without a precision", `"shipped_at" TIMESTAMPTZ,`},
		{"a length a known type cannot take, dropped", `"flags" INTEGER,`},
		{"a default carrying a cast", `"payload" JSONB DEFAULT '{}'::jsonb NOT NULL`},
		{"a default carrying a doubled quote, copied verbatim", `"label" TEXT DEFAULT 'it''s'::text NOT NULL`},
		{"a bare array element type", `"tags" TEXT[],`},
		{"an array whose element carries a length", `"aliases" VARCHAR(32)[],`},
		{"an unknown type keeping its parameter", `"score" FLOAT(24),`},
		{"an unnamed primary key", "    PRIMARY KEY (\"id\")"},
		{"an unnamed unique key", "    UNIQUE (\"user\", \"placed_at\")"},
		{"a named primary key", `    CONSTRAINT "pk_user" PRIMARY KEY ("id"),`},
		{"a named unique key", `    CONSTRAINT "uq_user_email" UNIQUE ("email")`},
		{"a table with no key, no index and no foreign key", "CREATE TABLE \"audit\" (\n    \"at\" TIMESTAMPTZ NOT NULL,\n    \"who\" TEXT NOT NULL\n);"},
		{"a non-unique index", `CREATE INDEX "ix_order_status" ON "order" ("status");`},
		{"a unique index", `CREATE UNIQUE INDEX "ix_categories_name" ON "categories" ("name");`},
		{
			"an unnamed foreign key, and the first half of a cycle",
			`ALTER TABLE "order" ADD FOREIGN KEY ("user") REFERENCES "user" ("id") ON UPDATE CASCADE ON DELETE RESTRICT;`,
		},
		{
			"the second half of the cycle, needing no ordering between the two tables",
			`ALTER TABLE "user" ADD CONSTRAINT "fk_user_home_order" FOREIGN KEY ("home_order_id") REFERENCES "order" ("id") ON DELETE SET NULL;`,
		},
		{
			"a self-referencing foreign key, and the two remaining actions",
			`ALTER TABLE "categories" ADD CONSTRAINT "fk_categories_parent" FOREIGN KEY ("parent_id") REFERENCES "categories" ("id") ON UPDATE NO ACTION ON DELETE SET DEFAULT;`,
		},
		{"a logical name and a description joined by a real newline", "COMMENT ON TABLE \"order\" IS '受注\nA table named after a reserved word."},
		{"an apostrophe inside a literal, doubled", `COMMENT ON COLUMN "order"."label" IS 'ラベル''s';`},
		{"an apostrophe inside a description, doubled", "it''s here on purpose"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if !strings.Contains(src, tt.want) {
				t.Errorf("the rendered edge fixture does not contain\n\t%s\ngot:\n%s", tt.want, src)
			}
		})
	}

	// A column whose logical name is just its physical name and which has no
	// description gets no comment: that is the state the importer leaves for an
	// object the dump carried none for.
	if strings.Contains(src, `COMMENT ON COLUMN "order"."note"`) {
		t.Errorf("the output comments a column that says nothing about itself:\n%s", src)
	}
}

// ---------------------------------------------------------------------------
// Refusals and write failures
// ---------------------------------------------------------------------------

// countingWriter records how much reached it, so that "all or nothing" can be
// asserted as the zero it is.
type countingWriter struct{ n int }

func (w *countingWriter) Write(p []byte) (int, error) { w.n += len(p); return len(p), nil }

func TestExportRefusesBeforeWriting(t *testing.T) {
	var w countingWriter

	err := Export(&w, loadDoc(t, "refused.json"))
	var re *RefusedError
	if !errors.As(err, &re) {
		t.Fatalf("Export returned %v, want a *RefusedError", err)
	}
	if w.n != 0 {
		t.Errorf("%d byte(s) were written for a refused document, want none", w.n)
	}
	if got := exitcode.Of(err); got != exitcode.InvalidInput {
		t.Errorf("exit code = %d, want %d (the document is what is wrong, not the writing)", got, exitcode.InvalidInput)
	}
}

// TestExportRefusesADocumentWithNoDialect covers the guard Export keeps for
// itself. Accept has already refused by the time the dialect is looked up, so
// this asserts the outcome a caller sees rather than which of the two guards
// produced it.
func TestExportRefusesADocumentWithNoDialect(t *testing.T) {
	var w countingWriter
	doc := loadDoc(t, "minimal.json")
	doc.Database.DBMS = model.DBMSSQLite

	err := Export(&w, doc)
	if err == nil {
		t.Fatal("Export rendered a SQLite document")
	}
	if w.n != 0 {
		t.Errorf("%d byte(s) were written, want none", w.n)
	}
}

// failingWriter fails every write, which is how the sticky-error handling of
// the bufio.Writer is reached at all.
type failingWriter struct{}

var errWriteFailed = errors.New("no space left on device")

func (failingWriter) Write([]byte) (int, error) { return 0, errWriteFailed }

func TestWriteErrorSurfaces(t *testing.T) {
	err := Export(failingWriter{}, loadDoc(t, "full.json"))
	if !errors.Is(err, errWriteFailed) {
		t.Fatalf("Export returned %v, want the write error", err)
	}
	if got := exitcode.Of(err); got != exitcode.OutputFailed {
		t.Errorf("exit code = %d, want %d (the environment stopped the write)", got, exitcode.OutputFailed)
	}
}

// Interface satisfaction, so that a signature change is a compile error here
// rather than at the call site in cmd/jjf.
var _ func(io.Writer, *model.Document) error = Export
