package ddl

import (
	"bufio"
	"fmt"
	"io"
	"strings"
	"unicode/utf8"

	"github.com/shutx-net/jumping-json-flush/internal/check"
	"github.com/shutx-net/jumping-json-flush/internal/model"
)

// ---------------------------------------------------------------------------
// The MySQL dialect
// ---------------------------------------------------------------------------

// Everything MySQL alone knows lives in this file, arranged the way postgres.go
// is and for the reason its header gives: one file per dialect, so that a
// change to one dialect touches one file and a reviewer reads one dialect at a
// time. The my prefix carries the same claim the pg prefix does - a delimiter,
// a type table and a precondition are facts about a target and not about SQL.
//
// design/ddl-export.md's MySQL table is the record this file implements, and
// the comments below cite it by row: M1 for the three phases, M2 for the
// backticks, M3 for AUTO_INCREMENT, M4 for the folded comments, M5 for the
// inverted namespaces, M6 for the doubled backslash, M7 for the parameters,
// M8 for what the type name alone decides, M9 for the "#" in a default, M10
// for the lengths and the one character MySQL will not take, M11 for what the
// type and the grammar decide about a default, and M12 for a foreign key's
// column order. A row and its function must move together; the numbers are
// cited so that they can be.

// ---------------------------------------------------------------------------
// Phases
// ---------------------------------------------------------------------------

// myWriteScript emits the whole script in three fixed phases: every
// CREATE TABLE, then every CREATE INDEX, then every foreign key as an
// ALTER TABLE.
//
// Three rather than PostgreSQL's four, and the missing one is not a
// simplification: MySQL has no COMMENT ON statement at all, so the fourth phase
// has nowhere to go and the two fields it carries ride on the definitions
// themselves - COMMENT on the column, COMMENT= on the table. That is M4, and
// pgHasComments' own comment says the same thing from the other side.
// Restating a column's whole definition in an ALTER TABLE ... MODIFY COLUMN was
// the alternative, and it would write one authored fact into the script twice.
//
// Everything else about choice 1 survives. Nothing in phase 1 refers to another
// table, so mutual references and self references still need no ordering and no
// cycle handling. Phase 2 still precedes phase 3, because MySQL accepts a plain
// UNIQUE INDEX as a foreign key target exactly as PostgreSQL does, so
// indexes[].unique is a legitimate source of the uniqueness a foreign key
// requires and has to exist first.
//
// The two header lines are byte for byte the ones pgWriteScript writes, and a
// test holds the two writers to agreeing. They are emitted per dialect rather
// than in Export because a dialect whose comment syntax differed would have to
// write them differently.
func myWriteScript(w *bufio.Writer, doc *model.Document) {
	io.WriteString(w, "-- Generated by jjf from a database design document.\n")
	io.WriteString(w, "-- The JSON is the source of truth: edit it and export again, never this file.\n")

	// The schema requires at least one table with at least one column, so this
	// section is never empty and needs no guard. The two below do.
	io.WriteString(w, "\n-- Tables\n\n")
	for i := range doc.Tables {
		if i > 0 {
			io.WriteString(w, "\n")
		}
		myWriteCreateTable(w, &doc.Tables[i])
	}

	if hasIndexes(doc) {
		io.WriteString(w, "\n-- Indexes\n\n")
		myWriteIndexes(w, doc)
	}
	if hasForeignKeys(doc) {
		io.WriteString(w, "\n-- Foreign keys\n\n")
		myWriteForeignKeys(w, doc)
	}
}

// ---------------------------------------------------------------------------
// Phase 1: tables
// ---------------------------------------------------------------------------

// myWriteCreateTable emits one table: every column in document order, then the
// primary key, then the unique keys, then the table's own comment after the
// closing parenthesis.
//
// Foreign keys are never inline, not even a self-reference, which is what makes
// phase 1 free of any dependency between tables. Indexes are not inline either,
// although mysqldump writes them as KEY clauses: keeping them in phase 2 is
// choice 2's rule, and the delta between the two writers stays the things that
// genuinely differ. What the round trip reads back from an inline KEY clause is
// the importer's problem and costs nothing, because the document is the same
// either way.
func myWriteCreateTable(w *bufio.Writer, t *model.Table) {
	fmt.Fprintf(w, "CREATE TABLE %s (\n", myQuoteIdent(t.Name))

	items := make([]string, 0, len(t.Columns)+1+len(t.UniqueKeys))
	for i := range t.Columns {
		items = append(items, myColumnItem(&t.Columns[i]))
	}
	if pk := t.PrimaryKey; pk != nil {
		items = append(items, constraintPrefix(myQuoteIdent, pk.Name)+"PRIMARY KEY ("+quotedList(myQuoteIdent, pk.Columns)+")")
	}
	for _, uk := range t.UniqueKeys {
		items = append(items, constraintPrefix(myQuoteIdent, uk.Name)+"UNIQUE ("+quotedList(myQuoteIdent, uk.Columns)+")")
	}

	for i, item := range items {
		io.WriteString(w, indent)
		io.WriteString(w, item)
		if i < len(items)-1 {
			io.WriteString(w, ",")
		}
		io.WriteString(w, "\n")
	}
	io.WriteString(w, ")")
	if text, ok := commentText(t.Name, t.LogicalName, t.Description); ok {
		io.WriteString(w, " COMMENT=")
		io.WriteString(w, myQuoteLiteral(text))
	}
	io.WriteString(w, ";\n")
}

// myColumnItem renders one column definition.
//
// The order is name, type, NOT NULL, DEFAULT, AUTO_INCREMENT, COMMENT, which is
// not pgColumnItem's order and is deliberately mysqldump's. The same argument
// the four-space indent rests on applies to the order of the words inside the
// line: a generated script and a dump of the database it created should read
// alike, and MySQL's column_definition grammar is less forgiving than
// PostgreSQL's about where AUTO_INCREMENT may sit, so matching the dump removes
// the question rather than answering it. Symmetry with the other writer would
// have been the alternative and is worth less than agreement with the dump this
// output is compared against twice in every round trip.
//
// NOT NULL is emitted only when the document says the column is not nullable,
// for the reason pgColumnItem gives: NULL is SQL's own default and stating it
// adds nothing.
//
// The default is copied out verbatim, with no quoting and no normalisation: the
// field is defined as SQL expression text and internal/check has already
// refused an empty one or one that does not read as an expression. A column
// carrying both a default and autoIncrement never reaches here, because myCheck
// reports it and Accept refuses the document.
func myColumnItem(c *model.Column) string {
	var b strings.Builder
	b.WriteString(myQuoteIdent(c.Name))
	b.WriteString(" ")
	b.WriteString(myRenderType(c))
	if !c.Nullable {
		b.WriteString(" NOT NULL")
	}
	if c.Default != nil {
		b.WriteString(" DEFAULT ")
		b.WriteString(*c.Default)
	}
	if c.AutoIncrement {
		b.WriteString(" AUTO_INCREMENT")
	}
	// M4: the column half of the comment fold. commentText is the shared
	// composition, so the first line is the logical name and the rest is the
	// description here exactly as it is in a COMMENT ON - which is what lets
	// the MySQL importer split an inline comment where the PostgreSQL one
	// splits a COMMENT ON.
	if text, ok := commentText(c.Name, c.LogicalName, c.Description); ok {
		b.WriteString(" COMMENT ")
		b.WriteString(myQuoteLiteral(text))
	}
	return b.String()
}

// ---------------------------------------------------------------------------
// Phase 2: indexes
// ---------------------------------------------------------------------------

// myWriteIndexes emits one statement per index, tables in document order and
// each table's indexes in document order.
func myWriteIndexes(w *bufio.Writer, doc *model.Document) {
	for i := range doc.Tables {
		t := &doc.Tables[i]
		for _, ix := range t.Indexes {
			unique := ""
			if ix.Unique {
				unique = "UNIQUE "
			}
			fmt.Fprintf(w, "CREATE %sINDEX %s ON %s (%s);\n",
				unique, myQuoteIdent(ix.Name), myQuoteIdent(t.Name), quotedList(myQuoteIdent, ix.Columns))
		}
	}
}

// ---------------------------------------------------------------------------
// Phase 3: foreign keys
// ---------------------------------------------------------------------------

// myWriteForeignKeys emits one ALTER TABLE per foreign key.
//
// The referential actions are written as the document spells them, and all five
// are legal MySQL text. Only four of them do anything: MySQL 8 accepts
// SET DEFAULT, records it and dumps it back, but InnoDB never performs the
// action and answers the delete it was supposed to handle with a foreign key
// error instead. That is drift rather than a refusal - the script is accepted,
// the document survives a round trip unchanged, and refusing it would refuse a
// document the importer can produce - and design/ddl-export.md's note under the
// MySQL table says so.
//
// ON UPDATE precedes ON DELETE, matching the field order in model.ForeignKey
// and the property order in the schema. Unlike PostgreSQL, MySQL keeps an
// explicit NO ACTION out of what it stores, so a document that states it does
// not get it back from a round trip; that is expected rather than a bug, in
// exactly the way pgWriteForeignKeys describes for its own dump tool.
func myWriteForeignKeys(w *bufio.Writer, doc *model.Document) {
	for i := range doc.Tables {
		t := &doc.Tables[i]
		for _, fk := range t.ForeignKeys {
			fmt.Fprintf(w, "ALTER TABLE %s ADD %sFOREIGN KEY (%s) REFERENCES %s (%s)",
				myQuoteIdent(t.Name), constraintPrefix(myQuoteIdent, fk.Name), quotedList(myQuoteIdent, fk.Columns),
				myQuoteIdent(fk.References.Table), quotedList(myQuoteIdent, fk.References.Columns))
			if fk.OnUpdate != "" {
				fmt.Fprintf(w, " ON UPDATE %s", fk.OnUpdate)
			}
			if fk.OnDelete != "" {
				fmt.Fprintf(w, " ON DELETE %s", fk.OnDelete)
			}
			io.WriteString(w, ";\n")
		}
	}
}

// ---------------------------------------------------------------------------
// Quoting
// ---------------------------------------------------------------------------

// myQuoteIdent writes s as a MySQL delimited identifier, always emitting the
// surrounding backticks.
//
// M2, which is choice 4's argument with a different delimiter. There is no
// exception for a name that would be legal bare: the schema's $defs/identifier
// is ^[A-Za-z_][A-Za-z0-9_]*$, so quoting is always safe, it removes the whole
// class of reserved-word collisions without a keyword list to maintain, and it
// preserves case on a server whose lower_case_table_names may be folding it.
//
// Not the double quote PostgreSQL uses: MySQL reads "order" as a string
// literal unless ANSI_QUOTES is in sql_mode, and putting it there would mean
// emitting a SET, which M6 rules out for the whole script.
//
// Doubling an embedded backtick is defensive rather than reachable - that
// pattern forbids one - and is here so that a future caller passing freer text
// cannot open a hole. The unit tests are the only place it is exercised, which
// is what text.go already says about pgQuoteIdent.
func myQuoteIdent(s string) string { return "`" + doubled(s, '`') + "`" }

// myQuoteLiteral writes s as a MySQL string literal, doubling the apostrophe
// and the backslash in one pass.
//
// M6, and the one place the two dialects' escaping genuinely differs rather
// than differing in a delimiter. MySQL treats a backslash inside a string as an
// escape character unless NO_BACKSLASH_ESCAPES is in sql_mode, which is not the
// default: 'C:\tmp' reaches the database as C: followed by a tab. This escaping
// is reachable, because it carries logicalName and description, which are free
// text in any language - a Windows path in a description is the ordinary way to
// meet it - and the failure is silent, since the script runs and stores the
// wrong text.
//
// One loop rather than two calls to doubled, for the reason doubled's own
// comment gives: chained replacements escape their own output, so doubling the
// backslash after the apostrophe would double the backslashes the first pass
// had just produced. Bytes of a multibyte UTF-8 sequence are all >= 0x80 and
// fall through untouched, so Japanese text survives unchanged.
//
// A newline is left alone, and has to be: a table comment is the logical name
// and the description joined by one, and the importer cuts it back apart at
// exactly that byte.
//
// The alternative was SET sql_mode='NO_BACKSLASH_ESCAPES' at the top of the
// script, so that PostgreSQL's rule would apply to both dialects.
// internal/export/ddl/text.go already refuses the equivalent for PostgreSQL -
// one setting invites character_set_client and time_zone after it - and a
// script that changes a session variable is a script whose effect depends on
// where it was run from.
func myQuoteLiteral(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 2)
	b.WriteByte('\'')
	for i := 0; i < len(s); i++ {
		switch c := s[i]; c {
		case '\'', '\\':
			b.WriteByte(c)
			b.WriteByte(c)
		default:
			b.WriteByte(c)
		}
	}
	b.WriteByte('\'')
	return b.String()
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

// myTypeParamKind reports how the parameters of the type called name are
// written. name has already been upper-cased and stripped of any attribute
// suffix by myRenderType, so BIGINT UNSIGNED never reaches here and would be
// answered paramUnknown if it did.
//
// M7. It is a switch and not a package-level map, for the reason
// internal/importer/postgres/typemap.go's canonicalTypeName gives verbatim: a
// map literal at package scope is mutable state any caller could corrupt.
//
// The list is short on purpose. Choice 5 says jjf keeps no per-system type
// catalogue, so this answers one question only - which attribute the
// parentheses hold - and every name it does not list falls to paramUnknown,
// where the document's own parameters are reproduced as stated. FLOAT and
// DOUBLE are left out for exactly that reason: MySQL reads FLOAT(24) as a
// precision in bits and FLOAT(10,2) as a deprecated precision and scale, and
// reproducing what the document says is right for both.
func myTypeParamKind(name string) paramKind {
	switch name {
	// Character, binary and bit strings: the parameter is a length. TINYINT is
	// here rather than with the integers because tinyint(1) is how MySQL
	// stores a boolean, mysqldump still writes it, and
	// skills/db-design/references/types.md tells authors to write
	// "length": 1 for exactly that - so dropping it would make the workbook
	// and the DDL describe different columns.
	case "VARCHAR", "CHARACTER VARYING", "CHAR", "CHARACTER",
		"BINARY", "VARBINARY", "BIT", "TINYINT":
		return paramLength

	// Exact numerics: the parameters are a precision and a scale.
	case "DECIMAL", "DEC", "NUMERIC", "FIXED":
		return paramPrecisionScale

	// Date and time: the parameter counts fractional-second digits, and MySQL
	// spells every one of them as a single word, so there is no infix case
	// here at all. paramTimePrecisionInfix stays a PostgreSQL-only answer.
	case "DATETIME", "TIMESTAMP", "TIME":
		return paramTimePrecision

	// Types that take no parameter jjf can write. The integers are here
	// because a display width has been deprecated since MySQL 8.0.17 and
	// mysqldump no longer writes one, so emitting INT(11) would be emitting a
	// construct the server is removing. ENUM and SET are here because their
	// parenthesis holds a value list, which is not a number and which the
	// document has nowhere to keep - see M8, and myCheck's silence about it.
	case "INT", "INTEGER", "SMALLINT", "MEDIUMINT", "BIGINT",
		"BOOL", "BOOLEAN", "DATE", "YEAR",
		"TEXT", "TINYTEXT", "MEDIUMTEXT", "LONGTEXT",
		"BLOB", "TINYBLOB", "MEDIUMBLOB", "LONGBLOB",
		"JSON", "ENUM", "SET":
		return paramNone
	}
	return paramUnknown
}

// myTypeAttributes are the trailing words MySQL puts AFTER a type's
// parentheses, longest first so that the two-word form is recognised before its
// own second word is.
//
// They are the reason a MySQL type name can contain a space at all, and the
// schema's columnType pattern - ^[A-Za-z][A-Za-z0-9_ ]*$ - permits it, so
// "BIGINT UNSIGNED" is an ordinary value that a document imported from MySQL
// legitimately carries.
//
// A function returning a fresh slice rather than a package-level var, for the
// reason cmd/jjf/export.go's exportFormats gives: a package-level slice is
// mutable state any caller could corrupt. It is walked in order, never ranged
// over as a map.
func myTypeAttributes() []string {
	return []string{" UNSIGNED ZEROFILL", " UNSIGNED", " ZEROFILL"}
}

// myAttributeSuffix splits a trailing UNSIGNED, ZEROFILL or UNSIGNED ZEROFILL
// off name, returning what is left and the suffix as the document spelled it.
//
// The suffix is returned rather than normalised because choice 5 passes the
// type name through as written; only the comparison folds case, and it folds
// ASCII alone, for the reason typemap.go's upperASCII gives.
//
// A type whose whole name is an attribute keeps it: the remainder would be
// empty, which is no type at all. That is the guard pgRenderType keeps for a
// type actually called ARRAY, and it is here for the same reason.
func myAttributeSuffix(name string) (base, attr string) {
	upper := upperASCII(name)
	for _, suffix := range myTypeAttributes() {
		if len(name) > len(suffix) && strings.HasSuffix(upper, suffix) {
			return name[:len(name)-len(suffix)], name[len(name)-len(suffix):]
		}
	}
	return name, ""
}

// myTypeBase is the type name with any UNSIGNED or ZEROFILL split off it, which
// is what the two rules decided by the type name alone have to compare.
//
// A thin name over myAttributeSuffix so that a rule reads as the question it is
// asking. M7 put the split there for the opposite purpose - to render the
// parameters before the attribute - and the two callers want the same first
// half for different second halves.
func myTypeBase(name string) string {
	base, _ := myAttributeSuffix(name)
	return base
}

// myRenderType folds a column's declared attributes back into its type, which
// is the reverse of what the importer took apart.
//
// M7. The parameters go BEFORE the attribute - DECIMAL(10,2) UNSIGNED, not
// DECIMAL UNSIGNED(10,2), which MySQL answers with a syntax error - so the
// attribute is split off, the parameters are rendered against what remains, and
// the attribute is put back. This is structurally the same problem
// pgInfixTimePrecision solves, approached from the other end: a parameter that
// cannot simply be appended. Saying so here is what stops a later reader taking
// one of the two for a mistake.
//
// Leaving BIGINT UNSIGNED to paramUnknown was the alternative, and it would
// reproduce whatever the document declared - which is right for a type jjf does
// not know and wrong for the one case that matters, DECIMAL UNSIGNED, where it
// would put the parenthesis after the attribute.
//
// The type NAME is passed through exactly as the document writes it and is
// never rewritten or quoted, for the reasons pgRenderType gives at length. A
// parameter a known type cannot take is dropped without a word, the same way
// and for the same reason: Export writes into an io.Writer and has no channel
// to warn on, so the documentation says it instead.
func myRenderType(c *model.Column) string {
	base, attr := myAttributeSuffix(c.Type)
	return base + typeParams(myTypeParamKind(upperASCII(base)), c) + attr
}

// myLengthlessTypes are the type names MySQL gives no default length to, so
// that a column declaring one without a length cannot be written at all.
//
// Two names and not a table of every type whose parameter is mandatory. CHAR,
// BINARY, BIT and DECIMAL all have a server default and are absent on purpose;
// ENUM and SET are absent for the opposite reason, that the document can never
// supply what they need. See M8 for why those three cases are not one case.
func myLengthlessTypes() []string { return []string{"VARCHAR", "VARBINARY"} }

// myKeyUnusableType reports why a column of the type called name cannot be part
// of a key, and whether it can be at all. name has already been upper-cased.
//
// The returned clause finishes the finding's sentence, because the two families
// fail differently and a single wording would be wrong for one of them: MySQL
// answers a TEXT or BLOB column in a key with ERROR 1170 and wants a prefix
// length, and a JSON column with ERROR 3152, which no prefix length would
// satisfy.
func myKeyUnusableType(name string) (clause string, unusable bool) {
	switch name {
	case "TEXT", "TINYTEXT", "MEDIUMTEXT", "LONGTEXT",
		"BLOB", "TINYBLOB", "MEDIUMBLOB", "LONGBLOB":
		return "MySQL refuses such a column in a key without a prefix length, which the document has nowhere to put", true
	case "JSON":
		return "MySQL indexes such a column only through a generated column on a JSON path, which the document has nowhere to express", true
	}
	return "", false
}

// ---------------------------------------------------------------------------
// Preconditions
// ---------------------------------------------------------------------------

// myIdentifierLimit is M10's first half: what MySQL does with a name longer
// than it takes.
//
// The measurement is in CHARACTERS rather than bytes, which is the one thing
// PostgreSQL's limit does not share: MySQL counts what it stores, and 64 is
// 64 characters whatever they encode to. The schema's identifier pattern is
// ASCII only, so no document jjf validate accepts can tell the two apart; they
// are kept apart anyway, because Check is total over a model that never met the
// schema.
//
// MySQL refuses rather than truncating - ERROR 1059 - so this is a loud failure
// prevented early rather than PostgreSQL's silent one prevented at all.
func myIdentifierLimit() identifierLimit {
	return identifierLimit{
		max:     64,
		unit:    "characters",
		measure: utf8.RuneCountInString,
		clause:  "MySQL refuses an identifier longer than 64 characters",
	}
}

// myNulClause is M10's third: why a comment carrying U+0000 is refused rather
// than written.
//
// The wall is a different one from PostgreSQL's. MySQL's own text types hold
// that byte quite happily; it is the mysql client that refuses to send a
// statement containing one unless it is run in binary mode, which is not how a
// generated script is applied. The refusal is therefore about the script rather
// than about the column, and the message says so.
const myNulClause = "the mysql client refuses to send a statement containing that character"

// myCommentLimits are M10's second half, the two lengths MySQL stores: 1024
// characters on a column and 2048 on a table, measured on 8.0, one more of
// either being ERROR 1629 and ERROR 1628.
//
// What makes them reachable from a document jjf validate accepts is M4 rather
// than either limit on its own: $defs/description allows 2000 characters and
// $defs/logicalName allows 255, and the generator joins them with a newline
// into ONE comment. A table comment of 2256 characters is therefore two fields
// each well inside the schema's own bounds.
func myCommentLimits() (column, table int) { return 1024, 2048 }

// myCommentFindings reports what MySQL refuses about the comments of one table,
// in document order: the table's own, then its columns'.
//
// At most one finding per object, the rule internal/check's checkColumnDefault
// follows. The length is checked before the character because a comment that is
// both too long and unsendable is one field to rewrite.
func myCommentFindings(t *model.Table) []check.Finding {
	columnMax, tableMax := myCommentLimits()

	var findings []check.Finding
	for _, o := range tableComments(t) {
		max, object := tableMax, "table"
		if o.column {
			max, object = columnMax, "column"
		}
		if n := utf8.RuneCountInString(o.text); n > max {
			findings = append(findings, check.Finding{
				Where: o.where,
				Message: fmt.Sprintf(
					"needs a COMMENT of %d characters, which is its logicalName and its description joined; MySQL stores at most %d characters on a %s",
					n, max, object),
			})
			continue
		}
		if f, bad := nulFinding(o, myNulClause); bad {
			findings = append(findings, f)
		}
	}
	return findings
}

// myAutoIncrementType reports whether MySQL will auto-increment a column of the
// type called name, which has already been upper-cased and had any UNSIGNED or
// ZEROFILL split off it.
//
// A list of what is ACCEPTED, for the reason pgIdentityType gives and with the
// same measurement behind it: MySQL has no user-defined types at all, so there
// is no name this list can wrongly refuse that the server would have accepted.
// It is not PostgreSQL's list with more entries - FLOAT, DOUBLE and BOOLEAN all
// auto-increment in MySQL and none of them can be a PostgreSQL identity column,
// while DECIMAL is refused by both. Every entry below was run against MySQL 8.0.
//
// The short spellings are here because MySQL accepts them and a hand-written
// document may use them: INT1 through INT8 and FLOAT4 / FLOAT8 are its own
// synonyms, and INT4 is not PostgreSQL's int4 arriving by accident. SERIAL is
// present although the importer never writes it - expandSerial takes it apart
// into BIGINT UNSIGNED - because a hand-written document may still say it and
// MySQL accepts SERIAL AUTO_INCREMENT.
func myAutoIncrementType(name string) bool {
	for _, t := range []string{
		"TINYINT", "INT1", "BOOL", "BOOLEAN",
		"SMALLINT", "INT2",
		"MEDIUMINT", "INT3", "MIDDLEINT",
		"INT", "INTEGER", "INT4",
		"BIGINT", "INT8", "SERIAL",
		"FLOAT", "FLOAT4",
		"DOUBLE", "DOUBLE PRECISION", "FLOAT8", "REAL",
	} {
		if name == t {
			return true
		}
	}
	return false
}

// myDefaultlessType reports whether MySQL refuses a plain default on a column
// of the type called name, which has already been upper-cased.
//
// The four families are the ones ERROR 1101 itself names - "BLOB, TEXT,
// GEOMETRY or JSON column can't have a default value" - and the list is written
// out rather than shared with myKeyUnusableType, which names two of them for a
// different rule: a spatial index over a geometry column is ordinary, so the
// two lists agree today by coincidence and not by construction. Each was run
// against MySQL 8.0.
func myDefaultlessType(name string) bool {
	for _, t := range []string{
		"TEXT", "TINYTEXT", "MEDIUMTEXT", "LONGTEXT",
		"BLOB", "TINYBLOB", "MEDIUMBLOB", "LONGBLOB",
		"JSON",
		"GEOMETRY", "POINT", "LINESTRING", "POLYGON",
		"MULTIPOINT", "MULTILINESTRING", "MULTIPOLYGON", "GEOMETRYCOLLECTION",
	} {
		if name == t {
			return true
		}
	}
	return false
}

// myParenthesisedDefault reports whether def is written as MySQL's
// parenthesised expression default rather than as a bare literal.
//
// The test is that the text STARTS with a parenthesis, and not that the first
// one closes at the end of it. The weaker test is deliberate: the stronger one
// needs to know where a string literal ends, MySQL's backslash escapes make
// that a second grammar to get right, and getting it wrong would refuse a
// legal document - which M5's row already names as the worse of the two
// mistakes. What the weaker test misses is DEFAULT ('a')+1, which MySQL answers
// with a syntax error of its own; what it must never do is refuse
// DEFAULT (_utf8mb4'a\')'), which is a value mysqldump writes.
func myParenthesisedDefault(def string) bool {
	return strings.HasPrefix(strings.TrimLeft(def, " \t\r\n"), "(")
}

// myBareDefaultWords are the bare words MySQL's unparenthesised DEFAULT does
// not admit, answering each with ERROR 1064.
//
// It is a list of what is REFUSED, and it is exactly a subtraction: internal/
// check's C8d already refuses every bare word outside its sixteen
// keywordConstants, so those sixteen are the only ones that can reach this
// rule, and these ten are the ones MySQL's grammar rejects. The six that
// survive are CURRENT_TIMESTAMP, LOCALTIME, LOCALTIMESTAMP, TRUE, FALSE and
// NULL. Written as the refusals rather than as the survivors so that a word
// this package has never heard of - a charset introducer, a function C8d reads
// as a call - passes untouched: a list of survivors would refuse it, and
// refusing a legal document is the mistake M5's row exists to name.
//
// Each was run against MySQL 8.0 on a DATETIME column, which is the most
// permissive one: TRUE and FALSE answer with ERROR 1067 there, a type error
// rather than a syntax error, and are legal on an INT column.
func myBareDefaultWords() []string {
	return []string{
		"CURRENT_DATE", "CURRENT_TIME",
		"CURRENT_USER", "SESSION_USER", "CURRENT_ROLE",
		"CURRENT_CATALOG", "CURRENT_SCHEMA", "USER",
		"SYSDATE", "SYSTIMESTAMP",
	}
}

// myLeadingWord returns the word an expression begins with, and the empty
// string when it begins with anything else - a quote, a digit, a sign or the
// parenthesis that makes the whole rule moot.
//
// The word bytes are MySQL's unquoted identifier characters. Nothing here folds
// case: the caller does that, with upperASCII, for the reason typemap.go gives.
func myLeadingWord(s string) string {
	i := 0
	for i < len(s) && (s[i] == ' ' || s[i] == '\t' || s[i] == '\r' || s[i] == '\n') {
		i++
	}
	if i == len(s) || !myWordStart(s[i]) {
		return ""
	}
	end := i
	for end < len(s) && myWordByte(s[end]) {
		end++
	}
	return s[i:end]
}

// myWordStart and myWordByte are MySQL's unquoted identifier characters. They
// carry the dialect prefix although the ASCII half of the answer is every
// system's, for the reason myNamedKey gives: an unprefixed name in this package
// means shared by both dialects, and only text.go and typemap.go hold those.
func myWordStart(b byte) bool {
	return b == '_' || b == '$' || (b >= 'A' && b <= 'Z') || (b >= 'a' && b <= 'z')
}

func myWordByte(b byte) bool { return myWordStart(b) || (b >= '0' && b <= '9') }

// myLeadsAKeyInOrder reports whether cols are the leading columns, IN ORDER, of
// this table's primary key, of one of its unique keys or of one of its indexes.
//
// Every one of the three may serve, unlike myLeadsAKey's question about
// AUTO_INCREMENT: M1 creates the indexes in phase 2 and adds the foreign keys
// in phase 3, so by the time the constraint is added every key the document
// declares exists.
//
// A leading PREFIX and not an equal list, because that is what InnoDB requires
// and what it was measured doing: a foreign key onto (a, b) of a table whose
// primary key is (a, b, c) is accepted. internal/check's C4 makes that case
// rare rather than impossible - it wants the referenced columns constrained
// unique as a SET, which (a, b) of a key on (a, b, c) is not - and the two
// checks are orthogonal, so a document that gets both wrong hears both.
func myLeadsAKeyInOrder(t *model.Table, cols []string) bool {
	prefix := func(key []string) bool {
		if len(key) < len(cols) {
			return false
		}
		for i, name := range cols {
			if key[i] != name {
				return false
			}
		}
		return true
	}
	if pk := t.PrimaryKey; pk != nil && prefix(pk.Columns) {
		return true
	}
	for _, uk := range t.UniqueKeys {
		if prefix(uk.Columns) {
			return true
		}
	}
	for _, ix := range t.Indexes {
		if prefix(ix.Columns) {
			return true
		}
	}
	return false
}

// myCheck reports the preconditions that are statements about MySQL rather than
// about the document, in document order.
//
// It returns only its own findings and never calls check.Document: Check owns
// that call and concatenates, which is what keeps the two groups
// un-interleaved.
//
// The list is not pgCheck's with a different database's name in the messages,
// and M5 is why: MySQL scopes foreign key names per SCHEMA and index and
// constraint names per TABLE, which is the exact inverse of PostgreSQL. Reusing
// pgCheck's walk on the theory that being stricter than the target is safe
// would refuse a legal MySQL document and pass an illegal one at the same time.
//
// Every rule below was run against a live MySQL 8.0 before it was written here.
// The messages describe the behaviour rather than quoting an error number,
// because a number is the one part of a server message that a release may
// renumber and a reader cannot act on.
func myCheck(doc *model.Document) []check.Finding {
	var findings []check.Finding

	// tables and constraints map a name in a schema-wide namespace to a
	// description of whatever claimed it first, so that a collision can say
	// what it collided with. Both maps are only ever LOOKED UP and assigned,
	// NEVER ranged over: ranging would make the order of the findings depend
	// on Go's map iteration and destroy the determinism the goldens and the
	// CLI output rest on. The order comes from the slice walks below and from
	// nowhere else.
	//
	// Two maps rather than pgCheck's one, because MySQL has two separate
	// schema-wide namespaces rather than one shared by four kinds of object: a
	// foreign key may take a name a table already has, and does.
	tables := make(map[string]bool, len(doc.Tables))
	constraints := make(map[string]string)
	// The two "reported" sets remember the names already reported, for the
	// reason internal/check's usedNames gives: three tables sharing a name is
	// one mistake to fix, not two findings. There are two of them for the same
	// reason there are two namespaces - a document may legally call a table
	// and a foreign key by one name, and one shared set would let a collision
	// in one namespace silence a collision in the other.
	tablesReported := make(map[string]bool)
	constraintsReported := make(map[string]bool)
	// byName finds a foreign key's referenced table for the order rule. Like
	// the maps above it is only ever LOOKED UP and assigned, NEVER ranged
	// over. The FIRST table of a name wins, which is the one CREATE TABLE the
	// script would have created before the collision M5 reports; a table with
	// no name at all is left out, so that a reference to nothing finds nothing
	// and internal/check's C2 keeps that case to itself.
	byName := make(map[string]*model.Table, len(doc.Tables))
	for i := range doc.Tables {
		if t := &doc.Tables[i]; t.Name != "" && byName[t.Name] == nil {
			byName[t.Name] = t
		}
	}

	for i := range doc.Tables {
		t := &doc.Tables[i]
		label := tableLabel(t.Name)

		// M10, before anything about what the names mean: a name MySQL will
		// not take, and a comment it will not store.
		findings = append(findings, identifierFindings(t, myIdentifierLimit())...)
		findings = append(findings, myCommentFindings(t)...)

		// M5, first half - a table name is schema-wide. internal/check
		// deliberately does not report duplicate table names, so without this
		// a document naming two tables "orders" would emit CREATE TABLE twice
		// and MySQL would reject the script. Index names are absent from this
		// namespace, which is where PostgreSQL's rule and MySQL's part
		// company: two MySQL tables may each carry an ix_created, and an index
		// may even take a name a table already has.
		if t.Name != "" {
			if tables[t.Name] && !tablesReported[t.Name] {
				tablesReported[t.Name] = true
				findings = append(findings, check.Finding{
					Where:   label,
					Message: fmt.Sprintf("is the second table this document calls %q; MySQL cannot create two tables of one name in a schema", t.Name),
				})
			}
			tables[t.Name] = true
		}

		findings = append(findings, myColumnFindings(t)...)
		findings = append(findings, myKeyFindings(t)...)

		// M5, second half. A foreign key name lives in a per-DATABASE
		// namespace in InnoDB, so two tables may not both carry an fk_parent -
		// which is the inverse of PostgreSQL, where pg_constraint is unique per
		// table and internal/export/ddl/precheck_test.go's
		// TestForeignKeyNamesMayRepeatAcrossTables pins that they may.
		//
		// A closure rather than the body of the loop below, because M12's
		// order rule has to run for every foreign key including the unnamed
		// ones this says nothing about.
		claimForeignKey := func(name string) {
			if name == "" {
				// The schema makes foreignKeys[].name optional and MySQL
				// invents one, so several unnamed foreign keys in one document
				// are ordinary rather than a collision.
				return
			}
			owner := "foreign key " + name + " on table " + t.Name
			prior, taken := constraints[name]
			if !taken {
				constraints[name] = owner
				return
			}
			if constraintsReported[name] {
				return
			}
			constraintsReported[name] = true
			findings = append(findings, check.Finding{
				Where:   label,
				Message: fmt.Sprintf("declares foreign key %q, a name already used by %s; InnoDB keeps foreign key names in one namespace per schema", name, prior),
			})
		}
		for k := range t.ForeignKeys {
			fk := &t.ForeignKeys[k]
			claimForeignKey(fk.Name)
			if f, bad := myForeignKeyOrderFinding(byName, label, fk); bad {
				findings = append(findings, f)
			}
		}
	}
	return findings
}

// myForeignKeyOrderFinding reports a foreign key whose referenced columns no
// key of the referenced table carries as its leading columns, in that order.
//
// This is the divergence internal/check cannot state and says so: its
// sameColumnSet compares the referenced columns as a SET, with the comment "a
// foreign key on (b, a) against a primary key on (a, b) is still the same
// target". That is exactly right for PostgreSQL, which was measured accepting
// it. InnoDB needs an index it can walk from the left and answers the same
// document with ERROR 1822, Missing index for constraint in the referenced
// table - which is M5's argument about namespaces applied to column order, and
// belongs here for the same reason M5 does. It is M12.
//
// Three things are skipped in silence, each because another check owns it and
// this one would have nothing to add: a foreign key with no referenced columns,
// one naming a table the document does not define (internal/check's C2), and
// one whose two column lists are of different lengths (C3).
func myForeignKeyOrderFinding(byName map[string]*model.Table, label string, fk *model.ForeignKey) (check.Finding, bool) {
	cols := fk.References.Columns
	target := byName[fk.References.Table]
	if len(cols) == 0 || target == nil || len(cols) != len(fk.Columns) {
		return check.Finding{}, false
	}
	if myLeadsAKeyInOrder(target, cols) {
		return check.Finding{}, false
	}
	return check.Finding{
		Where: label,
		Message: fmt.Sprintf(
			"declares %s referencing (%s) of table %q; MySQL needs an index on that table whose leading columns are those, in that order, and its primaryKey, uniqueKeys and indexes all begin differently",
			myNamedKey("foreign key", fk.Name), strings.Join(cols, ", "), fk.References.Table),
	}, true
}

// myColumnFindings reports what MySQL refuses about the columns of one table,
// in column order.
//
// At most one finding comes out per column, the rule internal/check's
// checkColumnDefault already follows: one authoring mistake, one finding. The
// order the five AUTO_INCREMENT rules are tried in is the order in which one
// explains the others - a second AUTO_INCREMENT column is the whole problem
// with that column, and telling its author that it also leads no key would be
// telling them to fix something they are about to delete. A type MySQL will
// not auto-increment comes next for the same reason, and before the two rules
// about a DEFAULT it may be keeping.
func myColumnFindings(t *model.Table) []check.Finding {
	var findings []check.Finding

	// auto is the first AUTO_INCREMENT column of the table, so that the second
	// one can name it. The document's order decides which is which, exactly as
	// it decides everything else this package reports.
	auto := ""
	for j := range t.Columns {
		c := &t.Columns[j]
		label := columnLabel(c.Name, t.Name)
		// said is the finding count this column started with, so that every
		// rule below can honour the one-finding-per-column rule against it
		// rather than against the rule immediately before it.
		said := len(findings)

		if c.AutoIncrement {
			// M3, all five rules. Each is a fact about MySQL: the first three
			// are refused outright by the server, the fourth is refused as an
			// invalid default, and the fifth is the silent one - MySQL accepts
			// a nullable AUTO_INCREMENT column and stores it NOT NULL, which
			// is C5's argument for a column outside the primary key and
			// PostgreSQL's identity rule in another grammar. The type rule is
			// a list of what is ACCEPTED, for the reason myAutoIncrementType
			// gives at length; it is not pgIdentityType's list, because the
			// two databases disagree about FLOAT, DOUBLE and BOOLEAN.
			switch {
			case auto != "":
				findings = append(findings, check.Finding{
					Where:   label,
					Message: fmt.Sprintf("is autoIncrement, and so is column %q on the same table; MySQL allows one AUTO_INCREMENT column per table", auto),
				})
			case !myAutoIncrementType(upperASCII(myTypeBase(c.Type))):
				findings = append(findings, check.Finding{
					Where:   label,
					Message: fmt.Sprintf("is autoIncrement and declares type %q; MySQL auto-increments only its integer and floating-point types", c.Type),
				})
			case c.Default != nil:
				findings = append(findings, check.Finding{
					Where:   label,
					Message: "is autoIncrement and also declares a default; MySQL refuses a default on an AUTO_INCREMENT column",
				})
			case c.Nullable:
				findings = append(findings, check.Finding{
					Where:   label,
					Message: "is autoIncrement and declared nullable; MySQL makes an AUTO_INCREMENT column NOT NULL, so the database would not match the document",
				})
			case !myLeadsAKey(t, c.Name):
				findings = append(findings, check.Finding{
					Where:   label,
					Message: "is autoIncrement and leads no key; MySQL needs it to be the first column of this table's primaryKey or of one of its uniqueKeys, and an entry in indexes cannot serve because the script creates it after the table",
				})
			}
			if auto == "" {
				auto = c.Name
			}
			if len(findings) > said {
				// One finding per column. The skip is conditional rather than
				// unconditional so that a column this block had nothing to say
				// about still reaches the check below: "at most one" is the
				// rule, not "the first branch that matches owns the column".
				continue
			}
		}

		// M8, first half. A bare VARCHAR is a syntax error rather than a
		// column of some default width, and mysqldump always writes the
		// length, so no document the importer produced can be in this state
		// and refusing costs the round trip nothing. Two type spellings and
		// not a table of every type whose parameter is mandatory: see
		// myLengthlessTypes.
		if c.Length == nil {
			name := upperASCII(c.Type)
			for _, lengthless := range myLengthlessTypes() {
				if name == lengthless {
					findings = append(findings, check.Finding{
						Where:   label,
						Message: fmt.Sprintf("declares type %q and no length; MySQL has no default length for it, so the column would be a syntax error rather than a column", c.Type),
					})
					break
				}
			}
		}
		if len(findings) > said {
			continue
		}

		// M11, first half - the type's own answer to a default, before
		// anything about what the default says: a column MySQL gives no
		// default to at all is one whose author is about to delete the field
		// rather than rewrite it. The parenthesis is the whole of the
		// exception and it is not a courtesy: DEFAULT ('x') on a TEXT column
		// is legal since 8.0.13 and is what mysqldump writes back, so refusing
		// every default on those families would break the round trip by
		// construction.
		if c.Default != nil && !myParenthesisedDefault(*c.Default) && myDefaultlessType(upperASCII(myTypeBase(c.Type))) {
			findings = append(findings, check.Finding{
				Where:   label,
				Message: fmt.Sprintf("declares type %q and the default %s; MySQL gives a BLOB, TEXT, GEOMETRY or JSON column no default unless it is written as a parenthesised expression, as in (%s)", c.Type, *c.Default, *c.Default),
			})
		}
		if len(findings) > said {
			continue
		}

		// M11, second half - the grammar's answer to a bare word.
		// internal/check's C8d has already let sixteen of them through as
		// SQL's niladic constants, and MySQL's unparenthesised DEFAULT takes
		// six: the rest are ERROR 1064, and the parenthesised form is what
		// MySQL wants instead.
		if c.Default != nil && !myParenthesisedDefault(*c.Default) {
			word := upperASCII(myLeadingWord(*c.Default))
			for _, refused := range myBareDefaultWords() {
				if word != refused {
					continue
				}
				findings = append(findings, check.Finding{
					Where:   label,
					Message: fmt.Sprintf("declares the default %q, which MySQL takes only in parentheses; write it as (%s), because an unparenthesised DEFAULT admits a literal, CURRENT_TIMESTAMP, LOCALTIME, LOCALTIMESTAMP and NOW() and nothing else", *c.Default, *c.Default),
				})
				break
			}
		}
		if len(findings) > said {
			continue
		}

		// M9, the MySQL half of internal/check's C8b. That check refuses "--",
		// "/*" and ";" in a default because all three mean the same thing in
		// every system the schema names; "#" cannot join them, because it is a
		// comment in MySQL and MariaDB alone and an operator in PostgreSQL.
		// Refusing it there would refuse a legal document, which is M5's
		// mistake in another grammar.
		//
		// What it prevents is the same failure C8b prevents: the generator
		// writes a column definition on one line, so a comment opened inside
		// the default runs to the end of it and takes whatever was written
		// after - the comma before the next column, or the COMMENT clause
		// carrying this column's own description.
		if myHashComment(c.Default) {
			findings = append(findings, check.Finding{
				Where:   label,
				Message: fmt.Sprintf(`declares the default %q, in which "#" starts a comment; MySQL reads one to the end of the line, which is where the generated column definition continues`, *c.Default),
			})
		}
	}
	return findings
}

// myHashComment reports whether def contains a "#" that MySQL would read as the
// start of a comment. A column with no default has none.
//
// Quote awareness is the whole job, and the reason this is a walk rather than a
// strings.Contains: '#ff0000' is an ordinary string default that must pass,
// while a "#" standing outside quotes is a comment. The rule for what closes a
// string is internal/check's - a doubled quote does not - re-implemented rather
// than shared for the reason precheck.go's tableLabel gives, and narrower than
// scanExpr because this looks for one byte instead of tokenising an expression.
//
// A string that is never closed ends the walk with nothing reported: that
// document already has internal/check's C8a finding against it, and a second
// finding about a "#" inside the text it could not read would be guesswork.
func myHashComment(def *string) bool {
	if def == nil {
		return false
	}
	s := *def
	for i := 0; i < len(s); i++ {
		switch s[i] {
		case '#':
			return true
		case '\'':
			for i++; i < len(s); i++ {
				if s[i] != '\'' {
					continue
				}
				if i+1 < len(s) && s[i+1] == '\'' {
					i++
					continue
				}
				break
			}
		}
	}
	return false
}

// myLeadsAKey reports whether column is the first column of the table's primary
// key or of one of its unique keys.
//
// indexes[] is deliberately not consulted, and neither is the index MySQL
// creates behind a foreign key. MySQL itself would accept either, but M1 puts
// every index in phase 2, so at the moment CREATE TABLE runs the only keys that
// exist are the ones the statement carries - and MySQL rejects the table before
// the index that would have justified it is created. Requiring the author to
// declare the key produces DDL that says what it means, which is the same
// argument the finding's own message makes.
func myLeadsAKey(t *model.Table, column string) bool {
	if pk := t.PrimaryKey; pk != nil && len(pk.Columns) > 0 && pk.Columns[0] == column {
		return true
	}
	for _, uk := range t.UniqueKeys {
		if len(uk.Columns) > 0 && uk.Columns[0] == column {
			return true
		}
	}
	return false
}

// myKeyFindings reports the keys of one table whose columns MySQL cannot index,
// in the order the objects appear in the JSON: the primary key, then the unique
// keys, then the indexes.
//
// M8, second half. Unlike the PostgreSQL user-defined type that is emitted and
// fails on execution, this is entirely contained in the document: the column's
// type is right there, MySQL will refuse the statement, and there is no correct
// DDL to write instead, because the prefix length or the generated column that
// would make it legal has nowhere to live in the format. AGENTS.md allows an
// exporter to check what its own target requires, which is what this is, and
// keeps the same rule out of "jjf validate", which is why it is not there.
//
// One finding per key rather than one per column: a composite key over two TEXT
// columns is one key to redesign.
func myKeyFindings(t *model.Table) []check.Finding {
	// types maps a column name to its declared type, so that a key can ask
	// about a column without walking the table again for each one. It is
	// LOOKED UP and assigned and NEVER ranged over; the order of the findings
	// comes from the key walks below.
	types := make(map[string]string, len(t.Columns))
	for j := range t.Columns {
		types[t.Columns[j].Name] = t.Columns[j].Type
	}

	// unusable finds the first column of cols that cannot be in a key. A
	// column the table does not declare is skipped in silence, because
	// internal/check's C1 has already reported it and this walk has no type to
	// judge.
	unusable := func(cols []string) (column, typeName, clause string, found bool) {
		for _, name := range cols {
			declared, ok := types[name]
			if !ok {
				continue
			}
			if clause, bad := myKeyUnusableType(upperASCII(declared)); bad {
				return name, declared, clause, true
			}
		}
		return "", "", "", false
	}

	var findings []check.Finding
	report := func(what string, cols []string) {
		column, typeName, clause, found := unusable(cols)
		if !found {
			return
		}
		findings = append(findings, check.Finding{
			Where:   tableLabel(t.Name),
			Message: fmt.Sprintf("declares %s over column %q, whose type is %s; %s", what, column, typeName, clause),
		})
	}

	if pk := t.PrimaryKey; pk != nil {
		report("a primary key", pk.Columns)
	}
	for _, uk := range t.UniqueKeys {
		report(myNamedKey("unique key", uk.Name), uk.Columns)
	}
	for _, ix := range t.Indexes {
		report(myNamedKey("index", ix.Name), ix.Columns)
	}
	return findings
}

// myNamedKey describes one key for a finding, quoting its name when it has one.
// The schema leaves uniqueKeys[].name optional, so "a unique key" has to read
// as well as `unique key "uq_user_email"` does.
//
// It carries the dialect prefix although nothing about it is MySQL-specific,
// because the rule this file's header states is about where a function lives
// rather than about what it knows: an unprefixed name in this package means
// shared by both dialects, and only text.go and typemap.go hold those.
func myNamedKey(kind, name string) string {
	if name == "" {
		return "a " + kind
	}
	return kind + " " + fmt.Sprintf("%q", name)
}
