package ddl

import (
	"bufio"
	"fmt"
	"io"
	"strings"

	"github.com/shutx-net/jumping-json-flush/internal/check"
	"github.com/shutx-net/jumping-json-flush/internal/model"
)

// ---------------------------------------------------------------------------
// The MySQL dialect
// ---------------------------------------------------------------------------

// Everything MySQL alone knows lives in this file, arranged the way postgres.go
// is and for the reason its header gives: one file per dialect, so that a
// change to one dialect touches one file and a reviewer reads one dialect at a
// time. The my prefix carries the same claim the pg prefix does - a delimiter,
// a type table and a precondition are facts about a target and not about SQL.
//
// design/ddl-export.md's MySQL table is the record this file implements, and
// the comments below cite it by row: M1 for the three phases, M2 for the
// backticks, M3 for AUTO_INCREMENT, M4 for the folded comments, M5 for the
// inverted namespaces, M6 for the doubled backslash, M7 for the parameters and
// M8 for what the type name alone decides. A row and its function must move
// together; the numbers are cited so that they can be.

// ---------------------------------------------------------------------------
// Phases
// ---------------------------------------------------------------------------

// myWriteScript emits the whole script in three fixed phases: every
// CREATE TABLE, then every CREATE INDEX, then every foreign key as an
// ALTER TABLE.
//
// Three rather than PostgreSQL's four, and the missing one is not a
// simplification: MySQL has no COMMENT ON statement at all, so the fourth phase
// has nowhere to go and the two fields it carries ride on the definitions
// themselves - COMMENT on the column, COMMENT= on the table. That is M4, and
// pgHasComments' own comment says the same thing from the other side.
// Restating a column's whole definition in an ALTER TABLE ... MODIFY COLUMN was
// the alternative, and it would write one authored fact into the script twice.
//
// Everything else about choice 1 survives. Nothing in phase 1 refers to another
// table, so mutual references and self references still need no ordering and no
// cycle handling. Phase 2 still precedes phase 3, because MySQL accepts a plain
// UNIQUE INDEX as a foreign key target exactly as PostgreSQL does, so
// indexes[].unique is a legitimate source of the uniqueness a foreign key
// requires and has to exist first.
//
// The two header lines are byte for byte the ones pgWriteScript writes, and a
// test holds the two writers to agreeing. They are emitted per dialect rather
// than in Export because a dialect whose comment syntax differed would have to
// write them differently.
func myWriteScript(w *bufio.Writer, doc *model.Document) {
	io.WriteString(w, "-- Generated by jjf from a database design document.\n")
	io.WriteString(w, "-- The JSON is the source of truth: edit it and export again, never this file.\n")

	// The schema requires at least one table with at least one column, so this
	// section is never empty and needs no guard. The two below do.
	io.WriteString(w, "\n-- Tables\n\n")
	for i := range doc.Tables {
		if i > 0 {
			io.WriteString(w, "\n")
		}
		myWriteCreateTable(w, &doc.Tables[i])
	}

	if hasIndexes(doc) {
		io.WriteString(w, "\n-- Indexes\n\n")
		myWriteIndexes(w, doc)
	}
	if hasForeignKeys(doc) {
		io.WriteString(w, "\n-- Foreign keys\n\n")
		myWriteForeignKeys(w, doc)
	}
}

// ---------------------------------------------------------------------------
// Phase 1: tables
// ---------------------------------------------------------------------------

// myWriteCreateTable emits one table: every column in document order, then the
// primary key, then the unique keys, then the table's own comment after the
// closing parenthesis.
//
// Foreign keys are never inline, not even a self-reference, which is what makes
// phase 1 free of any dependency between tables. Indexes are not inline either,
// although mysqldump writes them as KEY clauses: keeping them in phase 2 is
// choice 2's rule, and the delta between the two writers stays the things that
// genuinely differ. What the round trip reads back from an inline KEY clause is
// the importer's problem and costs nothing, because the document is the same
// either way.
func myWriteCreateTable(w *bufio.Writer, t *model.Table) {
	fmt.Fprintf(w, "CREATE TABLE %s (\n", myQuoteIdent(t.Name))

	items := make([]string, 0, len(t.Columns)+1+len(t.UniqueKeys))
	for i := range t.Columns {
		items = append(items, myColumnItem(&t.Columns[i]))
	}
	if pk := t.PrimaryKey; pk != nil {
		items = append(items, constraintPrefix(myQuoteIdent, pk.Name)+"PRIMARY KEY ("+quotedList(myQuoteIdent, pk.Columns)+")")
	}
	for _, uk := range t.UniqueKeys {
		items = append(items, constraintPrefix(myQuoteIdent, uk.Name)+"UNIQUE ("+quotedList(myQuoteIdent, uk.Columns)+")")
	}

	for i, item := range items {
		io.WriteString(w, indent)
		io.WriteString(w, item)
		if i < len(items)-1 {
			io.WriteString(w, ",")
		}
		io.WriteString(w, "\n")
	}
	io.WriteString(w, ")")
	if text, ok := commentText(t.Name, t.LogicalName, t.Description); ok {
		io.WriteString(w, " COMMENT=")
		io.WriteString(w, myQuoteLiteral(text))
	}
	io.WriteString(w, ";\n")
}

// myColumnItem renders one column definition.
//
// The order is name, type, NOT NULL, DEFAULT, AUTO_INCREMENT, COMMENT, which is
// not pgColumnItem's order and is deliberately mysqldump's. The same argument
// the four-space indent rests on applies to the order of the words inside the
// line: a generated script and a dump of the database it created should read
// alike, and MySQL's column_definition grammar is less forgiving than
// PostgreSQL's about where AUTO_INCREMENT may sit, so matching the dump removes
// the question rather than answering it. Symmetry with the other writer would
// have been the alternative and is worth less than agreement with the dump this
// output is compared against twice in every round trip.
//
// NOT NULL is emitted only when the document says the column is not nullable,
// for the reason pgColumnItem gives: NULL is SQL's own default and stating it
// adds nothing.
//
// The default is copied out verbatim, with no quoting and no normalisation: the
// field is defined as SQL expression text and internal/check has already
// refused an empty one or one that does not read as an expression. A column
// carrying both a default and autoIncrement never reaches here, because myCheck
// reports it and Accept refuses the document.
func myColumnItem(c *model.Column) string {
	var b strings.Builder
	b.WriteString(myQuoteIdent(c.Name))
	b.WriteString(" ")
	b.WriteString(myRenderType(c))
	if !c.Nullable {
		b.WriteString(" NOT NULL")
	}
	if c.Default != nil {
		b.WriteString(" DEFAULT ")
		b.WriteString(*c.Default)
	}
	if c.AutoIncrement {
		b.WriteString(" AUTO_INCREMENT")
	}
	// M4: the column half of the comment fold. commentText is the shared
	// composition, so the first line is the logical name and the rest is the
	// description here exactly as it is in a COMMENT ON - which is what lets
	// the MySQL importer split an inline comment where the PostgreSQL one
	// splits a COMMENT ON.
	if text, ok := commentText(c.Name, c.LogicalName, c.Description); ok {
		b.WriteString(" COMMENT ")
		b.WriteString(myQuoteLiteral(text))
	}
	return b.String()
}

// ---------------------------------------------------------------------------
// Phase 2: indexes
// ---------------------------------------------------------------------------

// myWriteIndexes emits one statement per index, tables in document order and
// each table's indexes in document order.
func myWriteIndexes(w *bufio.Writer, doc *model.Document) {
	for i := range doc.Tables {
		t := &doc.Tables[i]
		for _, ix := range t.Indexes {
			unique := ""
			if ix.Unique {
				unique = "UNIQUE "
			}
			fmt.Fprintf(w, "CREATE %sINDEX %s ON %s (%s);\n",
				unique, myQuoteIdent(ix.Name), myQuoteIdent(t.Name), quotedList(myQuoteIdent, ix.Columns))
		}
	}
}

// ---------------------------------------------------------------------------
// Phase 3: foreign keys
// ---------------------------------------------------------------------------

// myWriteForeignKeys emits one ALTER TABLE per foreign key.
//
// The referential actions are written as the document spells them, and all five
// are legal MySQL text. Only four of them do anything: MySQL 8 accepts
// SET DEFAULT, records it and dumps it back, but InnoDB never performs the
// action and answers the delete it was supposed to handle with a foreign key
// error instead. That is drift rather than a refusal - the script is accepted,
// the document survives a round trip unchanged, and refusing it would refuse a
// document the importer can produce - and design/ddl-export.md's note under the
// MySQL table says so.
//
// ON UPDATE precedes ON DELETE, matching the field order in model.ForeignKey
// and the property order in the schema. Unlike PostgreSQL, MySQL keeps an
// explicit NO ACTION out of what it stores, so a document that states it does
// not get it back from a round trip; that is expected rather than a bug, in
// exactly the way pgWriteForeignKeys describes for its own dump tool.
func myWriteForeignKeys(w *bufio.Writer, doc *model.Document) {
	for i := range doc.Tables {
		t := &doc.Tables[i]
		for _, fk := range t.ForeignKeys {
			fmt.Fprintf(w, "ALTER TABLE %s ADD %sFOREIGN KEY (%s) REFERENCES %s (%s)",
				myQuoteIdent(t.Name), constraintPrefix(myQuoteIdent, fk.Name), quotedList(myQuoteIdent, fk.Columns),
				myQuoteIdent(fk.References.Table), quotedList(myQuoteIdent, fk.References.Columns))
			if fk.OnUpdate != "" {
				fmt.Fprintf(w, " ON UPDATE %s", fk.OnUpdate)
			}
			if fk.OnDelete != "" {
				fmt.Fprintf(w, " ON DELETE %s", fk.OnDelete)
			}
			io.WriteString(w, ";\n")
		}
	}
}

// ---------------------------------------------------------------------------
// Quoting
// ---------------------------------------------------------------------------

// myQuoteIdent writes s as a MySQL delimited identifier, always emitting the
// surrounding backticks.
//
// M2, which is choice 4's argument with a different delimiter. There is no
// exception for a name that would be legal bare: the schema's $defs/identifier
// is ^[A-Za-z_][A-Za-z0-9_]*$, so quoting is always safe, it removes the whole
// class of reserved-word collisions without a keyword list to maintain, and it
// preserves case on a server whose lower_case_table_names may be folding it.
//
// Not the double quote PostgreSQL uses: MySQL reads "order" as a string
// literal unless ANSI_QUOTES is in sql_mode, and putting it there would mean
// emitting a SET, which M6 rules out for the whole script.
//
// Doubling an embedded backtick is defensive rather than reachable - that
// pattern forbids one - and is here so that a future caller passing freer text
// cannot open a hole. The unit tests are the only place it is exercised, which
// is what text.go already says about pgQuoteIdent.
func myQuoteIdent(s string) string { return "`" + doubled(s, '`') + "`" }

// myQuoteLiteral writes s as a MySQL string literal, doubling the apostrophe
// and the backslash in one pass.
//
// M6, and the one place the two dialects' escaping genuinely differs rather
// than differing in a delimiter. MySQL treats a backslash inside a string as an
// escape character unless NO_BACKSLASH_ESCAPES is in sql_mode, which is not the
// default: 'C:\tmp' reaches the database as C: followed by a tab. This escaping
// is reachable, because it carries logicalName and description, which are free
// text in any language - a Windows path in a description is the ordinary way to
// meet it - and the failure is silent, since the script runs and stores the
// wrong text.
//
// One loop rather than two calls to doubled, for the reason doubled's own
// comment gives: chained replacements escape their own output, so doubling the
// backslash after the apostrophe would double the backslashes the first pass
// had just produced. Bytes of a multibyte UTF-8 sequence are all >= 0x80 and
// fall through untouched, so Japanese text survives unchanged.
//
// A newline is left alone, and has to be: a table comment is the logical name
// and the description joined by one, and the importer cuts it back apart at
// exactly that byte.
//
// The alternative was SET sql_mode='NO_BACKSLASH_ESCAPES' at the top of the
// script, so that PostgreSQL's rule would apply to both dialects.
// internal/export/ddl/text.go already refuses the equivalent for PostgreSQL -
// one setting invites character_set_client and time_zone after it - and a
// script that changes a session variable is a script whose effect depends on
// where it was run from.
func myQuoteLiteral(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 2)
	b.WriteByte('\'')
	for i := 0; i < len(s); i++ {
		switch c := s[i]; c {
		case '\'', '\\':
			b.WriteByte(c)
			b.WriteByte(c)
		default:
			b.WriteByte(c)
		}
	}
	b.WriteByte('\'')
	return b.String()
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

// myTypeParamKind reports how the parameters of the type called name are
// written. name has already been upper-cased and stripped of any attribute
// suffix by myRenderType, so BIGINT UNSIGNED never reaches here and would be
// answered paramUnknown if it did.
//
// M7. It is a switch and not a package-level map, for the reason
// internal/importer/postgres/typemap.go's canonicalTypeName gives verbatim: a
// map literal at package scope is mutable state any caller could corrupt.
//
// The list is short on purpose. Choice 5 says jjf keeps no per-system type
// catalogue, so this answers one question only - which attribute the
// parentheses hold - and every name it does not list falls to paramUnknown,
// where the document's own parameters are reproduced as stated. FLOAT and
// DOUBLE are left out for exactly that reason: MySQL reads FLOAT(24) as a
// precision in bits and FLOAT(10,2) as a deprecated precision and scale, and
// reproducing what the document says is right for both.
func myTypeParamKind(name string) paramKind {
	switch name {
	// Character, binary and bit strings: the parameter is a length. TINYINT is
	// here rather than with the integers because tinyint(1) is how MySQL
	// stores a boolean, mysqldump still writes it, and
	// skills/db-design/references/types.md tells authors to write
	// "length": 1 for exactly that - so dropping it would make the workbook
	// and the DDL describe different columns.
	case "VARCHAR", "CHARACTER VARYING", "CHAR", "CHARACTER",
		"BINARY", "VARBINARY", "BIT", "TINYINT":
		return paramLength

	// Exact numerics: the parameters are a precision and a scale.
	case "DECIMAL", "DEC", "NUMERIC", "FIXED":
		return paramPrecisionScale

	// Date and time: the parameter counts fractional-second digits, and MySQL
	// spells every one of them as a single word, so there is no infix case
	// here at all. paramTimePrecisionInfix stays a PostgreSQL-only answer.
	case "DATETIME", "TIMESTAMP", "TIME":
		return paramTimePrecision

	// Types that take no parameter jjf can write. The integers are here
	// because a display width has been deprecated since MySQL 8.0.17 and
	// mysqldump no longer writes one, so emitting INT(11) would be emitting a
	// construct the server is removing. ENUM and SET are here because their
	// parenthesis holds a value list, which is not a number and which the
	// document has nowhere to keep - see M8, and myCheck's silence about it.
	case "INT", "INTEGER", "SMALLINT", "MEDIUMINT", "BIGINT",
		"BOOL", "BOOLEAN", "DATE", "YEAR",
		"TEXT", "TINYTEXT", "MEDIUMTEXT", "LONGTEXT",
		"BLOB", "TINYBLOB", "MEDIUMBLOB", "LONGBLOB",
		"JSON", "ENUM", "SET":
		return paramNone
	}
	return paramUnknown
}

// myTypeAttributes are the trailing words MySQL puts AFTER a type's
// parentheses, longest first so that the two-word form is recognised before its
// own second word is.
//
// They are the reason a MySQL type name can contain a space at all, and the
// schema's columnType pattern - ^[A-Za-z][A-Za-z0-9_ ]*$ - permits it, so
// "BIGINT UNSIGNED" is an ordinary value that a document imported from MySQL
// legitimately carries.
//
// A function returning a fresh slice rather than a package-level var, for the
// reason cmd/jjf/export.go's exportFormats gives: a package-level slice is
// mutable state any caller could corrupt. It is walked in order, never ranged
// over as a map.
func myTypeAttributes() []string {
	return []string{" UNSIGNED ZEROFILL", " UNSIGNED", " ZEROFILL"}
}

// myAttributeSuffix splits a trailing UNSIGNED, ZEROFILL or UNSIGNED ZEROFILL
// off name, returning what is left and the suffix as the document spelled it.
//
// The suffix is returned rather than normalised because choice 5 passes the
// type name through as written; only the comparison folds case, and it folds
// ASCII alone, for the reason typemap.go's upperASCII gives.
//
// A type whose whole name is an attribute keeps it: the remainder would be
// empty, which is no type at all. That is the guard pgRenderType keeps for a
// type actually called ARRAY, and it is here for the same reason.
func myAttributeSuffix(name string) (base, attr string) {
	upper := upperASCII(name)
	for _, suffix := range myTypeAttributes() {
		if len(name) > len(suffix) && strings.HasSuffix(upper, suffix) {
			return name[:len(name)-len(suffix)], name[len(name)-len(suffix):]
		}
	}
	return name, ""
}

// myRenderType folds a column's declared attributes back into its type, which
// is the reverse of what the importer took apart.
//
// M7. The parameters go BEFORE the attribute - DECIMAL(10,2) UNSIGNED, not
// DECIMAL UNSIGNED(10,2), which MySQL answers with a syntax error - so the
// attribute is split off, the parameters are rendered against what remains, and
// the attribute is put back. This is structurally the same problem
// pgInfixTimePrecision solves, approached from the other end: a parameter that
// cannot simply be appended. Saying so here is what stops a later reader taking
// one of the two for a mistake.
//
// Leaving BIGINT UNSIGNED to paramUnknown was the alternative, and it would
// reproduce whatever the document declared - which is right for a type jjf does
// not know and wrong for the one case that matters, DECIMAL UNSIGNED, where it
// would put the parenthesis after the attribute.
//
// The type NAME is passed through exactly as the document writes it and is
// never rewritten or quoted, for the reasons pgRenderType gives at length. A
// parameter a known type cannot take is dropped without a word, the same way
// and for the same reason: Export writes into an io.Writer and has no channel
// to warn on, so the documentation says it instead.
func myRenderType(c *model.Column) string {
	base, attr := myAttributeSuffix(c.Type)
	return base + typeParams(myTypeParamKind(upperASCII(base)), c) + attr
}

// myLengthlessTypes are the type names MySQL gives no default length to, so
// that a column declaring one without a length cannot be written at all.
//
// Two names and not a table of every type whose parameter is mandatory. CHAR,
// BINARY, BIT and DECIMAL all have a server default and are absent on purpose;
// ENUM and SET are absent for the opposite reason, that the document can never
// supply what they need. See M8 for why those three cases are not one case.
func myLengthlessTypes() []string { return []string{"VARCHAR", "VARBINARY"} }

// myKeyUnusableType reports why a column of the type called name cannot be part
// of a key, and whether it can be at all. name has already been upper-cased.
//
// The returned clause finishes the finding's sentence, because the two families
// fail differently and a single wording would be wrong for one of them: MySQL
// answers a TEXT or BLOB column in a key with ERROR 1170 and wants a prefix
// length, and a JSON column with ERROR 3152, which no prefix length would
// satisfy.
func myKeyUnusableType(name string) (clause string, unusable bool) {
	switch name {
	case "TEXT", "TINYTEXT", "MEDIUMTEXT", "LONGTEXT",
		"BLOB", "TINYBLOB", "MEDIUMBLOB", "LONGBLOB":
		return "MySQL refuses such a column in a key without a prefix length, which the document has nowhere to put", true
	case "JSON":
		return "MySQL indexes such a column only through a generated column on a JSON path, which the document has nowhere to express", true
	}
	return "", false
}

// ---------------------------------------------------------------------------
// Preconditions
// ---------------------------------------------------------------------------

// myCheck reports the preconditions that are statements about MySQL rather than
// about the document, in document order.
//
// It returns only its own findings and never calls check.Document: Check owns
// that call and concatenates, which is what keeps the two groups
// un-interleaved.
//
// The list is not pgCheck's with a different database's name in the messages,
// and M5 is why: MySQL scopes foreign key names per SCHEMA and index and
// constraint names per TABLE, which is the exact inverse of PostgreSQL. Reusing
// pgCheck's walk on the theory that being stricter than the target is safe
// would refuse a legal MySQL document and pass an illegal one at the same time.
//
// Every rule below was run against a live MySQL 8.0 before it was written here.
// The messages describe the behaviour rather than quoting an error number,
// because a number is the one part of a server message that a release may
// renumber and a reader cannot act on.
func myCheck(doc *model.Document) []check.Finding {
	var findings []check.Finding

	// tables and constraints map a name in a schema-wide namespace to a
	// description of whatever claimed it first, so that a collision can say
	// what it collided with. Both maps are only ever LOOKED UP and assigned,
	// NEVER ranged over: ranging would make the order of the findings depend
	// on Go's map iteration and destroy the determinism the goldens and the
	// CLI output rest on. The order comes from the slice walks below and from
	// nowhere else.
	//
	// Two maps rather than pgCheck's one, because MySQL has two separate
	// schema-wide namespaces rather than one shared by four kinds of object: a
	// foreign key may take a name a table already has, and does.
	tables := make(map[string]bool, len(doc.Tables))
	constraints := make(map[string]string)
	// The two "reported" sets remember the names already reported, for the
	// reason internal/check's usedNames gives: three tables sharing a name is
	// one mistake to fix, not two findings. There are two of them for the same
	// reason there are two namespaces - a document may legally call a table
	// and a foreign key by one name, and one shared set would let a collision
	// in one namespace silence a collision in the other.
	tablesReported := make(map[string]bool)
	constraintsReported := make(map[string]bool)

	for i := range doc.Tables {
		t := &doc.Tables[i]
		label := tableLabel(t.Name)

		// M5, first half - a table name is schema-wide. internal/check
		// deliberately does not report duplicate table names, so without this
		// a document naming two tables "orders" would emit CREATE TABLE twice
		// and MySQL would reject the script. Index names are absent from this
		// namespace, which is where PostgreSQL's rule and MySQL's part
		// company: two MySQL tables may each carry an ix_created, and an index
		// may even take a name a table already has.
		if t.Name != "" {
			if tables[t.Name] && !tablesReported[t.Name] {
				tablesReported[t.Name] = true
				findings = append(findings, check.Finding{
					Where:   label,
					Message: fmt.Sprintf("is the second table this document calls %q; MySQL cannot create two tables of one name in a schema", t.Name),
				})
			}
			tables[t.Name] = true
		}

		findings = append(findings, myColumnFindings(t)...)
		findings = append(findings, myKeyFindings(t)...)

		// M5, second half. A foreign key name lives in a per-DATABASE
		// namespace in InnoDB, so two tables may not both carry an fk_parent -
		// which is the inverse of PostgreSQL, where pg_constraint is unique per
		// table and internal/export/ddl/precheck_test.go's
		// TestForeignKeyNamesMayRepeatAcrossTables pins that they may.
		for _, fk := range t.ForeignKeys {
			if fk.Name == "" {
				// The schema makes foreignKeys[].name optional and MySQL
				// invents one, so several unnamed foreign keys in one document
				// are ordinary rather than a collision.
				continue
			}
			owner := "foreign key " + fk.Name + " on table " + t.Name
			prior, taken := constraints[fk.Name]
			if !taken {
				constraints[fk.Name] = owner
				continue
			}
			if constraintsReported[fk.Name] {
				continue
			}
			constraintsReported[fk.Name] = true
			findings = append(findings, check.Finding{
				Where:   label,
				Message: fmt.Sprintf("declares foreign key %q, a name already used by %s; InnoDB keeps foreign key names in one namespace per schema", fk.Name, prior),
			})
		}
	}
	return findings
}

// myColumnFindings reports what MySQL refuses about the columns of one table,
// in column order.
//
// At most one finding comes out per column, the rule internal/check's
// checkColumnDefault already follows: one authoring mistake, one finding. The
// order the four AUTO_INCREMENT rules are tried in is the order in which one
// explains the others - a second AUTO_INCREMENT column is the whole problem
// with that column, and telling its author that it also leads no key would be
// telling them to fix something they are about to delete.
func myColumnFindings(t *model.Table) []check.Finding {
	var findings []check.Finding

	// auto is the first AUTO_INCREMENT column of the table, so that the second
	// one can name it. The document's order decides which is which, exactly as
	// it decides everything else this package reports.
	auto := ""
	for j := range t.Columns {
		c := &t.Columns[j]
		label := columnLabel(c.Name, t.Name)

		if c.AutoIncrement {
			// M3, all four rules. Each is a fact about MySQL: the first two
			// are refused outright by the server, the third is refused as an
			// invalid default, and the fourth is the silent one - MySQL
			// accepts a nullable AUTO_INCREMENT column and stores it NOT NULL,
			// which is C5's argument for a column outside the primary key and
			// PostgreSQL's identity rule in another grammar.
			said := len(findings)
			switch {
			case auto != "":
				findings = append(findings, check.Finding{
					Where:   label,
					Message: fmt.Sprintf("is autoIncrement, and so is column %q on the same table; MySQL allows one AUTO_INCREMENT column per table", auto),
				})
			case c.Default != nil:
				findings = append(findings, check.Finding{
					Where:   label,
					Message: "is autoIncrement and also declares a default; MySQL refuses a default on an AUTO_INCREMENT column",
				})
			case c.Nullable:
				findings = append(findings, check.Finding{
					Where:   label,
					Message: "is autoIncrement and declared nullable; MySQL makes an AUTO_INCREMENT column NOT NULL, so the database would not match the document",
				})
			case !myLeadsAKey(t, c.Name):
				findings = append(findings, check.Finding{
					Where:   label,
					Message: "is autoIncrement and leads no key; MySQL needs it to be the first column of this table's primaryKey or of one of its uniqueKeys, and an entry in indexes cannot serve because the script creates it after the table",
				})
			}
			if auto == "" {
				auto = c.Name
			}
			if len(findings) > said {
				// One finding per column. The skip is conditional rather than
				// unconditional so that a column this block had nothing to say
				// about still reaches the check below: "at most one" is the
				// rule, not "the first branch that matches owns the column".
				continue
			}
		}

		// M8, first half. A bare VARCHAR is a syntax error rather than a
		// column of some default width, and mysqldump always writes the
		// length, so no document the importer produced can be in this state
		// and refusing costs the round trip nothing. Two type spellings and
		// not a table of every type whose parameter is mandatory: see
		// myLengthlessTypes.
		if c.Length == nil {
			name := upperASCII(c.Type)
			for _, lengthless := range myLengthlessTypes() {
				if name == lengthless {
					findings = append(findings, check.Finding{
						Where:   label,
						Message: fmt.Sprintf("declares type %q and no length; MySQL has no default length for it, so the column would be a syntax error rather than a column", c.Type),
					})
					break
				}
			}
		}
	}
	return findings
}

// myLeadsAKey reports whether column is the first column of the table's primary
// key or of one of its unique keys.
//
// indexes[] is deliberately not consulted, and neither is the index MySQL
// creates behind a foreign key. MySQL itself would accept either, but M1 puts
// every index in phase 2, so at the moment CREATE TABLE runs the only keys that
// exist are the ones the statement carries - and MySQL rejects the table before
// the index that would have justified it is created. Requiring the author to
// declare the key produces DDL that says what it means, which is the same
// argument the finding's own message makes.
func myLeadsAKey(t *model.Table, column string) bool {
	if pk := t.PrimaryKey; pk != nil && len(pk.Columns) > 0 && pk.Columns[0] == column {
		return true
	}
	for _, uk := range t.UniqueKeys {
		if len(uk.Columns) > 0 && uk.Columns[0] == column {
			return true
		}
	}
	return false
}

// myKeyFindings reports the keys of one table whose columns MySQL cannot index,
// in the order the objects appear in the JSON: the primary key, then the unique
// keys, then the indexes.
//
// M8, second half. Unlike the PostgreSQL user-defined type that is emitted and
// fails on execution, this is entirely contained in the document: the column's
// type is right there, MySQL will refuse the statement, and there is no correct
// DDL to write instead, because the prefix length or the generated column that
// would make it legal has nowhere to live in the format. AGENTS.md allows an
// exporter to check what its own target requires, which is what this is, and
// keeps the same rule out of "jjf validate", which is why it is not there.
//
// One finding per key rather than one per column: a composite key over two TEXT
// columns is one key to redesign.
func myKeyFindings(t *model.Table) []check.Finding {
	// types maps a column name to its declared type, so that a key can ask
	// about a column without walking the table again for each one. It is
	// LOOKED UP and assigned and NEVER ranged over; the order of the findings
	// comes from the key walks below.
	types := make(map[string]string, len(t.Columns))
	for j := range t.Columns {
		types[t.Columns[j].Name] = t.Columns[j].Type
	}

	// unusable finds the first column of cols that cannot be in a key. A
	// column the table does not declare is skipped in silence, because
	// internal/check's C1 has already reported it and this walk has no type to
	// judge.
	unusable := func(cols []string) (column, typeName, clause string, found bool) {
		for _, name := range cols {
			declared, ok := types[name]
			if !ok {
				continue
			}
			if clause, bad := myKeyUnusableType(upperASCII(declared)); bad {
				return name, declared, clause, true
			}
		}
		return "", "", "", false
	}

	var findings []check.Finding
	report := func(what string, cols []string) {
		column, typeName, clause, found := unusable(cols)
		if !found {
			return
		}
		findings = append(findings, check.Finding{
			Where:   tableLabel(t.Name),
			Message: fmt.Sprintf("declares %s over column %q, whose type is %s; %s", what, column, typeName, clause),
		})
	}

	if pk := t.PrimaryKey; pk != nil {
		report("a primary key", pk.Columns)
	}
	for _, uk := range t.UniqueKeys {
		report(myNamedKey("unique key", uk.Name), uk.Columns)
	}
	for _, ix := range t.Indexes {
		report(myNamedKey("index", ix.Name), ix.Columns)
	}
	return findings
}

// myNamedKey describes one key for a finding, quoting its name when it has one.
// The schema leaves uniqueKeys[].name optional, so "a unique key" has to read
// as well as `unique key "uq_user_email"` does.
//
// It carries the dialect prefix although nothing about it is MySQL-specific,
// because the rule this file's header states is about where a function lives
// rather than about what it knows: an unprefixed name in this package means
// shared by both dialects, and only text.go and typemap.go hold those.
func myNamedKey(kind, name string) string {
	if name == "" {
		return "a " + kind
	}
	return kind + " " + fmt.Sprintf("%q", name)
}
