package ddl

import (
	"bufio"
	"fmt"
	"io"
	"strconv"
	"strings"

	"github.com/shutx-net/jumping-json-flush/internal/check"
	"github.com/shutx-net/jumping-json-flush/internal/model"
)

// ---------------------------------------------------------------------------
// The PostgreSQL dialect
// ---------------------------------------------------------------------------

// Everything PostgreSQL alone knows lives in this file: its four phases, its
// quoting, its type table and the preconditions that are statements about
// PostgreSQL rather than about the document. dialect.go names two of these
// functions and nothing else in the package names any of them.
//
// One file per dialect rather than one file per concern - a text.go holding
// both dialects' quoting, a typemap.go holding both dialects' type tables -
// because the by-concern arrangement makes every change to one dialect touch
// four files and makes every reviewer read two dialects at once. It is also
// what lets the unqualified names in text.go and typemap.go mean "shared by
// both" rather than quietly meaning PostgreSQL, which is the confusion the
// dialect seam exists to remove.
//
// The pg prefix is therefore not decoration. An unprefixed quoteIdent in this
// package would read as a claim that there is one way to quote an identifier,
// which is the claim the seam exists to withdraw: the delimiter is a fact
// about a target and not about SQL.

// ---------------------------------------------------------------------------
// Phases
// ---------------------------------------------------------------------------

// pgWriteScript emits the whole script in the four fixed phases: every
// CREATE TABLE, then every CREATE INDEX, then every foreign key as an
// ALTER TABLE, then every COMMENT ON.
//
// The order is the specification's first choice and the reason there is no
// topological sort anywhere in this package. Nothing in phase 1 refers to
// another table, so mutual references and self references need no ordering
// between tables and no cycle handling. Phase 2 must precede phase 3 because
// PostgreSQL accepts a plain UNIQUE INDEX as a foreign key target, not only a
// UNIQUE constraint, so indexes[].unique is a legitimate source of the
// uniqueness a foreign key requires and has to exist first.
//
// The header carries no timestamp, no tool version and no input path. A version
// would make two builds of jjf disagree about the same document, which matters
// most for this artifact of the three, because this is the one that gets
// diffed. Every dialect writes those same two lines, byte for byte; they are
// emitted here rather than in Export because a dialect whose comment syntax
// differed would have to write them differently, and a test holds the two
// current writers to agreeing.
func pgWriteScript(w *bufio.Writer, doc *model.Document) {
	io.WriteString(w, "-- Generated by jjf from a database design document.\n")
	io.WriteString(w, "-- The JSON is the source of truth: edit it and export again, never this file.\n")

	// The schema requires at least one table with at least one column, so this
	// section is never empty and needs no guard. The three below do.
	io.WriteString(w, "\n-- Tables\n\n")
	for i := range doc.Tables {
		if i > 0 {
			io.WriteString(w, "\n")
		}
		pgWriteCreateTable(w, &doc.Tables[i])
	}

	if hasIndexes(doc) {
		io.WriteString(w, "\n-- Indexes\n\n")
		pgWriteIndexes(w, doc)
	}
	if hasForeignKeys(doc) {
		io.WriteString(w, "\n-- Foreign keys\n\n")
		pgWriteForeignKeys(w, doc)
	}
	if pgHasComments(doc) {
		io.WriteString(w, "\n-- Comments\n\n")
		pgWriteComments(w, doc)
	}
}

// ---------------------------------------------------------------------------
// Phase 1: tables
// ---------------------------------------------------------------------------

// pgWriteCreateTable emits one table: every column in document order, then the
// primary key, then the unique keys.
//
// Foreign keys are never inline, not even a self-reference. That is what makes
// phase 1 free of any dependency between tables.
func pgWriteCreateTable(w *bufio.Writer, t *model.Table) {
	fmt.Fprintf(w, "CREATE TABLE %s (\n", pgQuoteIdent(t.Name))

	items := make([]string, 0, len(t.Columns)+1+len(t.UniqueKeys))
	for i := range t.Columns {
		items = append(items, pgColumnItem(&t.Columns[i]))
	}
	if pk := t.PrimaryKey; pk != nil {
		items = append(items, constraintPrefix(pgQuoteIdent, pk.Name)+"PRIMARY KEY ("+quotedList(pgQuoteIdent, pk.Columns)+")")
	}
	for _, uk := range t.UniqueKeys {
		items = append(items, constraintPrefix(pgQuoteIdent, uk.Name)+"UNIQUE ("+quotedList(pgQuoteIdent, uk.Columns)+")")
	}

	for i, item := range items {
		io.WriteString(w, indent)
		io.WriteString(w, item)
		if i < len(items)-1 {
			io.WriteString(w, ",")
		}
		io.WriteString(w, "\n")
	}
	io.WriteString(w, ");\n")
}

// pgColumnItem renders one column definition.
//
// PostgreSQL accepts the column constraints in any order, so the order here is
// a style choice whose only requirement is that it never changes. IDENTITY and
// DEFAULT are mutually exclusive - Accept refuses a column carrying both,
// because PostgreSQL refuses one - so their relative order is never observable.
// NOT NULL last is what pg_dump writes.
//
// NOT NULL is emitted only when the document says the column is not nullable;
// NULL is SQL's own default and stating it adds nothing. A primary key column
// therefore carries both NOT NULL and PRIMARY KEY, which is redundant and is
// again what pg_dump writes.
//
// The default is copied out verbatim, with no quoting and no normalisation: the
// field is defined as SQL expression text, and internal/check has already
// refused an empty one or one that does not read as an expression.
func pgColumnItem(c *model.Column) string {
	var b strings.Builder
	b.WriteString(pgQuoteIdent(c.Name))
	b.WriteString(" ")
	b.WriteString(pgRenderType(c))
	if c.AutoIncrement {
		// Standard SQL, and the form PostgreSQL recommends over SERIAL.
		// Available since PostgreSQL 10, so it needs no version gate anywhere
		// in the supported range.
		b.WriteString(" GENERATED BY DEFAULT AS IDENTITY")
	}
	if c.Default != nil {
		b.WriteString(" DEFAULT ")
		b.WriteString(*c.Default)
	}
	if !c.Nullable {
		b.WriteString(" NOT NULL")
	}
	return b.String()
}

// ---------------------------------------------------------------------------
// Phase 2: indexes
// ---------------------------------------------------------------------------

// pgWriteIndexes emits one statement per index, tables in document order and
// each table's indexes in document order.
func pgWriteIndexes(w *bufio.Writer, doc *model.Document) {
	for i := range doc.Tables {
		t := &doc.Tables[i]
		for _, ix := range t.Indexes {
			unique := ""
			if ix.Unique {
				unique = "UNIQUE "
			}
			fmt.Fprintf(w, "CREATE %sINDEX %s ON %s (%s);\n",
				unique, pgQuoteIdent(ix.Name), pgQuoteIdent(t.Name), quotedList(pgQuoteIdent, ix.Columns))
		}
	}
}

// ---------------------------------------------------------------------------
// Phase 3: foreign keys
// ---------------------------------------------------------------------------

// pgWriteForeignKeys emits one ALTER TABLE per foreign key.
//
// The referential actions are written as the document spells them, which is
// legal PostgreSQL text for all five. ON UPDATE precedes ON DELETE, matching
// the field order in model.ForeignKey and the property order in the schema. NO
// ACTION is PostgreSQL's own default and pg_dump omits it, so a document that
// states it explicitly does not get it back from a round trip; that is expected
// rather than a bug, and the documentation says so.
func pgWriteForeignKeys(w *bufio.Writer, doc *model.Document) {
	for i := range doc.Tables {
		t := &doc.Tables[i]
		for _, fk := range t.ForeignKeys {
			fmt.Fprintf(w, "ALTER TABLE %s ADD %sFOREIGN KEY (%s) REFERENCES %s (%s)",
				pgQuoteIdent(t.Name), constraintPrefix(pgQuoteIdent, fk.Name), quotedList(pgQuoteIdent, fk.Columns),
				pgQuoteIdent(fk.References.Table), quotedList(pgQuoteIdent, fk.References.Columns))
			if fk.OnUpdate != "" {
				fmt.Fprintf(w, " ON UPDATE %s", fk.OnUpdate)
			}
			if fk.OnDelete != "" {
				fmt.Fprintf(w, " ON DELETE %s", fk.OnDelete)
			}
			io.WriteString(w, ";\n")
		}
	}
}

// ---------------------------------------------------------------------------
// Phase 4: comments
// ---------------------------------------------------------------------------

// pgWriteComments emits COMMENT ON statements: tables in document order, and
// within each table its own comment first, then its columns in document order.
func pgWriteComments(w *bufio.Writer, doc *model.Document) {
	for i := range doc.Tables {
		t := &doc.Tables[i]
		if text, ok := commentText(t.Name, t.LogicalName, t.Description); ok {
			fmt.Fprintf(w, "COMMENT ON TABLE %s IS %s;\n", pgQuoteIdent(t.Name), pgQuoteLiteral(text))
		}
		for j := range t.Columns {
			c := &t.Columns[j]
			if text, ok := commentText(c.Name, c.LogicalName, c.Description); ok {
				fmt.Fprintf(w, "COMMENT ON COLUMN %s.%s IS %s;\n",
					pgQuoteIdent(t.Name), pgQuoteIdent(c.Name), pgQuoteLiteral(text))
			}
		}
	}
}

// pgHasComments decides whether phase 4 exists at all. It is the one section
// guard that cannot be shared: hasIndexes and hasForeignKeys ask about a field
// every dialect writes somewhere, while a comments PHASE belongs to a dialect
// that has a COMMENT ON statement. A dialect without one has nowhere to put a
// fourth phase and has to fold the same two fields into CREATE TABLE, which is
// what design/ddl-export.md's M4 records.
func pgHasComments(doc *model.Document) bool {
	for i := range doc.Tables {
		t := &doc.Tables[i]
		if _, ok := commentText(t.Name, t.LogicalName, t.Description); ok {
			return true
		}
		for j := range t.Columns {
			c := &t.Columns[j]
			if _, ok := commentText(c.Name, c.LogicalName, c.Description); ok {
				return true
			}
		}
	}
	return false
}

// ---------------------------------------------------------------------------
// Quoting
// ---------------------------------------------------------------------------

// pgQuoteIdent writes s as a SQL delimited identifier, always emitting the
// surrounding double quotes.
//
// There is no exception for a name that would be legal bare. The schema's
// $defs/identifier is ^[A-Za-z_][A-Za-z0-9_]*$, which permits order, user,
// table and every other reserved word, so quoting unconditionally removes the
// whole class of collisions without a keyword list to maintain. It also
// preserves case: an unquoted Orders would reach PostgreSQL as orders and the
// database would stop matching the document.
//
// Doubling an embedded quote is defensive rather than reachable: that pattern
// forbids one. It is here so that a future caller passing freer text cannot
// open a hole, and the unit tests are the only place it is exercised.
func pgQuoteIdent(s string) string { return `"` + doubled(s, '"') + `"` }

// pgQuoteLiteral writes s as a SQL string literal.
//
// Unlike pgQuoteIdent's, this escaping IS reachable: it carries logicalName and
// description, which are free text in any language and may hold an apostrophe.
//
// A backslash is left alone on purpose. That is correct while
// standard_conforming_strings is on, which is PostgreSQL's default from 9.1
// onwards and therefore throughout the range jjf supports; the generated script
// does not SET it, because one setting invites search_path and client_encoding
// after it and the specification's list of what is not emitted did not
// contemplate any of them.
//
// A newline is left alone too, and has to be: a table comment is the logical
// name and the description joined by one, and the importer cuts it back apart
// at exactly that byte. An E'...\n...' escape string would look tidier and
// would break the round trip, because the importer's lexer keeps such a token
// raw.
func pgQuoteLiteral(s string) string { return `'` + doubled(s, '\'') + `'` }

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

// pgTypeParamKind reports how the parameters of the type called name are
// written. name has already been upper-cased and stripped of any array suffix.
//
// This is NOT internal/importer/postgres/typemap.go's table read backwards, and
// the two are deliberately separate. canonicalTypeName is keyed on the
// lowercase spellings pg_dump writes and answers "what does jjf call this
// type"; this one is keyed on whatever the document says and answers only
// "which attribute do the parentheses hold". Sharing them would mean an
// exported cross-package API for a fact each side needs in a different shape.
//
// It is a switch and not a package-level map, for the reason canonicalTypeName
// gives verbatim: a map literal at package scope is mutable state any caller
// could corrupt.
func pgTypeParamKind(name string) paramKind {
	switch name {
	// Character and bit strings: the parameter is a length.
	case "VARCHAR", "CHARACTER VARYING", "CHAR", "CHARACTER", "BPCHAR",
		"BIT", "BIT VARYING", "VARBIT":
		return paramLength

	// Exact numerics: the parameters are a precision and a scale.
	case "NUMERIC", "DECIMAL":
		return paramPrecisionScale

	// Date and time: the parameter counts fractional-second digits.
	case "TIMESTAMP", "TIMESTAMPTZ", "TIME", "TIMETZ", "INTERVAL":
		return paramTimePrecision

	// The spelled-out date and time names, whose parameter is infixed. The
	// importer never writes these - canonicalTypeName folds them into
	// TIMESTAMPTZ and friends - but a hand-authored document may, and
	// skills/db-design/references/types.md recommends the long form.
	case "TIMESTAMP WITH TIME ZONE", "TIMESTAMP WITHOUT TIME ZONE",
		"TIME WITH TIME ZONE", "TIME WITHOUT TIME ZONE":
		return paramTimePrecisionInfix

	// Types that take no parameter at all.
	case "INTEGER", "INT", "INT4", "BIGINT", "INT8", "SMALLINT", "INT2",
		"BOOLEAN", "BOOL", "DOUBLE PRECISION", "FLOAT8", "REAL", "FLOAT4",
		"TEXT", "BYTEA", "UUID", "JSON", "JSONB", "DATE", "MONEY",
		"INET", "CIDR", "MACADDR", "MACADDR8", "XML", "TSVECTOR", "TSQUERY",
		"OID", "NAME", "PG_LSN", "TXID_SNAPSHOT":
		return paramNone
	}
	return paramUnknown
}

// pgArraySuffix is what the importer appends to the element type name, because
// an array type cannot match the schema's columnType pattern - it has brackets.
const pgArraySuffix = " ARRAY"

// pgRenderType folds a column's declared attributes back into its type, which
// is the reverse of what the importer took apart.
//
// The type NAME is passed through exactly as the document writes it and is
// never rewritten: that is the specification's choice 5, and it is why this
// table decides only how the parentheses are read. It is never quoted either,
// unlike every identifier this package emits. That asymmetry looks like an
// inconsistency and is not: quoting would make "ORDER_STATUS" a different type
// from the lowercase order_status PostgreSQL actually created, and "integer" is
// not a type at all.
//
// A parameter a known type cannot take is dropped without a word: INTEGER with
// a length of 11 renders as INTEGER. Emitting integer(11) would be DDL
// PostgreSQL rejects, which breaks the promise that a document this exporter
// accepts produces a script the database takes; refusing the document would be
// an opinion about a design "jjf validate" calls fine; and dropping is what
// internal/importer/postgres/typemap.go does in the mirror situation. It warns
// there and cannot here - Export writes into an io.Writer and has no channel to
// say anything on - so the documentation says it instead.
func pgRenderType(c *model.Column) string {
	name := c.Type

	// The importer appends the suffix once even for a multi-dimensional array,
	// so one is stripped. A type actually called ARRAY keeps its name: the
	// remainder would be empty, which is no type at all.
	array := false
	if len(name) > len(pgArraySuffix) && upperASCII(name[len(name)-len(pgArraySuffix):]) == pgArraySuffix {
		name = name[:len(name)-len(pgArraySuffix)]
		array = true
	}

	var out string
	if kind := pgTypeParamKind(upperASCII(name)); kind == paramTimePrecisionInfix {
		out = pgInfixTimePrecision(name, c)
	} else {
		out = name + typeParams(kind, c)
	}
	if array {
		// The parameters describe the ELEMENT - character varying(255)[]
		// really is an array of 255-character strings - so the brackets go
		// outside them.
		out += "[]"
	}
	return out
}

// pgInfixTimePrecision writes a precision into a spelled-out date or time type,
// after its first word: TIMESTAMP WITH TIME ZONE with a precision of 3 becomes
// TIMESTAMP(3) WITH TIME ZONE. Appending it instead would be a syntax error,
// and rewriting the name to TIMESTAMPTZ(3) is the rewrite choice 5 forbids.
//
// A type this shape always has a second word, but the split is written so that
// a name without one still renders as itself.
func pgInfixTimePrecision(name string, c *model.Column) string {
	if c.Precision == nil {
		return name
	}
	first, rest, found := strings.Cut(name, " ")
	if !found {
		return name + "(" + strconv.Itoa(*c.Precision) + ")"
	}
	return first + "(" + strconv.Itoa(*c.Precision) + ") " + rest
}

// ---------------------------------------------------------------------------
// Preconditions
// ---------------------------------------------------------------------------

// pgCheck reports the preconditions that are statements about PostgreSQL
// rather than about the document, in document order.
//
// It returns only its own findings and never calls check.Document: Check owns
// that call and concatenates, which is what keeps the two groups
// un-interleaved and what makes precheck_test.go's
// TestCheckPassesThroughInternalCheck a statement about the contract rather
// than about this walk.
func pgCheck(doc *model.Document) []check.Finding {
	var findings []check.Finding

	// claimed maps a name in the schema-wide namespace to a description of
	// whatever claimed it first, so that a collision can say what it collided
	// with. The map is only ever LOOKED UP and assigned, NEVER ranged over:
	// ranging would make the order of the findings depend on Go's map
	// iteration and destroy the determinism the goldens and the CLI output
	// rest on. The order comes from the slice walk below and from nowhere
	// else.
	claimed := make(map[string]string, len(doc.Tables))
	// reported remembers the names already reported, for the same reason
	// internal/check's usedNames does: three tables sharing an index name is
	// one mistake to fix, not two findings.
	reported := make(map[string]bool)

	// claim records name as taken by owner. It returns what already held the
	// name and whether this collision is worth reporting: a name already
	// reported once is not reported again, for the reason internal/check's
	// usedNames gives - three tables sharing an index name is one mistake to
	// fix, not two findings.
	claim := func(name, owner string) (prior string, collides bool) {
		if name == "" {
			// The schema makes primaryKey.name and uniqueKeys[].name
			// optional, so several unnamed constraints in one document are
			// ordinary rather than a collision. tables[].name and
			// indexes[].name are required, but the model can still hold ""
			// for a document that was never validated, and this function has
			// to stay total over those.
			return "", false
		}
		prior, taken := claimed[name]
		if !taken {
			claimed[name] = owner
			return "", false
		}
		if reported[name] {
			return "", false
		}
		reported[name] = true
		return prior, true
	}

	// namespaceRule is the clause every P1 finding ends with. It names
	// PostgreSQL outright, which is what lets these findings share one list
	// and one prefix with internal/check's without confusing a reader who then
	// runs "jjf validate" and is told the document is fine.
	const namespaceRule = "; PostgreSQL puts tables, indexes and the indexes behind PRIMARY KEY and UNIQUE in one namespace per schema"

	for i := range doc.Tables {
		t := &doc.Tables[i]
		label := tableLabel(t.Name)

		// P1 - a table name is in the namespace too. internal/check
		// deliberately does not report duplicate table names, so without this
		// a document naming two tables "orders" would emit CREATE TABLE twice
		// and PostgreSQL would reject the script.
		if prior, collides := claim(t.Name, "table "+t.Name); collides {
			// Two tables of one name is the collision a reader will hit most
			// often and it deserves to be said plainly; anything else that
			// took the name is named instead.
			if prior == "table "+t.Name {
				findings = append(findings, check.Finding{
					Where:   label,
					Message: fmt.Sprintf("is the second table this document calls %q; PostgreSQL cannot create two tables of one name in a schema", t.Name),
				})
			} else {
				findings = append(findings, check.Finding{
					Where:   label,
					Message: fmt.Sprintf("is called %q, a name already used by %s%s", t.Name, prior, namespaceRule),
				})
			}
		}

		for j := range t.Columns {
			c := &t.Columns[j]
			if !c.AutoIncrement {
				continue
			}
			// P2 - PostgreSQL refuses "both default and identity specified
			// for column". autoIncrement renders as GENERATED BY DEFAULT AS
			// IDENTITY and default renders verbatim, so a column carrying
			// both would emit a statement the database rejects.
			if c.Default != nil {
				findings = append(findings, check.Finding{
					Where:   columnLabel(c.Name, t.Name),
					Message: "is autoIncrement and also declares a default; PostgreSQL refuses a column that is both an identity column and has a DEFAULT",
				})
				// At most one finding comes out per column, the rule
				// internal/check's checkColumnDefault already follows: one
				// authoring mistake, one finding.
				continue
			}
			// P3 - the silent case. PostgreSQL accepts a nullable identity
			// column and makes it NOT NULL anyway, so the database and the
			// document would disagree without anything saying so. That is
			// C5's argument exactly; C5 only reaches the column when it is
			// also part of the primary key.
			if c.Nullable {
				findings = append(findings, check.Finding{
					Where:   columnLabel(c.Name, t.Name),
					Message: "is autoIncrement and declared nullable; PostgreSQL makes an identity column NOT NULL, so the database would not match the document",
				})
			}
		}

		// The rest of P1, in the order a reader meets the objects in the JSON.
		// Foreign keys are skipped entirely: their names live in pg_constraint,
		// which is unique per TABLE, so two tables may each carry a foreign key
		// called fk_parent and PostgreSQL accepts both. internal/check's C6
		// already covers the per-table case.
		if pk := t.PrimaryKey; pk != nil {
			if prior, collides := claim(pk.Name, "primary key "+pk.Name+" on table "+t.Name); collides {
				findings = append(findings, check.Finding{
					Where:   label,
					Message: fmt.Sprintf("declares primary key %q, a name already used by %s%s", pk.Name, prior, namespaceRule),
				})
			}
		}
		for _, uk := range t.UniqueKeys {
			if prior, collides := claim(uk.Name, "unique key "+uk.Name+" on table "+t.Name); collides {
				findings = append(findings, check.Finding{
					Where:   label,
					Message: fmt.Sprintf("declares unique key %q, a name already used by %s%s", uk.Name, prior, namespaceRule),
				})
			}
		}
		for _, ix := range t.Indexes {
			if prior, collides := claim(ix.Name, "index "+ix.Name+" on table "+t.Name); collides {
				findings = append(findings, check.Finding{
					Where:   label,
					Message: fmt.Sprintf("declares index %q, a name already used by %s%s", ix.Name, prior, namespaceRule),
				})
			}
		}
	}
	return findings
}
