package dot

import (
	"bufio"
	"fmt"
	"io"

	"github.com/shutx-net/jumping-json-flush/internal/exitcode"
	"github.com/shutx-net/jumping-json-flush/internal/export/erd"
	"github.com/shutx-net/jumping-json-flush/internal/model"
)

// columnCells is the number of cells in one column row of a table label. The
// header cell spans exactly this many, so the two must move together if a
// fifth cell is ever added.
const columnCells = 4

// Export renders doc and writes it to dst as Graphviz DOT source.
//
// The statement order is fixed: the header, one node per table in document
// order, the stub nodes for undefined foreign key targets, then one edge per
// foreign key. Nothing below this function returns an error. They all write
// into the bufio.Writer, which latches its first write error and turns every
// later write into a no-op, so Flush is the single place a failure can
// surface. Threading an error through every writer, or wrapping dst in a
// sticky-error type, would add code and a type for no extra information.
func Export(dst io.Writer, doc *model.Document) error {
	bw := bufio.NewWriter(dst)
	writeGraph(bw, doc)
	if err := bw.Flush(); err != nil {
		return exitcode.Wrap(exitcode.OutputFailed, "write graph", err)
	}
	return nil
}

// ---------------------------------------------------------------------------
// Graph skeleton
// ---------------------------------------------------------------------------

// writeGraph emits the whole digraph.
//
// The header carries no timestamp, no tool version and no input path. A
// version would make two builds of jjf disagree about the same document - the
// same reason the workbook records the bare creator "jjf" - and a path would
// make the output depend on where the input happened to sit.
func writeGraph(w *bufio.Writer, doc *model.Document) {
	io.WriteString(w, "// Generated by jjf from a database design document.\n")
	io.WriteString(w, "// The JSON is the source of truth: edit it and export again, never this file.\n")
	fmt.Fprintf(w, "digraph %s {\n", quoteID(doc.Database.Name))

	// charset is set explicitly so that a Japanese logical name is read as
	// UTF-8 whatever the reader's locale says. shape=plaintext is required by
	// the HTML-like labels below, which draw their own box.
	io.WriteString(w, "\tgraph [charset=\"UTF-8\", rankdir=LR];\n")
	io.WriteString(w, "\tnode [shape=plaintext];\n")
	// dir=both is the single most load-bearing attribute in the file: without
	// it graphviz draws the head arrow alone and silently discards the crow's
	// foot on the tail, which is exactly the end the cardinality is on.
	io.WriteString(w, "\tedge [dir=both];\n")
	io.WriteString(w, "\n")

	for i := range doc.Tables {
		writeTableNode(w, &doc.Tables[i])
	}

	if stubs := erd.UndefinedTargets(doc); len(stubs) > 0 {
		io.WriteString(w, "\n\t// referenced by a foreign key but not defined in this document\n")
		for _, name := range stubs {
			writeStubNode(w, name)
		}
	}

	if hasForeignKeys(doc) {
		io.WriteString(w, "\n")
		writeEdges(w, doc)
	}

	io.WriteString(w, "}\n")
}

// hasForeignKeys reports whether any table declares a foreign key, which is
// what decides whether the edge section exists at all. A document without one
// must still produce a syntactically complete digraph, with no dangling blank
// line before the closing brace.
func hasForeignKeys(doc *model.Document) bool {
	for i := range doc.Tables {
		if len(doc.Tables[i].ForeignKeys) > 0 {
			return true
		}
	}
	return false
}

// ---------------------------------------------------------------------------
// Nodes
// ---------------------------------------------------------------------------

// writeTableNode emits one table as a node whose label is an HTML-like table:
// a header carrying the logical and physical names, then one row per column
// with its key marker, physical name, logical name and rendered type.
//
// The attribute list holds label and nothing else. Colour, font and size stay
// out: they are layout knobs the reader can pass to dot, and jjf owns the
// layout with no knobs at all, exactly as it does for the workbook.
//
// Every piece of document text goes through escapeHTML, including the physical
// name and the type, which cannot need it under the schema's patterns.
// Escaping uniformly means no reviewer has to work out which of them can.
func writeTableNode(w *bufio.Writer, t *model.Table) {
	fmt.Fprintf(w, "\t%s [label=<<TABLE BORDER=\"0\" CELLBORDER=\"1\" CELLSPACING=\"0\" CELLPADDING=\"4\">\n",
		quoteID(t.Name))
	fmt.Fprintf(w, "\t\t<TR><TD COLSPAN=\"%d\" BGCOLOR=\"#e8e8e8\"><B>%s</B><BR/>%s</TD></TR>\n",
		columnCells, escapeHTML(t.LogicalName), escapeHTML(t.Name))

	for i := range t.Columns {
		c := &t.Columns[i]
		// The marker cell is left at the default alignment: it holds a mark of
		// at most five characters and reads better centred.
		fmt.Fprintf(w, "\t\t<TR><TD>%s</TD><TD ALIGN=\"LEFT\">%s</TD><TD ALIGN=\"LEFT\">%s</TD><TD ALIGN=\"LEFT\">%s</TD></TR>\n",
			erd.Marker(t, c.Name), escapeHTML(c.Name), escapeHTML(c.LogicalName), escapeHTML(erd.RenderType(c)))
	}

	io.WriteString(w, "\t</TABLE>>];\n")
}

// writeStubNode emits a placeholder for a table a foreign key names but the
// document does not define.
//
// shape=box with style=dashed is what makes it VISIBLY different: the real
// tables are shape=plaintext carrying a drawn HTML table, so a dashed grey box
// cannot be mistaken for one. The local shape overrides the graph-level
// default, which is why that default is harmless here.
//
// The stub invents nothing - no columns, no keys, no types - so the diagram
// shows exactly what the JSON claims: that something points at a table this
// document does not describe.
//
// The \n in the label is the two characters backslash and n, a DOT string
// escape that graphviz renders as a line break. It must NOT become a real
// newline byte: that would still parse, but it would break the
// one-statement-per-line shape the golden files depend on.
func writeStubNode(w *bufio.Writer, name string) {
	fmt.Fprintf(w, "\t%s [shape=box, style=dashed, color=\"#999999\", fontcolor=\"#999999\", label=\"%s\\n(not defined in this document)\"];\n",
		quoteID(name), escapeString(name))
}

// ---------------------------------------------------------------------------
// Edges
// ---------------------------------------------------------------------------

// writeEdges emits one edge per foreign key, walking the tables in document
// order and each table's foreign keys in document order.
//
// One statement per foreign key: a composite foreign key is ONE relationship
// and gets one edge, never one per column pair. Two foreign keys between the
// same pair of tables produce two statements, which graphviz draws as two
// parallel edges, told apart by their labels. A self-referencing foreign key
// produces an edge whose endpoints are equal and is special-cased nowhere.
func writeEdges(w *bufio.Writer, doc *model.Document) {
	for i := range doc.Tables {
		t := &doc.Tables[i]
		for j := range t.ForeignKeys {
			fk := &t.ForeignKeys[j]
			// The tail is the child, the table that declares the foreign key;
			// the head is the table it references. The attribute order is
			// fixed rather than alphabetical - which would put label first and
			// read worse - and any order does as long as it never changes.
			fmt.Fprintf(w, "\t%s -> %s [arrowtail=%s, arrowhead=%s, label=%s];\n",
				quoteID(t.Name), quoteID(fk.References.Table),
				arrow(erd.ChildEnd(t, fk)), arrow(erd.ParentEnd(t, fk)), quoteID(erd.EdgeLabel(fk)))
		}
	}
}
