package dot

import (
	"bytes"
	"errors"
	"strings"
	"testing"
	"unicode/utf8"

	"github.com/shutx-net/jumping-json-flush/internal/exitcode"
	"github.com/shutx-net/jumping-json-flush/internal/model"
)

// ---------------------------------------------------------------------------
// Rendering helpers
// ---------------------------------------------------------------------------

// render exports doc and returns the DOT source. The documents in this file
// are Go literals rather than fixtures: what is under test is the shape of the
// output for one document shape at a time, and a literal keeps the shape and
// the assertion next to each other. The JSON fixtures render whole documents.
func render(t *testing.T, doc *model.Document) string {
	t.Helper()
	var buf bytes.Buffer
	if err := Export(&buf, doc); err != nil {
		t.Fatalf("Export: %v", err)
	}
	return buf.String()
}

// docOf wraps tables in a minimal document called shop.
func docOf(tables ...model.Table) *model.Document {
	return &model.Document{
		FormatVersion: model.CurrentFormatVersion,
		Database:      model.Database{Name: "shop"},
		Tables:        tables,
	}
}

// wantLine fails unless out holds line as a whole line.
func wantLine(t *testing.T, out, line string) {
	t.Helper()
	for _, got := range strings.Split(out, "\n") {
		if got == line {
			return
		}
	}
	t.Errorf("the output has no line\n\t%s\ngot:\n%s", line, out)
}

// wantNoLine fails when out holds line as a whole line.
func wantNoLine(t *testing.T, out, line string) {
	t.Helper()
	for _, got := range strings.Split(out, "\n") {
		if got == line {
			t.Errorf("the output has the unwanted line\n\t%s\ngot:\n%s", line, out)
			return
		}
	}
}

// customers is a table with a primary key and no foreign key.
func customers() model.Table {
	return model.Table{
		Name:        "customers",
		LogicalName: "顧客",
		Columns: []model.Column{
			{Name: "id", LogicalName: "顧客ID", Type: "BIGINT"},
			{Name: "email", LogicalName: "メールアドレス", Type: "VARCHAR", Length: ptr(255)},
		},
		PrimaryKey: &model.PrimaryKey{Name: "pk_customers", Columns: []string{"id"}},
	}
}

// orders is a child of customers through one single-column foreign key.
func orders() model.Table {
	return model.Table{
		Name:        "orders",
		LogicalName: "受注",
		Columns: []model.Column{
			{Name: "id", LogicalName: "受注ID", Type: "BIGINT"},
			{Name: "customer_id", LogicalName: "顧客ID", Type: "BIGINT"},
		},
		PrimaryKey: &model.PrimaryKey{Name: "pk_orders", Columns: []string{"id"}},
		ForeignKeys: []model.ForeignKey{{
			Name:       "fk_orders_customer",
			Columns:    []string{"customer_id"},
			References: model.Reference{Table: "customers", Columns: []string{"id"}},
		}},
	}
}

// ---------------------------------------------------------------------------
// Graph skeleton
// ---------------------------------------------------------------------------

func TestExportHeader(t *testing.T) {
	out := render(t, docOf(customers()))
	lines := strings.Split(out, "\n")

	want := []string{
		"// Generated by jjf from a database design document.",
		"// The JSON is the source of truth: edit it and export again, never this file.",
		`digraph "shop" {`,
		"\tgraph [charset=\"UTF-8\", rankdir=LR];",
		"\tnode [shape=plaintext];",
		// Without dir=both graphviz draws the head arrow alone and drops the
		// crow's foot on the tail, which is the end the cardinality is on.
		"\tedge [dir=both];",
		"",
	}
	for i, line := range want {
		if i >= len(lines) {
			t.Fatalf("the output has only %d lines, want at least %d", len(lines), len(want))
		}
		if lines[i] != line {
			t.Errorf("line %d = %q, want %q", i+1, lines[i], line)
		}
	}

	// Exactly one newline after the closing brace, and no blank line before it.
	if !strings.HasSuffix(out, "}\n") || strings.HasSuffix(out, "\n\n}\n") {
		t.Errorf("the output does not end with a single closing brace line:\n%q", out[max(0, len(out)-40):])
	}

	// Nothing that would make two runs, or two builds, disagree.
	for _, unwanted := range []string{"jjf version", ".json", "20"} {
		if strings.Contains(strings.SplitN(out, "digraph", 2)[0], unwanted) {
			t.Errorf("the header mentions %q, which would break determinism:\n%s", unwanted, out)
		}
	}
}

func TestExportNodePerTable(t *testing.T) {
	doc := docOf(customers(), orders())
	out := render(t, doc)

	for _, name := range []string{"customers", "orders"} {
		wantLine(t, out, "\t\""+name+"\" [label=<<TABLE BORDER=\"0\" CELLBORDER=\"1\" CELLSPACING=\"0\" CELLPADDING=\"4\">")
	}
	// In document order.
	if first, second := strings.Index(out, `"customers" [label`), strings.Index(out, `"orders" [label`); first > second {
		t.Errorf("the nodes are not in document order:\n%s", out)
	}
	if got, want := strings.Count(out, "[label=<<TABLE"), len(doc.Tables); got != want {
		t.Errorf("the output has %d table nodes, want %d", got, want)
	}
}

// TestExportQuotesReservedNames covers the reason quoteID never omits its
// quotes: every one of these names is a DOT keyword and a legal table name.
func TestExportQuotesReservedNames(t *testing.T) {
	var tables []model.Table
	for _, name := range []string{"graph", "node", "edge", "subgraph", "strict", "digraph"} {
		tables = append(tables, model.Table{
			Name:        name,
			LogicalName: name,
			Columns:     []model.Column{{Name: "id", LogicalName: "id", Type: "BIGINT"}},
			PrimaryKey:  &model.PrimaryKey{Columns: []string{"id"}},
		})
	}
	// An edge between two of them, so both endpoints are keywords too.
	tables[1].Columns = append(tables[1].Columns, model.Column{Name: "graph_id", LogicalName: "graph_id", Type: "BIGINT"})
	tables[1].ForeignKeys = []model.ForeignKey{{
		Name:       "fk_node_graph",
		Columns:    []string{"graph_id"},
		References: model.Reference{Table: "graph", Columns: []string{"id"}},
	}}

	out := render(t, docOf(tables...))

	for _, name := range []string{"graph", "node", "edge", "subgraph", "strict", "digraph"} {
		wantLine(t, out, "\t\""+name+"\" [label=<<TABLE BORDER=\"0\" CELLBORDER=\"1\" CELLSPACING=\"0\" CELLPADDING=\"4\">")
	}
	wantLine(t, out, "\t\"node\" -> \"graph\" [arrowtail=crowodot, arrowhead=teetee, label=\"fk_node_graph\"];")
	// The quoted node statement cannot be confused with the graph attribute
	// statement a few lines above it.
	wantLine(t, out, "\tgraph [charset=\"UTF-8\", rankdir=LR];")
}

// ---------------------------------------------------------------------------
// Table labels
// ---------------------------------------------------------------------------

func TestExportEscapesLabelText(t *testing.T) {
	// Only a logicalName or a description can carry these characters:
	// $defs/identifier and $defs/columnType forbid them.
	tbl := model.Table{
		Name:        "quotes",
		LogicalName: `A & B <c> "d"`,
		Columns: []model.Column{
			{Name: "id", LogicalName: `x < y & z`, Type: "BIGINT"},
		},
	}
	out := render(t, docOf(tbl))

	wantLine(t, out, "\t\t<TR><TD COLSPAN=\"4\" BGCOLOR=\"#e8e8e8\"><B>A &amp; B &lt;c&gt; &quot;d&quot;</B><BR/>quotes</TD></TR>")
	if strings.Contains(out, `<c>`) || strings.Contains(out, `x < y`) {
		t.Errorf("raw markup reached the label:\n%s", out)
	}
}

func TestExportJapanesePassesThrough(t *testing.T) {
	out := render(t, docOf(customers()))

	if !utf8.ValidString(out) {
		t.Error("the output is not valid UTF-8")
	}
	for _, want := range []string{"顧客", "メールアドレス", `charset="UTF-8"`} {
		if !strings.Contains(out, want) {
			t.Errorf("the output does not contain %q:\n%s", want, out)
		}
	}
}

func TestExportKeyMarkers(t *testing.T) {
	// order_lines: order_id is both a primary key and a foreign key column,
	// line_no is a primary key column alone, product_code a foreign key column
	// alone, and note neither.
	tbl := model.Table{
		Name:        "order_lines",
		LogicalName: "受注明細",
		Columns: []model.Column{
			{Name: "order_id", LogicalName: "受注ID", Type: "BIGINT"},
			{Name: "line_no", LogicalName: "行番号", Type: "SMALLINT"},
			{Name: "product_code", LogicalName: "商品コード", Type: "VARCHAR", Length: ptr(20)},
			{Name: "note", LogicalName: "備考", Type: "TEXT", Nullable: true},
		},
		PrimaryKey: &model.PrimaryKey{Columns: []string{"order_id", "line_no"}},
		ForeignKeys: []model.ForeignKey{
			{Name: "fk_order_lines_order", Columns: []string{"order_id"},
				References: model.Reference{Table: "orders", Columns: []string{"id"}}},
			{Name: "fk_order_lines_product", Columns: []string{"product_code"},
				References: model.Reference{Table: "products", Columns: []string{"code"}}},
		},
	}
	out := render(t, docOf(tbl))

	tests := []struct {
		name   string
		marker string
		column string
		typ    string
	}{
		{"a primary and foreign key column", "PK,FK", "order_id", "BIGINT"},
		{"a primary key column", "PK", "line_no", "SMALLINT"},
		{"a foreign key column", "FK", "product_code", "VARCHAR(20)"},
		{"a plain column", "", "note", "TEXT"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			wantLine(t, out, "\t\t<TR><TD>"+tt.marker+"</TD><TD ALIGN=\"LEFT\">"+tt.column+
				"</TD><TD ALIGN=\"LEFT\">"+escapeHTML(columnLogicalName(&tbl, tt.column))+
				"</TD><TD ALIGN=\"LEFT\">"+tt.typ+"</TD></TR>")
		})
	}
}

// columnLogicalName is a test-side lookup, kept out of the exporter because
// the exporter walks the columns it is printing rather than searching for one.
// It walks the slice itself rather than borrowing internal/export/erd's
// findColumn, which is unexported there and is a piece of the cardinality
// derivation rather than a lookup this package is entitled to.
func columnLogicalName(t *model.Table, column string) string {
	for i := range t.Columns {
		if t.Columns[i].Name == column {
			return t.Columns[i].LogicalName
		}
	}
	return ""
}

func TestExportTableWithoutPrimaryKey(t *testing.T) {
	tbl := model.Table{
		Name:        "audit_log",
		LogicalName: "監査ログ",
		Columns:     []model.Column{{Name: "message", LogicalName: "内容", Type: "TEXT"}},
	}
	out := render(t, docOf(tbl))

	if strings.Contains(out, "<TD>PK</TD>") {
		t.Errorf("a table without a primary key has a PK marker:\n%s", out)
	}
	wantLine(t, out, "\t\t<TR><TD></TD><TD ALIGN=\"LEFT\">message</TD><TD ALIGN=\"LEFT\">内容</TD><TD ALIGN=\"LEFT\">TEXT</TD></TR>")
}

func TestExportColumnTypes(t *testing.T) {
	tbl := model.Table{
		Name:        "types",
		LogicalName: "型",
		Columns: []model.Column{
			{Name: "amount", LogicalName: "金額", Type: "NUMERIC", Precision: ptr(10), Scale: ptr(2)},
			{Name: "ratio", LogicalName: "率", Type: "NUMERIC", Precision: ptr(8)},
			{Name: "created_at", LogicalName: "作成日時", Type: "TIMESTAMP WITH TIME ZONE"},
		},
	}
	out := render(t, docOf(tbl))

	for _, want := range []string{"NUMERIC(10,2)", "NUMERIC(8)", "TIMESTAMP WITH TIME ZONE"} {
		if !strings.Contains(out, ">"+want+"</TD>") {
			t.Errorf("the output has no type cell %q:\n%s", want, out)
		}
	}
}

// ---------------------------------------------------------------------------
// Edges
// ---------------------------------------------------------------------------

func TestExportEdgePerForeignKey(t *testing.T) {
	out := render(t, docOf(customers(), orders()))

	// customer_id is neither the primary key nor unique, so the child side is
	// many, and every child side is optional. It is NOT NULL, so the parent
	// side is one and mandatory.
	wantLine(t, out, "\t\"orders\" -> \"customers\" [arrowtail=crowodot, arrowhead=teetee, label=\"fk_orders_customer\"];")
	if got := strings.Count(out, " -> "); got != 1 {
		t.Errorf("the output has %d edges, want 1:\n%s", got, out)
	}
}

func TestExportEdgeLabelFallsBackToColumns(t *testing.T) {
	child := orders()
	child.ForeignKeys[0].Name = ""
	child.ForeignKeys[0].Columns = []string{"customer_id"}
	out := render(t, docOf(customers(), child))

	// A constraint name is optional, so the child column list stands in.
	wantLine(t, out, "\t\"orders\" -> \"customers\" [arrowtail=crowodot, arrowhead=teetee, label=\"customer_id\"];")
}

func TestExportCompositeForeignKeyIsOneEdge(t *testing.T) {
	parent := model.Table{
		Name: "order_lines", LogicalName: "受注明細",
		Columns: []model.Column{
			{Name: "order_id", LogicalName: "受注ID", Type: "BIGINT"},
			{Name: "line_no", LogicalName: "行番号", Type: "SMALLINT"},
		},
		PrimaryKey: &model.PrimaryKey{Columns: []string{"order_id", "line_no"}},
	}
	child := model.Table{
		Name: "shipment_lines", LogicalName: "出荷明細",
		Columns: []model.Column{
			{Name: "order_id", LogicalName: "受注ID", Type: "BIGINT"},
			{Name: "line_no", LogicalName: "行番号", Type: "SMALLINT"},
		},
		PrimaryKey: &model.PrimaryKey{Columns: []string{"order_id", "line_no"}},
		ForeignKeys: []model.ForeignKey{{
			Name:    "fk_shipment_lines_line",
			Columns: []string{"order_id", "line_no"},
			References: model.Reference{
				Table: "order_lines", Columns: []string{"order_id", "line_no"},
			},
		}},
	}
	out := render(t, docOf(parent, child))

	if got := strings.Count(out, " -> "); got != 1 {
		t.Errorf("a composite foreign key produced %d edges, want 1:\n%s", got, out)
	}
	// The foreign key columns are the whole primary key, so the child side is
	// one - a 1:1 relationship - and optional, as every child side is. Both
	// columns are NOT NULL, so the parent side is mandatory.
	wantLine(t, out, "\t\"shipment_lines\" -> \"order_lines\" [arrowtail=teeodot, arrowhead=teetee, label=\"fk_shipment_lines_line\"];")
}

func TestExportTwoForeignKeysBetweenOnePair(t *testing.T) {
	parent := customers()
	child := model.Table{
		Name: "transfers", LogicalName: "振替",
		Columns: []model.Column{
			{Name: "from_id", LogicalName: "振替元", Type: "BIGINT"},
			{Name: "to_id", LogicalName: "振替先", Type: "BIGINT", Nullable: true},
		},
		ForeignKeys: []model.ForeignKey{
			{Name: "fk_transfers_from", Columns: []string{"from_id"},
				References: model.Reference{Table: "customers", Columns: []string{"id"}}},
			{Name: "fk_transfers_to", Columns: []string{"to_id"},
				References: model.Reference{Table: "customers", Columns: []string{"id"}}},
		},
	}
	out := render(t, docOf(parent, child))

	if got := strings.Count(out, " -> "); got != 2 {
		t.Errorf("the output has %d edges, want 2:\n%s", got, out)
	}
	// Same endpoints, different labels. The nullable to_id makes the PARENT
	// end of the second relationship optional: what a NULL there says is that
	// this row may point at no customer at all.
	wantLine(t, out, "\t\"transfers\" -> \"customers\" [arrowtail=crowodot, arrowhead=teetee, label=\"fk_transfers_from\"];")
	wantLine(t, out, "\t\"transfers\" -> \"customers\" [arrowtail=crowodot, arrowhead=teeodot, label=\"fk_transfers_to\"];")
}

func TestExportSelfReference(t *testing.T) {
	tbl := model.Table{
		Name: "employees", LogicalName: "社員",
		Columns: []model.Column{
			{Name: "id", LogicalName: "社員ID", Type: "BIGINT"},
			{Name: "manager_id", LogicalName: "上長", Type: "BIGINT", Nullable: true},
		},
		PrimaryKey: &model.PrimaryKey{Columns: []string{"id"}},
		ForeignKeys: []model.ForeignKey{{
			Name: "fk_employees_manager", Columns: []string{"manager_id"},
			References: model.Reference{Table: "employees", Columns: []string{"id"}},
		}},
	}
	out := render(t, docOf(tbl))

	wantLine(t, out, "\t\"employees\" -> \"employees\" [arrowtail=crowodot, arrowhead=teeodot, label=\"fk_employees_manager\"];")
	// The target is defined, so nothing is stubbed.
	wantNoLine(t, out, "\t// referenced by a foreign key but not defined in this document")
}

// ---------------------------------------------------------------------------
// Undefined foreign key targets
// ---------------------------------------------------------------------------

// TestExportStubNodeForUndefinedTarget covers a legal document: the schema
// deliberately does not check that a foreign key's target exists. The edge is
// not dropped and the export does not fail; the diagram shows exactly what the
// JSON claims. "jjf validate" warns about the same document - the exporter
// never does.
func TestExportStubNodeForUndefinedTarget(t *testing.T) {
	first := model.Table{
		Name: "orders", LogicalName: "受注",
		Columns: []model.Column{{Name: "shipment_id", LogicalName: "出荷ID", Type: "BIGINT"}},
		ForeignKeys: []model.ForeignKey{{
			Name: "fk_orders_shipment", Columns: []string{"shipment_id"},
			References: model.Reference{Table: "shipments", Columns: []string{"id"}},
		}},
	}
	// A second reference to the same undefined table, from another table.
	second := model.Table{
		Name: "returns", LogicalName: "返品",
		Columns: []model.Column{{Name: "shipment_id", LogicalName: "出荷ID", Type: "BIGINT"}},
		ForeignKeys: []model.ForeignKey{{
			Name: "fk_returns_shipment", Columns: []string{"shipment_id"},
			References: model.Reference{Table: "shipments", Columns: []string{"id"}},
		}},
	}
	out := render(t, docOf(first, second))

	wantLine(t, out, "\t// referenced by a foreign key but not defined in this document")
	// The \n in the label is the two characters backslash and n, a DOT escape,
	// not a newline byte: a newline would break the one-statement-per-line
	// shape the golden files depend on.
	wantLine(t, out, `	"shipments" [shape=box, style=dashed, color="#999999", fontcolor="#999999", label="shipments\n(not defined in this document)"];`)

	if got := strings.Count(out, "shape=box"); got != 1 {
		t.Errorf("the same undefined target produced %d stubs, want 1:\n%s", got, out)
	}
	if got := strings.Count(out, " -> "); got != 2 {
		t.Errorf("the output has %d edges, want 2:\n%s", got, out)
	}
}

// TestExportUndefinedTargetsAreCaseSensitive pins that jjf folds identifier
// case nowhere: a reference to Orders in a document defining orders is an
// undefined target.
func TestExportUndefinedTargetsAreCaseSensitive(t *testing.T) {
	child := orders()
	child.ForeignKeys[0].References.Table = "Customers"
	out := render(t, docOf(customers(), child))

	wantLine(t, out, `	"Customers" [shape=box, style=dashed, color="#999999", fontcolor="#999999", label="Customers\n(not defined in this document)"];`)
}

func TestExportWithoutForeignKeys(t *testing.T) {
	out := render(t, docOf(customers()))

	if strings.Contains(out, " -> ") {
		t.Errorf("a document without foreign keys produced an edge:\n%s", out)
	}
	wantNoLine(t, out, "\t// referenced by a foreign key but not defined in this document")

	// No dangling blank line: the closing brace follows the last node.
	lines := strings.Split(strings.TrimSuffix(out, "\n"), "\n")
	if got, want := lines[len(lines)-2], "\t</TABLE>>];"; got != want {
		t.Errorf("the line before the closing brace = %q, want %q", got, want)
	}
}

// ---------------------------------------------------------------------------
// Exporter level behaviour
// ---------------------------------------------------------------------------

// TestExportDeterminism renders the same document twice. Unlike the workbook
// there are no time zone sub-tests: nothing here touches the clock, and the
// only maps in the package are looked up rather than ranged over.
func TestExportDeterminism(t *testing.T) {
	doc := docOf(customers(), orders())

	first := render(t, doc)
	for i := range 8 {
		if got := render(t, doc); got != first {
			t.Fatalf("render %d differs from the first:\n--- got ---\n%s\n--- want ---\n%s", i+2, got, first)
		}
	}
}

// errWriter fails every write, standing in for a full disk or a closed pipe.
type errWriter struct{ err error }

func (w errWriter) Write([]byte) (int, error) { return 0, w.err }

func TestExportWriteError(t *testing.T) {
	boom := errors.New("boom")
	err := Export(errWriter{err: boom}, docOf(customers(), orders()))

	if err == nil {
		t.Fatal("Export to a failing writer returned no error")
	}
	if !errors.Is(err, boom) {
		t.Errorf("Export error = %v, want it to wrap %v", err, boom)
	}
	if got, want := exitcode.Of(err), exitcode.OutputFailed; got != want {
		t.Errorf("exitcode.Of(err) = %d, want %d", got, want)
	}
}
