package dot

import (
	"encoding/xml"
	"errors"
	"flag"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"unicode/utf8"

	"github.com/shutx-net/jumping-json-flush/internal/model"
	"github.com/shutx-net/jumping-json-flush/internal/schema"
)

var update = flag.Bool("update", false, "update golden files")

// fixtures are the documents whose rendering is frozen. Between them they hold
// every shape the exporter has to survive: full.json is the ordinary document,
// edge.json the awkward ones, nofk.json the minimal output.
var fixtures = []string{"full.json", "edge.json", "nofk.json"}

// ---------------------------------------------------------------------------
// Fixtures and golden files
// ---------------------------------------------------------------------------

// loadDoc reads a fixture and decodes it. The fixture is checked against the
// schema on the way through, because a fixture that no longer conforms tests
// nothing worth knowing - and it would also be a document the CLI could never
// reach this exporter with.
func loadDoc(t *testing.T, name string) *model.Document {
	t.Helper()

	path := filepath.Join("testdata", name)
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	validator, err := schema.NewValidator()
	if err != nil {
		t.Fatal(err)
	}
	if err := validator.Validate(path, raw); err != nil {
		t.Fatalf("fixture does not conform to the schema: %v", err)
	}
	doc, err := model.Decode(raw)
	if err != nil {
		t.Fatal(err)
	}
	return doc
}

// goldenName maps a fixture name to the name of its golden file.
func goldenName(fixture string) string {
	return strings.TrimSuffix(fixture, filepath.Ext(fixture)) + ".dot"
}

func checkGolden(t *testing.T, name, have string) {
	t.Helper()
	path := filepath.Join("testdata", "golden", name)
	if *update {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(have), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden (run: go test ./internal/export/dot/ -update): %v", err)
	}
	if string(want) != have {
		t.Errorf("output mismatch for %s\n--- got ---\n%s\n--- want ---\n%s", name, have, want)
	}
}

func TestGolden(t *testing.T) {
	for _, name := range fixtures {
		t.Run(name, func(t *testing.T) {
			checkGolden(t, goldenName(name), render(t, loadDoc(t, name)))
		})
	}
}

// TestFixturesAreDeterministic renders each fixture twice. There are no time
// zone sub-tests as there are for the workbook: those exist because the zip
// format records local timestamps, and nothing in this package reads the clock
// at all.
func TestFixturesAreDeterministic(t *testing.T) {
	for _, name := range fixtures {
		t.Run(name, func(t *testing.T) {
			doc := loadDoc(t, name)
			if first, second := render(t, doc), render(t, doc); first != second {
				t.Errorf("two renders of %s differ:\n--- first ---\n%s\n--- second ---\n%s", name, first, second)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// Structural well-formedness
// ---------------------------------------------------------------------------

// htmlLabels extracts the HTML-like label payload of every node statement.
//
// A naive scan is correct here because the emitter escapes every < and > that
// comes from document text, so the only unescaped angle brackets inside a
// label are tag delimiters, and a table node statement always ends with the
// literal </TABLE>>];.
func htmlLabels(src string) []string {
	const opener, closer = "label=<", ">];"

	var out []string
	for rest := src; ; {
		i := strings.Index(rest, opener)
		if i < 0 {
			return out
		}
		rest = rest[i+len(opener):]
		j := strings.Index(rest, closer)
		if j < 0 {
			return out
		}
		out = append(out, rest[:j])
		rest = rest[j+len(closer):]
	}
}

// TestFixturesRenderWellFormedLabels parses every label payload as XML.
//
// graphviz's HTML-like labels are XML shaped: <BR/> is self-closed, every
// attribute is quoted, and &amp; &lt; &gt; &quot; are the standard XML
// entities, so a payload that is not well-formed XML is certainly not a valid
// label. The check is NECESSARY but not sufficient - it knows nothing of
// graphviz's tag vocabulary - and it is as far as this can be taken without
// the dot binary, which this project deliberately does not require to build or
// to test.
func TestFixturesRenderWellFormedLabels(t *testing.T) {
	for _, name := range fixtures {
		t.Run(name, func(t *testing.T) {
			src := render(t, loadDoc(t, name))

			if !utf8.ValidString(src) {
				t.Fatal("the output is not valid UTF-8")
			}
			const header = "// Generated by jjf from a database design document.\n" +
				"// The JSON is the source of truth: edit it and export again, never this file.\n"
			if !strings.HasPrefix(src, header) {
				t.Errorf("the output does not open with the two comment lines:\n%.160s", src)
			}
			if !strings.HasSuffix(src, "}\n") {
				t.Errorf("the output does not end with a closing brace and one newline: %q", src[max(0, len(src)-20):])
			}

			labels := htmlLabels(src)
			if len(labels) != len(loadDoc(t, name).Tables) {
				t.Fatalf("found %d HTML labels, want one per table (%d)", len(labels), len(loadDoc(t, name).Tables))
			}
			for i, label := range labels {
				dec := xml.NewDecoder(strings.NewReader(label))
				for {
					_, err := dec.Token()
					if errors.Is(err, io.EOF) {
						break
					}
					if err != nil {
						t.Errorf("label %d is not well-formed XML: %v\n%s", i, err, label)
						break
					}
				}
			}
		})
	}
}

// ---------------------------------------------------------------------------
// What the edge fixture is for
// ---------------------------------------------------------------------------

// TestEdgeFixtureCoversItsCases names, one by one, the awkward cases the edge
// golden is supposed to show. A regression then reports which case broke
// rather than dumping a diff of the whole file.
func TestEdgeFixtureCoversItsCases(t *testing.T) {
	src := render(t, loadDoc(t, "edge.json"))

	tests := []struct {
		name string
		want string
	}{
		{
			"a table named after the DOT keyword graph, quoted",
			"\t\"graph\" [label=<<TABLE",
		},
		{
			"a table named after the DOT keyword edge, quoted and distinct from the edge attribute statement",
			"\t\"edge\" [label=<<TABLE",
		},
		{"the graph attribute statement is still there", "\tgraph [charset=\"UTF-8\", rankdir=LR];"},
		{"the edge attribute statement is still there", "\tedge [dir=both];"},
		{"an escaped ampersand", "&amp;"},
		{"an escaped less-than", "&lt;"},
		{"an escaped greater-than", "&gt;"},
		{"an escaped double quote", "&quot;"},
		{"a Japanese logical name", "<B>辺</B>"},
		{"a column that is both a primary and a foreign key column", "<TD>PK,FK</TD>"},
		{"a precision and scale rendered into the type", "NUMERIC(5,2)"},
		{"a precision alone rendered into the type", "NUMERIC(8)"},
		{"a length winning over a precision", "NUMERIC(10)"},
		{
			"a self-referencing foreign key as a loop edge",
			"\t\"categories\" -> \"categories\" [arrowtail=crowodot, arrowhead=teetee, label=\"fk_categories_parent\"];",
		},
		{
			"a composite foreign key equal to the composite primary key, as one 1:1 edge",
			"\t\"edge_labels\" -> \"edge\" [arrowtail=teetee, arrowhead=teetee, label=\"fk_edge_labels_edge\"];",
		},
		{
			"a foreign key made unique by an index alone, also 1:1",
			"\t\"node_stats\" -> \"nodes\" [arrowtail=teetee, arrowhead=teetee, label=\"fk_node_stats_node\"];",
		},
		{
			"an unnamed foreign key labelled with its column list",
			"\t\"edge\" -> \"nodes\" [arrowtail=crowodot, arrowhead=teetee, label=\"from_node\"];",
		},
		{
			"a second foreign key between the same pair of tables",
			"\t\"edge\" -> \"nodes\" [arrowtail=crowtee, arrowhead=teetee, label=\"fk_edge_to_node\"];",
		},
		{
			"a foreign key naming a column the table does not define, which is not optional and does not crash",
			"\t\"node_stats\" -> \"graph\" [arrowtail=crowtee, arrowhead=teetee, label=\"fk_node_stats_unknown_column\"];",
		},
		{"the section comment above the stubs", "\t// referenced by a foreign key but not defined in this document"},
		{
			"a dashed stub node whose label carries the two-character DOT escape",
			`	"nodes" [shape=box, style=dashed, color="#999999", fontcolor="#999999", label="nodes\n(not defined in this document)"];`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if !strings.Contains(src, tt.want) {
				t.Errorf("the rendered edge fixture does not contain\n\t%s\ngot:\n%s", tt.want, src)
			}
		})
	}

	// Three foreign keys name the same undefined table, and it gets one stub.
	if got := strings.Count(src, "shape=box"); got != 1 {
		t.Errorf("the output holds %d stub nodes, want 1:\n%s", got, src)
	}
}
