package postgres

import (
	"errors"
	"reflect"
	"slices"
	"strings"
	"testing"
)

// mustParse parses src and fails the test if the dump is not well formed. The
// warnings are returned rather than asserted, because most tests care about the
// intermediate representation alone.
func mustParse(t *testing.T, src string) (*pgDump, []Diagnostic) {
	t.Helper()
	var d diagList
	dump, err := parse([]byte(src), &d)
	if err != nil {
		t.Fatalf("parse returned error %v, want no error", err)
	}
	return dump, d.all()
}

// statementHeads lexes src and returns the first token of every statement, which
// is enough to say where the splitter cut.
func statementHeads(t *testing.T, src string) []string {
	t.Helper()
	toks, err := lex([]byte(src))
	if err != nil {
		t.Fatalf("lex(%q) returned error %v, want no error", src, err)
	}
	heads := []string{}
	for _, stmt := range splitStatements(toks) {
		heads = append(heads, stmt[0].text)
	}
	return heads
}

func TestSplitStatements(t *testing.T) {
	tests := []struct {
		name string
		src  string
		want []string
	}{
		{
			name: "two statements",
			src:  "SELECT 1; SELECT 2;",
			want: []string{"select", "select"},
		},
		{
			name: "trailing statement without a semicolon",
			src:  "SELECT 1; UPDATE t SET a = 1",
			want: []string{"select", "update"},
		},
		{
			name: "empty statements are dropped",
			src:  ";;SELECT 1;;",
			want: []string{"select"},
		},
		{
			name: "semicolon inside a dollar-quoted body",
			src: "CREATE FUNCTION f() RETURNS void AS $$\nBEGIN\n  CREATE TABLE x (a int);\nEND;\n$$ LANGUAGE plpgsql;\n" +
				"SELECT 1;",
			want: []string{"create", "select"},
		},
		{
			name: "semicolon inside a string",
			src:  "INSERT INTO t VALUES (';');\nSELECT 1;",
			want: []string{"insert", "select"},
		},
		{
			name: "semicolon inside a comment",
			src:  "-- one ; two\nSELECT 1;",
			want: []string{"select"},
		},
		{
			name: "semicolon inside parentheses",
			src:  "SELECT f(a;b); SELECT 2;",
			want: []string{"select", "select"},
		},
		{
			name: "only comments",
			src:  "-- nothing here\n/* nor here */\n",
			want: []string{},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := statementHeads(t, tt.src); !slices.Equal(got, tt.want) {
				t.Errorf("splitStatements(%q) got = %v, want %v", tt.src, got, tt.want)
			}
		})
	}
}

// createTableSource exercises every column form the importer understands at
// once, in the spelling pg_dump uses.
const createTableSource = `CREATE TABLE public.users (
    id integer NOT NULL,
    email character varying(255) NOT NULL UNIQUE,
    ratio numeric(10,2) DEFAULT 1.5,
    tags text[],
    span interval day to second(6),
    created_at timestamp(3) without time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    kind public.status DEFAULT 'a'::public.status,
    owner_id integer REFERENCES public.orgs(id) ON DELETE CASCADE,
    seq_id integer DEFAULT nextval('public.users_id_seq'::regclass),
    gen integer GENERATED ALWAYS AS (id + 1) STORED,
    ident integer GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1),
    note text DEFAULT 'a, b (c)',
    CONSTRAINT users_pkey PRIMARY KEY (id)
);`

func TestParseCreateTable(t *testing.T) {
	dump, _ := mustParse(t, createTableSource)
	if len(dump.Tables) != 1 {
		t.Fatalf("tables got = %v, want 1", len(dump.Tables))
	}
	table := dump.Tables[0]
	if table.Name.Schema != "public" || table.Name.Name != "users" {
		t.Errorf("table name got = %v, want public.users", table.Name)
	}

	tests := []struct {
		name      string
		words     string
		args      string
		dims      int
		notNull   bool
		def       string
		identity  bool
		generated bool
	}{
		{name: "id", words: "integer", notNull: true},
		{name: "email", words: "character varying", args: "255", notNull: true},
		{name: "ratio", words: "numeric", args: "10,2", def: "1.5"},
		{name: "tags", words: "text", dims: 1},
		{name: "span", words: "interval day to second", args: "6"},
		{name: "created_at", words: "timestamp without time zone", args: "3", notNull: true, def: "now()"},
		{name: "updated_at", words: "timestamp with time zone"},
		{name: "kind", words: "public.status", def: "'a'::public.status"},
		{name: "owner_id", words: "integer"},
		{name: "seq_id", words: "integer", def: "nextval('public.users_id_seq'::regclass)"},
		{name: "gen", words: "integer", generated: true},
		{name: "ident", words: "integer", identity: true},
		{name: "note", words: "text", def: "'a, b (c)'"},
	}
	if len(table.Columns) != len(tests) {
		t.Fatalf("columns got = %v, want %v", len(table.Columns), len(tests))
	}

	for i, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			col := table.Columns[i]
			if col.Name != tt.name {
				t.Fatalf("column %d name got = %v, want %v", i, col.Name, tt.name)
			}
			if got := strings.Join(col.Type.Words, " "); got != tt.words {
				t.Errorf("%s type words got = %v, want %v", tt.name, got, tt.words)
			}
			if got := strings.Join(col.Type.Args, ","); got != tt.args {
				t.Errorf("%s type args got = %v, want %v", tt.name, got, tt.args)
			}
			if col.Type.ArrayDims != tt.dims {
				t.Errorf("%s array dimensions got = %v, want %v", tt.name, col.Type.ArrayDims, tt.dims)
			}
			if col.NotNull != tt.notNull {
				t.Errorf("%s not null got = %v, want %v", tt.name, col.NotNull, tt.notNull)
			}
			if col.HasDefault != (tt.def != "") {
				t.Errorf("%s has default got = %v, want %v", tt.name, col.HasDefault, tt.def != "")
			}
			if col.Default != tt.def {
				t.Errorf("%s default got = %q, want %q", tt.name, col.Default, tt.def)
			}
			if col.Identity != tt.identity {
				t.Errorf("%s identity got = %v, want %v", tt.name, col.Identity, tt.identity)
			}
			if col.Generated != tt.generated {
				t.Errorf("%s generated got = %v, want %v", tt.name, col.Generated, tt.generated)
			}
		})
	}

	// The inline constraints arrive in source order, ahead of the one written as
	// a table element.
	wantConstraints := []struct {
		kind    constraintKind
		name    string
		columns []string
	}{
		{kind: constraintUnique, columns: []string{"email"}},
		{kind: constraintForeign, columns: []string{"owner_id"}},
		{kind: constraintPrimaryKey, name: "users_pkey", columns: []string{"id"}},
	}
	if len(table.Constraints) != len(wantConstraints) {
		t.Fatalf("constraints got = %v, want %v", len(table.Constraints), len(wantConstraints))
	}
	for i, want := range wantConstraints {
		got := table.Constraints[i]
		if got.Kind != want.kind || got.Name != want.name || !slices.Equal(got.Columns, want.columns) {
			t.Errorf("constraint %d got = %v/%v/%v, want %v/%v/%v",
				i, got.Kind, got.Name, got.Columns, want.kind, want.name, want.columns)
		}
	}
	fk := table.Constraints[1]
	if fk.RefTable.String() != "public.orgs" || !slices.Equal(fk.RefColumns, []string{"id"}) || fk.OnDelete != "CASCADE" {
		t.Errorf("inline foreign key got = %v%v on delete %q, want public.orgs[id] on delete %q",
			fk.RefTable, fk.RefColumns, fk.OnDelete, "CASCADE")
	}
}

func TestParseCreateTableSpellings(t *testing.T) {
	tests := []struct {
		name string
		src  string
	}{
		{name: "if not exists", src: "CREATE TABLE IF NOT EXISTS public.t (id integer);"},
		{name: "unlogged", src: "CREATE UNLOGGED TABLE public.t (id integer);"},
		{name: "temporary", src: "CREATE GLOBAL TEMPORARY TABLE public.t (id integer);"},
		{name: "unqualified", src: "CREATE TABLE t (id integer);"},
		{name: "quoted name with a space", src: `CREATE TABLE public."user profile" (id integer);`},
		{name: "storage options after the column list", src: "CREATE TABLE public.t (id integer) WITH (fillfactor='70') TABLESPACE ts;"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dump, warnings := mustParse(t, tt.src)
			if len(dump.Tables) != 1 {
				t.Fatalf("tables got = %v, want 1", len(dump.Tables))
			}
			if len(dump.Tables[0].Columns) != 1 {
				t.Errorf("columns got = %v, want 1", len(dump.Tables[0].Columns))
			}
			if len(warnings) != 0 {
				t.Errorf("warnings got = %v, want none", warnings)
			}
		})
	}
}

func TestParseAlterTableConstraints(t *testing.T) {
	const src = `ALTER TABLE ONLY public.t ADD CONSTRAINT t_pkey PRIMARY KEY (id);
ALTER TABLE public.t ADD CONSTRAINT t_uq UNIQUE (a, b);
ALTER TABLE ONLY public.t
    ADD CONSTRAINT t_fk FOREIGN KEY (a, b) REFERENCES public.u(x, y) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE public.t ADD PRIMARY KEY (id);
ALTER TABLE IF EXISTS ONLY public.t ADD CONSTRAINT t_fk2 FOREIGN KEY (c) REFERENCES public.u;
ALTER TABLE public.t ADD CONSTRAINT t_fk3 FOREIGN KEY (d) REFERENCES public.u(x) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE public.t ADD CONSTRAINT t_fk4 FOREIGN KEY (e) REFERENCES public.u(x) ON DELETE SET DEFAULT ON UPDATE RESTRICT;
ALTER TABLE public.t OWNER TO postgres;
ALTER TABLE ONLY public.t ALTER COLUMN id SET DEFAULT nextval('public.t_id_seq'::regclass);
ALTER TABLE public.t ALTER COLUMN a SET NOT NULL;
ALTER TABLE public.t ALTER COLUMN b DROP NOT NULL;
ALTER TABLE public.t ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (SEQUENCE NAME public.t_id_seq START WITH 1);
ALTER TABLE public.t ALTER COLUMN a SET STATISTICS 100;`

	dump, warnings := mustParse(t, src)
	if len(warnings) != 0 {
		t.Errorf("warnings got = %v, want none", warnings)
	}

	tests := []struct {
		kind             constraintKind
		name             string
		columns          []string
		refTable         string
		refColumns       []string
		onUpdate         string
		onDelete         string
		wantNoRefColumns bool
	}{
		{kind: constraintPrimaryKey, name: "t_pkey", columns: []string{"id"}},
		{kind: constraintUnique, name: "t_uq", columns: []string{"a", "b"}},
		{
			kind: constraintForeign, name: "t_fk", columns: []string{"a", "b"},
			refTable: "public.u", refColumns: []string{"x", "y"},
			onUpdate: "CASCADE", onDelete: "SET NULL",
		},
		{kind: constraintPrimaryKey, columns: []string{"id"}},
		{
			kind: constraintForeign, name: "t_fk2", columns: []string{"c"},
			refTable: "public.u", wantNoRefColumns: true,
		},
		{
			kind: constraintForeign, name: "t_fk3", columns: []string{"d"},
			refTable: "public.u", refColumns: []string{"x"},
			onUpdate: "NO ACTION", onDelete: "RESTRICT",
		},
		{
			kind: constraintForeign, name: "t_fk4", columns: []string{"e"},
			refTable: "public.u", refColumns: []string{"x"},
			onUpdate: "RESTRICT", onDelete: "SET DEFAULT",
		},
	}
	if len(dump.Constraints) != len(tests) {
		t.Fatalf("constraints got = %v, want %v", len(dump.Constraints), len(tests))
	}
	for i, tt := range tests {
		got := dump.Constraints[i]
		if got.Kind != tt.kind || got.Name != tt.name || !slices.Equal(got.Columns, tt.columns) {
			t.Errorf("constraint %d got = %v/%v/%v, want %v/%v/%v",
				i, got.Kind, got.Name, got.Columns, tt.kind, tt.name, tt.columns)
		}
		if tt.refTable != "" && got.RefTable.String() != tt.refTable {
			t.Errorf("constraint %d references got = %v, want %v", i, got.RefTable, tt.refTable)
		}
		if tt.wantNoRefColumns && got.RefColumns != nil {
			t.Errorf("constraint %d reference columns got = %v, want none", i, got.RefColumns)
		}
		if !tt.wantNoRefColumns && tt.refColumns != nil && !slices.Equal(got.RefColumns, tt.refColumns) {
			t.Errorf("constraint %d reference columns got = %v, want %v", i, got.RefColumns, tt.refColumns)
		}
		if got.OnUpdate != tt.onUpdate || got.OnDelete != tt.onDelete {
			t.Errorf("constraint %d actions got = update %q delete %q, want update %q delete %q",
				i, got.OnUpdate, got.OnDelete, tt.onUpdate, tt.onDelete)
		}
	}

	// The foreign key statement spans two lines, so every statement after it
	// sits one line further down than its position in the list.
	wantDefault := pgDefault{
		Table:  qname{Schema: "public", Name: "t", Line: 10},
		Column: "id",
		Expr:   "nextval('public.t_id_seq'::regclass)",
		Line:   10,
	}
	if len(dump.Defaults) != 1 || dump.Defaults[0] != wantDefault {
		t.Errorf("defaults got = %v, want [%v]", dump.Defaults, wantDefault)
	}
	wantNotNulls := []pgNotNull{
		{Table: qname{Schema: "public", Name: "t", Line: 11}, Column: "a", Line: 11},
		{Table: qname{Schema: "public", Name: "t", Line: 12}, Column: "b", Drop: true, Line: 12},
	}
	if !reflect.DeepEqual(dump.NotNulls, wantNotNulls) {
		t.Errorf("not nulls got = %v, want %v", dump.NotNulls, wantNotNulls)
	}
	wantIdentities := []pgIdentity{
		{Table: qname{Schema: "public", Name: "t", Line: 13}, Column: "id", Line: 13},
	}
	if !reflect.DeepEqual(dump.Identities, wantIdentities) {
		t.Errorf("identities got = %v, want %v", dump.Identities, wantIdentities)
	}
}

func TestParseCreateIndex(t *testing.T) {
	tests := []struct {
		name        string
		src         string
		wantName    string
		wantColumns []string
		wantUnique  bool
		wantMethod  string
		wantDropped bool
	}{
		{
			name:        "plain",
			src:         "CREATE INDEX t_a_idx ON public.t USING btree (a);",
			wantName:    "t_a_idx",
			wantColumns: []string{"a"},
			wantMethod:  "btree",
		},
		{
			name:        "unique and multi column",
			src:         "CREATE UNIQUE INDEX t_ab_idx ON public.t USING btree (a, b);",
			wantName:    "t_ab_idx",
			wantColumns: []string{"a", "b"},
			wantUnique:  true,
			wantMethod:  "btree",
		},
		{
			name:        "without a method",
			src:         "CREATE INDEX t_a_idx ON public.t (a);",
			wantName:    "t_a_idx",
			wantColumns: []string{"a"},
			wantMethod:  "btree",
		},
		{
			name:        "without a name",
			src:         "CREATE INDEX ON public.t USING btree (a);",
			wantColumns: []string{"a"},
			wantMethod:  "btree",
		},
		{
			name:        "concurrently and if not exists",
			src:         "CREATE INDEX CONCURRENTLY IF NOT EXISTS t_a_idx ON ONLY public.t USING btree (a);",
			wantName:    "t_a_idx",
			wantColumns: []string{"a"},
			wantMethod:  "btree",
		},
		{
			name:        "ordering options",
			src:         "CREATE INDEX t_a_idx ON public.t USING btree (a, b DESC NULLS LAST);",
			wantName:    "t_a_idx",
			wantColumns: []string{"a", "b"},
			wantMethod:  "btree",
		},
		{
			name:        "operator class",
			src:         "CREATE INDEX t_a_idx ON public.t USING btree (a varchar_pattern_ops);",
			wantName:    "t_a_idx",
			wantColumns: []string{"a"},
			wantMethod:  "btree",
		},
		{
			name:        "non-btree method",
			src:         "CREATE INDEX t_doc_idx ON public.t USING gin (doc);",
			wantName:    "t_doc_idx",
			wantColumns: []string{"doc"},
			wantMethod:  "gin",
		},
		{
			name:        "include columns",
			src:         "CREATE INDEX t_a_idx ON public.t USING btree (a) INCLUDE (b);",
			wantName:    "t_a_idx",
			wantColumns: []string{"a"},
			wantMethod:  "btree",
		},
		{
			name:        "partial",
			src:         "CREATE UNIQUE INDEX t_a_idx ON public.t USING btree (a) WHERE (deleted_at IS NULL);",
			wantName:    "t_a_idx",
			wantColumns: []string{"a"},
			wantUnique:  true,
			wantMethod:  "btree",
		},
		{
			name:        "expression index is dropped",
			src:         "CREATE INDEX t_email_idx ON public.t USING btree (lower((email)::text));",
			wantDropped: true,
		},
		{
			name:        "mixed expression index is dropped whole",
			src:         "CREATE INDEX t_mix_idx ON public.t USING btree (a, lower(b));",
			wantDropped: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dump, _ := mustParse(t, tt.src)
			if tt.wantDropped {
				if len(dump.Indexes) != 0 {
					t.Fatalf("indexes got = %v, want none", dump.Indexes)
				}
				return
			}
			if len(dump.Indexes) != 1 {
				t.Fatalf("indexes got = %v, want 1", len(dump.Indexes))
			}
			idx := dump.Indexes[0]
			if idx.Name != tt.wantName {
				t.Errorf("index name got = %v, want %v", idx.Name, tt.wantName)
			}
			if idx.Table.String() != "public.t" {
				t.Errorf("index table got = %v, want public.t", idx.Table)
			}
			if !slices.Equal(idx.Columns, tt.wantColumns) {
				t.Errorf("index columns got = %v, want %v", idx.Columns, tt.wantColumns)
			}
			if idx.Unique != tt.wantUnique {
				t.Errorf("index unique got = %v, want %v", idx.Unique, tt.wantUnique)
			}
			if idx.Method != tt.wantMethod {
				t.Errorf("index method got = %v, want %v", idx.Method, tt.wantMethod)
			}
		})
	}
}

func TestParseCommentOn(t *testing.T) {
	const src = `COMMENT ON TABLE public.users IS 'ユーザー';
COMMENT ON COLUMN public.users.email IS 'メールアドレス
連絡先として使う';
COMMENT ON COLUMN users.id IS 'identifier';
COMMENT ON TABLE public.users IS NULL;
COMMENT ON SCHEMA public IS 'standard schema';
COMMENT ON FUNCTION public.f() IS 'a function';
COMMENT ON INDEX public.users_pkey IS 'an index';`

	dump, warnings := mustParse(t, src)
	if len(warnings) != 0 {
		t.Errorf("warnings got = %v, want none", warnings)
	}
	want := []pgComment{
		{Target: commentTable, Table: qname{Schema: "public", Name: "users", Line: 1}, Text: "ユーザー", Line: 1},
		{
			Target: commentColumn, Table: qname{Schema: "public", Name: "users", Line: 2},
			Column: "email", Text: "メールアドレス\n連絡先として使う", Line: 2,
		},
		{
			Target: commentColumn, Table: qname{Name: "users", Line: 4},
			Column: "id", Text: "identifier", Line: 4,
		},
	}
	if !reflect.DeepEqual(dump.Comments, want) {
		t.Errorf("comments got = %v, want %v", dump.Comments, want)
	}
}

func TestParseSequences(t *testing.T) {
	tests := []struct {
		name string
		src  string
		want []pgSequence
	}{
		{
			name: "create then own",
			src: "CREATE SEQUENCE public.users_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;\n" +
				"ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;",
			want: []pgSequence{{
				Name:        qname{Schema: "public", Name: "users_id_seq", Line: 1},
				OwnedTable:  qname{Schema: "public", Name: "users", Line: 2},
				OwnedColumn: "id",
				Line:        1,
			}},
		},
		{
			name: "owned without a preceding create",
			src:  "ALTER SEQUENCE public.s OWNED BY public.t.id;",
			want: []pgSequence{{
				Name:        qname{Schema: "public", Name: "s", Line: 1},
				OwnedTable:  qname{Schema: "public", Name: "t", Line: 1},
				OwnedColumn: "id",
				Line:        1,
			}},
		},
		{
			name: "owned by none",
			src:  "CREATE SEQUENCE public.s;\nALTER SEQUENCE public.s OWNED BY NONE;",
			want: []pgSequence{{Name: qname{Schema: "public", Name: "s", Line: 1}, Line: 1}},
		},
		{
			name: "other alter sequence actions are ignored",
			src:  "CREATE SEQUENCE public.s;\nALTER SEQUENCE public.s RESTART WITH 42;",
			want: []pgSequence{{Name: qname{Schema: "public", Name: "s", Line: 1}, Line: 1}},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dump, _ := mustParse(t, tt.src)
			if !reflect.DeepEqual(dump.Sequences, tt.want) {
				t.Errorf("sequences got = %v, want %v", dump.Sequences, tt.want)
			}
		})
	}
}

// outOfScopeSource holds one statement of every kind jjf does not map. Not one
// of them may reach the intermediate representation or produce a warning: a
// dump is full of them, and warning about each would bury the warnings that
// describe real information loss.
const outOfScopeSource = `--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET search_path = public;
SET default_table_access_method = heap;
SELECT pg_catalog.set_config('search_path', '', false);
\connect mydb
CREATE SCHEMA app;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;
CREATE TYPE public.status AS ENUM ('a', 'b');
CREATE DOMAIN public.email AS text;
CREATE FUNCTION public.f() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    CREATE TABLE nope (a integer);
    RETURN NEW;
END;
$$;
CREATE TRIGGER t_upd BEFORE UPDATE ON public.t FOR EACH ROW EXECUTE FUNCTION public.f();
CREATE VIEW public.v AS SELECT a FROM public.t;
CREATE MATERIALIZED VIEW public.mv AS SELECT a FROM public.t WITH NO DATA;
ALTER TABLE public.t OWNER TO postgres;
ALTER SCHEMA app OWNER TO postgres;
ALTER FUNCTION public.f() OWNER TO postgres;
GRANT ALL ON TABLE public.t TO reader;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
COPY public.t (a) FROM stdin;
ANALYZE public.t;
`

func TestParseSkipsOutOfScopeStatements(t *testing.T) {
	dump, warnings := mustParse(t, outOfScopeSource)
	if len(warnings) != 0 {
		t.Errorf("warnings got = %v, want none", warnings)
	}
	// The \connect line is the one thing this dump does say about the design.
	want := &pgDump{Database: "mydb"}
	if !reflect.DeepEqual(dump, want) {
		t.Errorf("dump got = %+v, want %+v", dump, want)
	}

}

func TestSkippable(t *testing.T) {
	tests := []struct {
		name string
		src  string
		want bool
	}{
		{name: "set", src: "SET search_path = public;", want: true},
		{name: "select", src: "SELECT pg_catalog.set_config('search_path', '', false);", want: true},
		{name: "create schema", src: "CREATE SCHEMA app;", want: true},
		{name: "create type", src: "CREATE TYPE public.status AS ENUM ('a');", want: true},
		{name: "create function", src: "CREATE FUNCTION public.f() RETURNS void AS $$ $$;", want: true},
		{name: "create view", src: "CREATE VIEW public.v AS SELECT 1;", want: true},
		{name: "create materialized view", src: "CREATE MATERIALIZED VIEW public.mv AS SELECT 1;", want: true},
		{name: "create trigger", src: "CREATE TRIGGER x AFTER INSERT ON public.t FOR EACH ROW EXECUTE FUNCTION f();", want: true},
		{name: "create extension", src: "CREATE EXTENSION pgcrypto;", want: true},
		{name: "grant", src: "GRANT ALL ON TABLE public.t TO reader;", want: true},
		{name: "revoke", src: "REVOKE ALL ON SCHEMA public FROM PUBLIC;", want: true},
		{name: "alter schema", src: "ALTER SCHEMA app OWNER TO postgres;", want: true},
		{name: "alter function", src: "ALTER FUNCTION public.f() OWNER TO postgres;", want: true},
		{name: "create table", src: "CREATE TABLE public.t (a integer);"},
		{name: "create unlogged table", src: "CREATE UNLOGGED TABLE public.t (a integer);"},
		{name: "create index", src: "CREATE INDEX i ON public.t (a);"},
		{name: "create unique index", src: "CREATE UNIQUE INDEX i ON public.t (a);"},
		{name: "create sequence", src: "CREATE SEQUENCE public.s;"},
		{name: "alter table", src: "ALTER TABLE public.t OWNER TO postgres;"},
		{name: "alter sequence", src: "ALTER SEQUENCE public.s OWNED BY public.t.a;"},
		{name: "comment on", src: "COMMENT ON TABLE public.t IS 'x';"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			toks, err := lex([]byte(tt.src))
			if err != nil {
				t.Fatalf("lex returned error %v, want no error", err)
			}
			stmts := splitStatements(toks)
			if len(stmts) != 1 {
				t.Fatalf("statements got = %v, want 1", len(stmts))
			}
			if got := skippable(stmts[0]); got != tt.want {
				t.Errorf("skippable(%q) got = %v, want %v", tt.src, got, tt.want)
			}
		})
	}
}

func TestParseWarnings(t *testing.T) {
	tests := []struct {
		name        string
		src         string
		wantLine    int
		wantMessage string
		wantTables  int
		wantIndexes int
	}{
		{
			name:        "inline check constraint",
			src:         "CREATE TABLE public.t (\n  a integer CHECK (a > 0)\n);",
			wantLine:    2,
			wantMessage: "check constraint is not imported",
			wantTables:  1,
		},
		{
			name:        "table check constraint",
			src:         "CREATE TABLE public.t (\n  a integer,\n  CONSTRAINT t_a_ck CHECK (a > 0)\n);",
			wantLine:    3,
			wantMessage: "constraint t_a_ck on table public.t: check constraint is not imported",
			wantTables:  1,
		},
		{
			name:        "check constraint added later",
			src:         "ALTER TABLE ONLY public.t\n  ADD CONSTRAINT t_a_ck CHECK ((a > 0));",
			wantLine:    2,
			wantMessage: "check constraint is not imported",
		},
		{
			name:        "exclusion constraint",
			src:         "ALTER TABLE ONLY public.t ADD CONSTRAINT t_ex EXCLUDE USING gist (a WITH =);",
			wantLine:    1,
			wantMessage: "exclusion constraint is not imported",
		},
		{
			name:        "partial index",
			src:         "CREATE INDEX t_a_idx ON public.t USING btree (a) WHERE (a IS NOT NULL);",
			wantLine:    1,
			wantMessage: "partial index predicate is not imported",
			wantIndexes: 1,
		},
		{
			name:        "expression index",
			src:         "CREATE INDEX t_a_idx ON public.t USING btree (lower(a));",
			wantLine:    1,
			wantMessage: "expression index is not imported",
		},
		{
			name:        "include columns",
			src:         "CREATE INDEX t_a_idx ON public.t USING btree (a) INCLUDE (b);",
			wantLine:    1,
			wantMessage: "INCLUDE columns are not imported",
			wantIndexes: 1,
		},
		{
			name:        "non-btree access method",
			src:         "CREATE INDEX t_a_idx ON public.t USING gin (a);",
			wantLine:    1,
			wantMessage: "access method gin is not imported",
			wantIndexes: 1,
		},
		{
			name:        "ordering options",
			src:         "CREATE INDEX t_a_idx ON public.t USING btree (a DESC);",
			wantLine:    1,
			wantMessage: "column ordering options are not imported",
			wantIndexes: 1,
		},
		{
			name:        "deferrable constraint",
			src:         "ALTER TABLE ONLY public.t\n  ADD CONSTRAINT t_fk FOREIGN KEY (a) REFERENCES public.u(b) DEFERRABLE INITIALLY DEFERRED;",
			wantLine:    2,
			wantMessage: "DEFERRABLE and NOT VALID flags are not imported",
		},
		{
			name:        "match full",
			src:         "ALTER TABLE ONLY public.t ADD CONSTRAINT t_fk FOREIGN KEY (a) REFERENCES public.u(b) MATCH FULL;",
			wantLine:    1,
			wantMessage: "MATCH FULL is not imported",
		},
		{
			name:        "inherits",
			src:         "CREATE TABLE public.t (\n  a integer\n) INHERITS (public.parent);",
			wantLine:    1,
			wantMessage: "inherited columns are not imported",
			wantTables:  1,
		},
		{
			name:        "partition by",
			src:         "CREATE TABLE public.t (\n  a integer\n) PARTITION BY RANGE (a);",
			wantLine:    1,
			wantMessage: "partitioning is not imported",
			wantTables:  1,
		},
		{
			name:        "partition of",
			src:         "CREATE TABLE public.t_2024 PARTITION OF public.t FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');",
			wantLine:    1,
			wantMessage: "table partition is not imported",
		},
		{
			name:        "typed table",
			src:         "CREATE TABLE public.t OF public.t_type;",
			wantLine:    1,
			wantMessage: "typed table is not imported",
		},
		{
			name:        "generated column",
			src:         "CREATE TABLE public.t (\n  a integer,\n  b integer GENERATED ALWAYS AS (a + 1) STORED\n);",
			wantLine:    3,
			wantMessage: "generated column is imported as an ordinary column",
			wantTables:  1,
		},
		{
			name:        "add column",
			src:         "CREATE TABLE public.t (a integer);\nALTER TABLE public.t ADD COLUMN b integer;",
			wantLine:    2,
			wantMessage: "ADD COLUMN is imported at the end of the column list",
			wantTables:  1,
		},
		{
			name:        "array dimension bound",
			src:         "CREATE TABLE public.t (\n  a integer[3]\n);",
			wantLine:    2,
			wantMessage: "array dimension bound is not imported",
			wantTables:  1,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dump, warnings := mustParse(t, tt.src)
			if len(warnings) != 1 {
				t.Fatalf("warnings got = %v, want exactly 1", warnings)
			}
			if !strings.Contains(warnings[0].Message, tt.wantMessage) {
				t.Errorf("warning got = %q, want it to contain %q", warnings[0].Message, tt.wantMessage)
			}
			if warnings[0].Line != tt.wantLine {
				t.Errorf("warning line got = %v, want %v", warnings[0].Line, tt.wantLine)
			}
			if len(dump.Tables) != tt.wantTables {
				t.Errorf("tables got = %v, want %v", len(dump.Tables), tt.wantTables)
			}
			if len(dump.Indexes) != tt.wantIndexes {
				t.Errorf("indexes got = %v, want %v", len(dump.Indexes), tt.wantIndexes)
			}
		})
	}
}

func TestParseErrors(t *testing.T) {
	tests := []struct {
		name     string
		src      string
		wantLine int
		wantMsg  string
	}{
		{
			name:     "unclosed column list",
			src:      "CREATE TABLE public.t (\n  a integer,\n  b integer\n",
			wantLine: 3,
			wantMsg:  "expected",
		},
		{
			name:     "missing ON in CREATE INDEX",
			src:      "CREATE INDEX t_a_idx public.t (a);",
			wantLine: 1,
			wantMsg:  "expected ON in CREATE INDEX",
		},
		{
			name:     "three part qualified name",
			src:      "CREATE TABLE mydb.public.t (a integer);",
			wantLine: 1,
			wantMsg:  "has too many parts",
		},
		{
			name:     "end of statement after ADD CONSTRAINT",
			src:      "ALTER TABLE public.t\n  ADD CONSTRAINT t_pkey;",
			wantLine: 2,
			wantMsg:  "expected a constraint",
		},
		{
			name:     "missing column list on a primary key",
			src:      "ALTER TABLE public.t ADD CONSTRAINT t_pkey PRIMARY KEY;",
			wantLine: 1,
			wantMsg:  `expected "("`,
		},
		{
			name:     "comment without a string",
			src:      "COMMENT ON TABLE public.t IS 42;",
			wantLine: 1,
			wantMsg:  "expected a string after IS",
		},
		{
			name:     "column definition without a type",
			src:      "CREATE TABLE public.t (\n  a,\n  b integer\n);",
			wantLine: 2,
			wantMsg:  "expected a type name",
		},
		{
			// A truncated file, which is what a dump interrupted mid-write
			// looks like. The line reported is the one the argument list
			// OPENED on rather than the end of the file, so the message points
			// at the parenthesis that was never closed.
			name:     "unterminated type argument list",
			src:      "CREATE TABLE public.t (\n  a numeric(10",
			wantLine: 2,
			wantMsg:  "unterminated type argument list",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var d diagList
			_, err := parse([]byte(tt.src), &d)
			if err == nil {
				t.Fatalf("parse(%q) returned no error, want %q", tt.src, tt.wantMsg)
			}
			var se *syntaxError
			if !errors.As(err, &se) {
				t.Fatalf("parse(%q) error type got = %T, want *syntaxError", tt.src, err)
			}
			if !strings.Contains(se.Msg, tt.wantMsg) {
				t.Errorf("parse(%q) message got = %q, want it to contain %q", tt.src, se.Msg, tt.wantMsg)
			}
			if se.Line != tt.wantLine {
				t.Errorf("parse(%q) line got = %v, want %v", tt.src, se.Line, tt.wantLine)
			}
		})
	}
}

func TestDumpVersion(t *testing.T) {
	tests := []struct {
		name     string
		src      string
		want     string
		wantLine int
	}{
		{
			name: "real header",
			src: "--\n-- PostgreSQL database dump\n--\n\n" +
				"-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)\n" +
				"-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)\n",
			want:     "16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)",
			wantLine: 6,
		},
		{
			name: "no banner",
			src:  "CREATE TABLE public.t (a integer);\n",
		},
		{
			name: "banner past the header window",
			src:  strings.Repeat("--\n", headerLines) + "-- Dumped by pg_dump version 16.13\n",
		},
		{
			name: "banner in a statement is not a banner",
			src:  "SELECT 'Dumped by pg_dump version 99.0';\n",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, line := dumpVersion([]byte(tt.src))
			if got != tt.want || line != tt.wantLine {
				t.Errorf("dumpVersion got = %q at line %v, want %q at line %v", got, line, tt.want, tt.wantLine)
			}
		})
	}
}
