-- Generated by jjf from a database design document.
-- The JSON is the source of truth: edit it and export again, never this file.

-- Tables

CREATE TABLE "order" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user" BIGINT NOT NULL,
    "status" ORDER_STATUS DEFAULT 'pending'::order_status NOT NULL,
    "total" NUMERIC(10,2) DEFAULT 0.00 NOT NULL,
    "rate" NUMERIC(8),
    "placed_at" TIMESTAMP(3) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "shipped_at" TIMESTAMPTZ,
    "flags" INTEGER,
    "payload" JSONB DEFAULT '{}'::jsonb NOT NULL,
    "label" TEXT DEFAULT 'it''s'::text NOT NULL,
    "note" TEXT,
    PRIMARY KEY ("id"),
    UNIQUE ("user", "placed_at")
);

CREATE TABLE "user" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "tags" TEXT[],
    "aliases" VARCHAR(32)[],
    "score" FLOAT(24),
    "home_order_id" BIGINT,
    CONSTRAINT "pk_user" PRIMARY KEY ("id"),
    CONSTRAINT "uq_user_email" UNIQUE ("email")
);

CREATE TABLE "categories" (
    "id" BIGINT NOT NULL,
    "parent_id" BIGINT,
    "name" VARCHAR(64) NOT NULL,
    CONSTRAINT "pk_categories" PRIMARY KEY ("id")
);

CREATE TABLE "audit" (
    "at" TIMESTAMPTZ NOT NULL,
    "who" TEXT NOT NULL
);

-- Indexes

CREATE INDEX "ix_order_status" ON "order" ("status");
CREATE UNIQUE INDEX "ix_categories_name" ON "categories" ("name");

-- Foreign keys

ALTER TABLE "order" ADD FOREIGN KEY ("user") REFERENCES "user" ("id") ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "user" ADD CONSTRAINT "fk_user_home_order" FOREIGN KEY ("home_order_id") REFERENCES "order" ("id") ON DELETE SET NULL;
ALTER TABLE "categories" ADD CONSTRAINT "fk_categories_parent" FOREIGN KEY ("parent_id") REFERENCES "categories" ("id") ON UPDATE NO ACTION ON DELETE SET DEFAULT;

-- Comments

COMMENT ON TABLE "order" IS '受注
A table named after a reserved word. Its description carries an apostrophe - it''s here on purpose -
and a newline, so the COMMENT ON literal has to survive both.';
COMMENT ON COLUMN "order"."id" IS '受注ID';
COMMENT ON COLUMN "order"."user" IS '利用者ID
A column named after a reserved word, in a table named after another one.';
COMMENT ON COLUMN "order"."status" IS '受注状態
A user-defined type. Nothing in the generated script creates it, which is the documented limitation.';
COMMENT ON COLUMN "order"."total" IS '合計金額';
COMMENT ON COLUMN "order"."rate" IS 'レート';
COMMENT ON COLUMN "order"."placed_at" IS '受注日時
The spelled-out type name with a precision, which PostgreSQL only accepts infixed.';
COMMENT ON COLUMN "order"."shipped_at" IS '出荷日時';
COMMENT ON COLUMN "order"."flags" IS 'フラグ
A length a known type cannot take, which is dropped without a word.';
COMMENT ON COLUMN "order"."payload" IS 'ペイロード';
COMMENT ON COLUMN "order"."label" IS 'ラベル''s';
COMMENT ON TABLE "user" IS '利用者
The other half of a cycle: order references user and user references order, which the four fixed phases need no topological sort to survive.';
COMMENT ON COLUMN "user"."id" IS '利用者ID';
COMMENT ON COLUMN "user"."email" IS 'メールアドレス';
COMMENT ON COLUMN "user"."tags" IS 'タグ';
COMMENT ON COLUMN "user"."aliases" IS '別名
An array whose element carries a length, so the parameter goes inside the brackets.';
COMMENT ON COLUMN "user"."score" IS 'スコア
A type this exporter''s table does not list, whose parameter is reproduced in the order the rest of jjf displays one.';
COMMENT ON COLUMN "user"."home_order_id" IS '既定受注ID';
COMMENT ON TABLE "categories" IS '分類
A self-referencing foreign key, and the two referential actions the other tables do not use.';
COMMENT ON COLUMN "categories"."id" IS '分類ID';
COMMENT ON COLUMN "categories"."parent_id" IS '親分類ID';
COMMENT ON COLUMN "categories"."name" IS '名称';
COMMENT ON TABLE "audit" IS '監査';
