-- Generated by jjf from a database design document.
-- The JSON is the source of truth: edit it and export again, never this file.

-- Tables

CREATE TABLE "regions" (
    "country_code" CHAR(2) NOT NULL,
    "region_code" VARCHAR(16) NOT NULL,
    "name" VARCHAR(128) NOT NULL,
    CONSTRAINT "pk_regions" PRIMARY KEY ("country_code", "region_code")
);

CREATE TABLE "warehouses" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "region_code" VARCHAR(16) NOT NULL,
    "country_code" CHAR(2) NOT NULL,
    "code" VARCHAR(32) NOT NULL,
    "slot" VARCHAR(32) NOT NULL,
    "parent_id" BIGINT,
    PRIMARY KEY ("id"),
    UNIQUE ("code")
);

CREATE TABLE "shipments" (
    "warehouse_code" VARCHAR(32) NOT NULL,
    "slot_key" VARCHAR(32) NOT NULL
);

CREATE TABLE "settings" (
    "id" BIGINT NOT NULL,
    "retry_count" INTEGER DEFAULT 0 NOT NULL,
    "rate" NUMERIC DEFAULT 0.00 NOT NULL,
    "threshold" NUMERIC DEFAULT 1e3 NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "closed_at" TIMESTAMP DEFAULT NULL NOT NULL,
    "enabled" BOOLEAN DEFAULT true NOT NULL,
    "updated_at" TIMESTAMP DEFAULT now() NOT NULL,
    "token" UUID DEFAULT gen_random_uuid() NOT NULL,
    "state" TEXT DEFAULT 'pending' NOT NULL,
    "note" TEXT DEFAULT '' NOT NULL,
    "label" TEXT DEFAULT ''::text NOT NULL,
    "owner" TEXT DEFAULT 'it''s'::text NOT NULL,
    "greeting" TEXT DEFAULT 'hello  world'::text NOT NULL,
    "payload" JSONB DEFAULT '{}'::jsonb NOT NULL,
    "status" TEXT DEFAULT 'pending'::text NOT NULL,
    "slots" INTEGER DEFAULT (1 + 2) NOT NULL,
    "tags" TEXT[] DEFAULT ARRAY[]::text[] NOT NULL,
    "escaped" TEXT DEFAULT E'a\b' NOT NULL,
    "grace" INTERVAL DEFAULT INTERVAL '1 day' NOT NULL,
    CONSTRAINT "pk_settings" PRIMARY KEY ("id")
);

-- Indexes

CREATE INDEX "ix_regions_name" ON "regions" ("name");
CREATE UNIQUE INDEX "ix_warehouses_slot" ON "warehouses" ("slot");

-- Foreign keys

ALTER TABLE "warehouses" ADD FOREIGN KEY ("region_code", "country_code") REFERENCES "regions" ("region_code", "country_code") ON DELETE RESTRICT;
ALTER TABLE "warehouses" ADD CONSTRAINT "fk_warehouses_parent" FOREIGN KEY ("parent_id") REFERENCES "warehouses" ("id") ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE "shipments" ADD FOREIGN KEY ("warehouse_code") REFERENCES "warehouses" ("code");
ALTER TABLE "shipments" ADD FOREIGN KEY ("slot_key") REFERENCES "warehouses" ("slot");

-- Comments

COMMENT ON TABLE "regions" IS '地域
A composite primary key, and a non-unique index no foreign key targets.';
COMMENT ON COLUMN "regions"."country_code" IS '国コード';
COMMENT ON COLUMN "regions"."region_code" IS '地域コード';
COMMENT ON COLUMN "regions"."name" IS '名称';
COMMENT ON TABLE "warehouses" IS '倉庫
An unnamed primary key, an unnamed unique key and an unnamed foreign key in one table.';
COMMENT ON COLUMN "warehouses"."id" IS '倉庫ID';
COMMENT ON COLUMN "warehouses"."region_code" IS '地域コード';
COMMENT ON COLUMN "warehouses"."country_code" IS '国コード';
COMMENT ON COLUMN "warehouses"."code" IS '倉庫コード';
COMMENT ON COLUMN "warehouses"."slot" IS 'スロット';
COMMENT ON COLUMN "warehouses"."parent_id" IS '親倉庫ID
A description as well as a logical name, so the comment carries both lines.';
COMMENT ON TABLE "shipments" IS '出荷
No primary key at all, and two unnamed foreign keys that do not collide.';
COMMENT ON COLUMN "shipments"."warehouse_code" IS '倉庫コード';
COMMENT ON COLUMN "shipments"."slot_key" IS 'スロットキー';
COMMENT ON TABLE "settings" IS '設定
Every shape of default that must not produce a finding: literals, an empty SQL string, casts, a qualified type, a function call, an array constructor and a typed literal.';
COMMENT ON COLUMN "settings"."id" IS '設定ID';
COMMENT ON COLUMN "settings"."retry_count" IS '再試行回数';
COMMENT ON COLUMN "settings"."rate" IS 'レート';
COMMENT ON COLUMN "settings"."threshold" IS 'しきい値';
COMMENT ON COLUMN "settings"."created_at" IS '作成日時';
COMMENT ON COLUMN "settings"."closed_at" IS '終了日時';
COMMENT ON COLUMN "settings"."enabled" IS '有効';
COMMENT ON COLUMN "settings"."updated_at" IS '更新日時';
COMMENT ON COLUMN "settings"."token" IS 'トークン';
COMMENT ON COLUMN "settings"."state" IS '状態';
COMMENT ON COLUMN "settings"."note" IS '備考';
COMMENT ON COLUMN "settings"."label" IS 'ラベル';
COMMENT ON COLUMN "settings"."owner" IS '所有者';
COMMENT ON COLUMN "settings"."greeting" IS 'あいさつ';
COMMENT ON COLUMN "settings"."payload" IS 'ペイロード';
COMMENT ON COLUMN "settings"."status" IS '受注状態';
COMMENT ON COLUMN "settings"."slots" IS 'スロット数';
COMMENT ON COLUMN "settings"."tags" IS 'タグ';
COMMENT ON COLUMN "settings"."escaped" IS 'エスケープ';
COMMENT ON COLUMN "settings"."grace" IS '猶予';
