-- Generated by jjf from a database design document.
-- The JSON is the source of truth: edit it and export again, never this file.

-- Tables

CREATE TABLE `order` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '受注ID',
    `user` BIGINT UNSIGNED NOT NULL COMMENT '利用者ID
A column named after a reserved word, in a table named after another one. Its type carries the attribute because the column it references does, and MySQL refuses a foreign key between a signed and an unsigned integer.',
    `status` VARCHAR(16) NOT NULL DEFAULT 'pending' COMMENT '受注状態',
    `total` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0.00 COMMENT '合計金額
An attribute after the type name, so the parameters have to go before it and not after.',
    `rate` DECIMAL(8) COMMENT 'レート',
    `placed_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '受注日時',
    `shipped_at` DATETIME COMMENT '出荷日時',
    `flags` INT COMMENT 'フラグ
A display width MySQL has deprecated, which is dropped without a word.',
    `active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '有効
A boolean, which MySQL stores as TINYINT(1) and mysqldump writes back with its length.',
    `label` VARCHAR(64) NOT NULL DEFAULT 'it''s' COMMENT 'ラベル''s',
    `path` VARCHAR(255) COMMENT 'C:\\tmp
A logical name holding a Windows path. The backslash has to be doubled, or MySQL reads it as an escape and stores a tab.',
    `note` VARCHAR(32),
    PRIMARY KEY (`id`),
    UNIQUE (`user`, `placed_at`)
) COMMENT='受注
A table named after a reserved word. Its description carries an apostrophe - it''s here on purpose -
and a newline, so the table''s COMMENT= literal has to survive both.';

CREATE TABLE `user` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '利用者ID
An unsigned integer that is also the AUTO_INCREMENT column, so the attribute and the keyword meet in one definition.',
    `email` VARCHAR(255) NOT NULL COMMENT 'メールアドレス',
    `score` FLOAT(24) COMMENT 'スコア
A type this exporter''s table does not list, whose parameter is reproduced in the order the rest of jjf displays one.',
    `home_order_id` BIGINT COMMENT '既定受注ID',
    CONSTRAINT `pk_user` PRIMARY KEY (`id`),
    CONSTRAINT `uq_user_email` UNIQUE (`email`)
) COMMENT='利用者
The other half of a cycle: order references user and user references order, which the three fixed phases need no topological sort to survive.';

CREATE TABLE `categories` (
    `id` BIGINT NOT NULL COMMENT '分類ID',
    `parent_id` BIGINT COMMENT '親分類ID',
    `name` VARCHAR(64) NOT NULL COMMENT '名称',
    CONSTRAINT `pk_categories` PRIMARY KEY (`id`)
) COMMENT='分類
A self-referencing foreign key, the fourth referential action, and a unique index in the phase after the tables.';

CREATE TABLE `audit` (
    `at` DATETIME NOT NULL,
    `who` VARCHAR(64) NOT NULL
) COMMENT='監査';

-- Indexes

CREATE INDEX `ix_order_status` ON `order` (`status`);
CREATE UNIQUE INDEX `ix_categories_name` ON `categories` (`name`);

-- Foreign keys

ALTER TABLE `order` ADD FOREIGN KEY (`user`) REFERENCES `user` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE `user` ADD CONSTRAINT `fk_user_home_order` FOREIGN KEY (`home_order_id`) REFERENCES `order` (`id`) ON DELETE SET NULL;
ALTER TABLE `categories` ADD CONSTRAINT `fk_categories_parent` FOREIGN KEY (`parent_id`) REFERENCES `categories` (`id`) ON UPDATE NO ACTION;
