-- Generated by jjf from a database design document.
-- The JSON is the source of truth: edit it and export again, never this file.

-- Tables

CREATE TABLE `regions` (
    `country_code` CHAR(2) NOT NULL COMMENT '国コード',
    `region_code` VARCHAR(16) NOT NULL COMMENT '地域コード',
    `name` VARCHAR(128) NOT NULL COMMENT '名称',
    CONSTRAINT `pk_regions` PRIMARY KEY (`country_code`, `region_code`)
) COMMENT='地域
A composite primary key, and a non-unique index no foreign key targets.';

CREATE TABLE `warehouses` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '倉庫ID',
    `region_code` VARCHAR(16) NOT NULL COMMENT '地域コード',
    `country_code` CHAR(2) NOT NULL COMMENT '国コード',
    `code` VARCHAR(32) NOT NULL COMMENT '倉庫コード',
    `slot` VARCHAR(32) NOT NULL COMMENT 'スロット',
    `parent_id` BIGINT COMMENT '親倉庫ID
A description as well as a logical name, so the comment carries both lines.',
    PRIMARY KEY (`id`),
    UNIQUE (`code`)
) COMMENT='倉庫
An unnamed primary key led by the AUTO_INCREMENT column, an unnamed unique key and an unnamed foreign key in one table.';

CREATE TABLE `shipments` (
    `warehouse_code` VARCHAR(32) NOT NULL COMMENT '倉庫コード',
    `slot_key` VARCHAR(32) NOT NULL COMMENT 'スロットキー'
) COMMENT='出荷
No primary key at all, and two unnamed foreign keys that do not collide. The second targets a unique index rather than a unique key, which is why the index phase has to come first.';

CREATE TABLE `settings` (
    `id` BIGINT NOT NULL COMMENT '設定ID',
    `retry_count` INT NOT NULL DEFAULT 0 COMMENT '再試行回数',
    `rate` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT 'レート',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    `closed_at` DATETIME DEFAULT NULL COMMENT '終了日時',
    `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '有効',
    `token` CHAR(36) NOT NULL DEFAULT (UUID()) COMMENT 'トークン',
    `state` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '状態',
    `note` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '備考',
    `owner` VARCHAR(64) NOT NULL DEFAULT 'it''s' COMMENT '所有者',
    `slots` INT NOT NULL DEFAULT (1 + 2) COMMENT 'スロット数',
    `payload` JSON COMMENT 'ペイロード',
    CONSTRAINT `pk_settings` PRIMARY KEY (`id`)
) COMMENT='設定
Every shape of default MySQL takes: a number, a decimal, CURRENT_TIMESTAMP, an explicit NULL, a string literal, the empty string, an apostrophe inside a literal, and the parenthesised expressions MySQL 8.0.13 and later require for anything else.';

-- Indexes

CREATE INDEX `ix_regions_name` ON `regions` (`name`);
CREATE UNIQUE INDEX `ix_warehouses_slot` ON `warehouses` (`slot`);

-- Foreign keys

ALTER TABLE `warehouses` ADD FOREIGN KEY (`country_code`, `region_code`) REFERENCES `regions` (`country_code`, `region_code`) ON DELETE RESTRICT;
ALTER TABLE `warehouses` ADD CONSTRAINT `fk_warehouses_parent` FOREIGN KEY (`parent_id`) REFERENCES `warehouses` (`id`) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE `shipments` ADD FOREIGN KEY (`warehouse_code`) REFERENCES `warehouses` (`code`) ON UPDATE NO ACTION;
ALTER TABLE `shipments` ADD FOREIGN KEY (`slot_key`) REFERENCES `warehouses` (`slot`);
